### PR TITLE
Fix reactions summary crash

### LINKED ISSUE #5463: Crash - Parcelising ReactionsSummaryData
```
java.lang.RuntimeException: 
  at android.os.Parcel.writeSerializable (Parcel.java:1833)
  at im.vector.app.features.home.room.detail.timeline.item.ReactionsSummaryData.writeToParcel (Unknown Source:54)
  at im.vector.app.features.home.room.detail.timeline.item.MessageInformationData.writeToParcel (Unknown Source:66)
  at im.vector.app.features.home.room.detail.timeline.action.TimelineEventFragmentArgs.writeToParcel (Unknown Source:17)
  at android.os.Parcel.writeParcelable (Parcel.java:1801)
  at android.os.Parcel.writeValue (Parcel.java:1707)
  at android.os.Parcel.writeArrayMapInternal (Parcel.java:928)
  at android.os.BaseBundle.writeToParcelInner (BaseBundle.java:1588)
  at android.os.Bundle.writeToParcel (Bundle.java:1253)
  at android.os.Parcel.writeBundle (Parcel.java:997)
  at androidx.fragment.app.FragmentState.writeToParcel (FragmentState.java:10)
  at android.os.Parcel.writeTypedObject (Parcel.java:1634)
  at android.os.Parcel.writeTypedList (Parcel.java:1513)
  at android.os.Parcel.writeTypedList (Parcel.java:1470)
  at androidx.fragment.app.FragmentManagerState.writeToParcel (FragmentManagerState.java:1)
  at android.os.Parcel.writeParcelable (Parcel.java:1801)
  at android.os.Parcel.writeValue (Parcel.java:1707)
  at android.os.Parcel.writeArrayMapInternal (Parcel.java:928)
  at android.os.BaseBundle.writeToParcelInner (BaseBundle.java:1588)
  at android.os.Bundle.writeToParcel (Bundle.java:1253)
  at android.os.Parcel.writeBundle (Parcel.java:997)
  at android.os.Parcel.writeValue (Parcel.java:1698)
  at android.os.Parcel.writeArrayMapInternal (Parcel.java:928)
  at android.os.BaseBundle.writeToParcelInner (BaseBundle.java:1588)
  at android.os.Bundle.writeToParcel (Bundle.java:1253)
  at android.os.Parcel.writeBundle (Parcel.java:997)
  at android.os.Parcel.writeValue (Parcel.java:1698)
  at android.os.Parcel.writeArrayMapInternal (Parcel.java:928)
  at android.os.BaseBundle.writeToParcelInner (BaseBundle.java:1588)
  at android.os.Bundle.writeToParcel (Bundle.java:1253)
  at android.app.IActivityTaskManager$Stub$Proxy.activityStopped (IActivityTaskManager.java:4542)
  at android.app.servertransaction.PendingTransactionActions$StopInfo.run (PendingTransactionActions.java:145)
  at android.os.Handler.handleCallback (Handler.java:888)
  at android.os.Handler.dispatchMessage (Handler.java:100)
  at android.os.Looper.loop (Looper.java:213)
  at android.app.ActivityThread.main (ActivityThread.java:8178)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:513)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1101)
Caused by: java.io.NotSerializableException: 
  at java.io.ObjectOutputStream.writeObject0 (ObjectOutputStream.java:1240)
  at java.io.ObjectOutputStream.defaultWriteFields (ObjectOutputStream.java:1604)
  at java.io.ObjectOutputStream.writeSerialData (ObjectOutputStream.java:1565)
  at java.io.ObjectOutputStream.writeOrdinaryObject (ObjectOutputStream.java:1488)
  at java.io.ObjectOutputStream.writeObject0 (ObjectOutputStream.java:1234)
  at java.io.ObjectOutputStream.writeObject (ObjectOutputStream.java:354)
  at android.os.Parcel.writeSerializable (Parcel.java:1828)
```

| Occurrences (30 days) | Total Occurrences | Impacted users (lifetime) |
| --- | --- | --- |
| 660 | 689 | 592 |

https://play.google.com/console/u/0/developers/{redacted}/app/{redacted}/vitals/crashes/99f978d5/details?versionCode=40104002/details?installedFrom=PLAY_STORE&days=30

### PR DESCRIPTION
**Pull request by ariskotsomitopoulos**
Fixing `NotSerializableException` crash on reactions summary

 Closes #5463

### CODE REVIEW

File: vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/MessageInformationData.kt [hunk 1]
```diff
@@ -58,11 +58,14 @@ data class ReferencesInfoData(
...
-        val showAll: Boolean = false,
+        val showAll: Boolean = false
+) : Parcelable
+
+data class ReactionsSummaryEvents(
         val onShowMoreClicked: () -> Unit,
         val onShowLessClicked: () -> Unit,
         val onAddMoreClicked: () -> Unit
-) : Parcelable
+)
```
Comment (bmarty) [inline vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/MessageInformationData.kt:68]: I though the idea was to avoid having lambda in data class. Anyway I understand why it should fix the crash.

On my side, I would have added a new sub interface to [TimelineEventController.Callback](https://github.com/vector-im/element-android/blob/main/vector/src/main/java/im/vector/app/features/home/room/detail/timeline/TimelineEventController.kt#L116), but I did not try to do so (this is maybe not better).

File: vector/src/main/java/im/vector/app/features/home/room/detail/timeline/TimelineEventController.kt [hunk 2]
```diff
@@ -415,7 +416,12 @@ class TimelineEventController @Inject constructor(private val dateFormatter: Vec
                         partialState = partialState,
                         lastSentEventIdWithoutReadReceipts = lastSentEventWithoutReadReceipts,
                         callback = callback,
-                        eventsGroup = timelineEventsGroup
+                        eventsGroup = timelineEventsGroup,
+                        reactionsSummaryEvents = ReactionsSummaryEvents(
+                                onAddMoreClicked = { reactionListFactory.onAddMoreClicked(callback, event) },
```
Comment (ganfra) [inline vector/src/main/java/im/vector/app/features/home/room/detail/timeline/TimelineEventController.kt:421]: I would avoid creating a new data class to be pass everywhere. Would prefer having  ReactionsSummaryCallback as interface with empty default implementation. Then let TimelineEventController.Callback inherits this interface and just delegate to reactionListFactory in the case of onShowLess and onShowMore

**Review by bmarty — COMMENTED** [review]
LGTM (did not test it though)

File: vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/MessageInformationData.kt (hunk 1 above)
Comment (ouchadam) [reply vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/MessageInformationData.kt:68]: I would be up for avoiding the bundle of functions by passing an interface instead (not a blocker for this PR from me)

**Review by ganfra — CHANGES_REQUESTED** [review]

**Review by ouchadam — APPROVED** [review]
thanks for the fix! :crossed_fingers:  could be nice to avoid holding the callbacks in a data class, not a blocker for the release fix

File: vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/MessageInformationData.kt (hunk 1 above)
Comment (ariskotsomitopoulos) [reply vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/MessageInformationData.kt:68]: I Suspect the problem is due to the `@Parcelize` and not the data class. If the crash continue then we will change it with a callback.

I also tried with callback at first but then you would have to implement that callback on `TimelineFragment` and we don't want that there. I think this is a bit more clear with lamda

**Comment by ganfra** [comment]
> thanks for the fix! 🤞 could be nice to avoid holding the callbacks in a data class, not a blocker for the release fix
> 
> EDIT - just seen @ganfra 's comment, will avoid merging until we're all aligned

We can change that later for not blocking the release :)

File: vector/src/main/java/im/vector/app/features/home/room/detail/timeline/TimelineEventController.kt (hunk 2 above)
Comment (ariskotsomitopoulos) [reply vector/src/main/java/im/vector/app/features/home/room/detail/timeline/TimelineEventController.kt:421]: This was my first attempt. Let me check if I can enhance it fast for the release.
