### PR TITLE
Better room preview, use room Summary API if available

### LINKED ISSUE #3946: Restricted Room previews aren't working
### Steps to reproduce

1. In Rooms list in Space
2. Select Room that am not a member of (appears in Suggested list)
3. Bottom sheet appears "This room can't be previewed" 

### What did you expect?

To see a preview of the room

### What happened?

Bottom sheet appears "This room can't be previewed" 
(Also, content should display room name, not Matrix ID; [https://github.com/vector-im/element-android/issues/3940](url) )

### Your phone model

_No response_

### Operating system version

_No response_

### Application version and app store

https://buildkite.com/organizations/matrix-dot-org/pipelines/element-android/builds/3224/jobs/a1fe572d-8a7b-4406-8a0f-37f4c9ff4787/artifacts/30990f61-8f7d-4dc6-af1e-340765110cc6

### Homeserver

_No response_

### Have you submitted a rageshake?

No

### PR DESCRIPTION
**Pull request by BillCarsonFr**
Fixes #3946 

Implements [MSC 3266](https://github.com/matrix-org/matrix-doc/pull/3266)

Improve Room preview by using the new Room Summary API (stripped state). This allows you to get minimum information on a room (name/topic/avatar/type/member count...) even if you cannot peek state or if it's not in public directory.
Basically if you can join the room you will get a summary.

### CODE REVIEW

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/GetRoomSummaryTask.kt [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+}
+
+internal class DefaultGetRoomSummaryTask @Inject constructor(
+        private val roomAPI: RoomAPI,
+        private val globalErrorReceiver: GlobalErrorReceiver
+) : GetRoomSummaryTask {
+
+    override suspend fun execute(params: GetRoomSummaryTask.Params): RoomStrippedState {
+        return executeRequest(globalErrorReceiver) {
+            roomAPI.getRoomSummary(params.roomId, params.viaServers)
```
Comment (bmarty) [inline matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/GetRoomSummaryTask.kt:39]: Is there any fallback if this unstable API returns a 404? This can occur a lot.

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/RoomAPI.kt [hunk 2]
```diff
@@ -381,4 +382,14 @@ internal interface RoomAPI {
...
     suspend fun upgradeRoom(@Path("roomId") roomId: String,
                             @Body body: RoomUpgradeBody): RoomUpgradeResponse
+
+    /**
+     * The API returns the summary of the specified room, if the room could be found and the client should be able to view
+     * its contents according to the join_rules, history visibility, space membership and similar rules outlined in MSC3173
+     * as well as if the user is already a member of that room.
+     * https://github.com/deepbluev7/matrix-doc/blob/room-summaries/proposals/3266-room-summary.md
+     */
+    @GET(NetworkConstants.URI_API_PREFIX_PATH_UNSTABLE + "im.nheko.summary/rooms/{roomidOrAlias}/summary")
```
Comment (bmarty) [inline matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/RoomAPI.kt:392]: I know it is like that in the MSC, I've made [a comment about it](https://github.com/matrix-org/matrix-doc/pull/3266/files#r708524182), but here, can you write `roomIdOrAlias`, with a capital `I` please?

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/RoomModule.kt [hunk 3]
```diff
@@ -253,4 +253,7 @@ internal abstract class RoomModule {
 
     @Binds
     abstract fun bindSign3pidInvitationTask(task: DefaultSign3pidInvitationTask): Sign3pidInvitationTask
+
+    @Binds
+    abstract fun bindSGetRoomSummaryTask(task: DefaultGetRoomSummaryTask): GetRoomSummaryTask
```
Comment (bmarty) [inline matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/RoomModule.kt:258]: Remove the extra "S"

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/peeking/PeekRoomTask.kt [hunk 4]
```diff
@@ -70,6 +72,25 @@ internal class DefaultPeekRoomTask @Inject constructor(
             serverList = emptyList()
         }
 
+        // If the room summary API is available on the Home Server we should try it first
+        val strippedState = tryOrNull("Failed to get room stripped state roomId:$roomId") {
+            getRoomSummaryTask.execute(GetRoomSummaryTask.Params(roomId, serverList))
+        }
+        if (strippedState != null) {
```
Comment (bmarty) [inline matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/peeking/PeekRoomTask.kt:79]: So in case of 404 `strippedState` will be null so OK 👍

**Review by bmarty — COMMENTED** [review]
LGTM, just a few minor remarks

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/GetRoomSummaryTask.kt (hunk 1 above)
Comment (BillCarsonFr) [reply matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/GetRoomSummaryTask.kt:39]: It's done in PeekRoom task. It will try first the summary API, then check the public repository, and fallback to raw peek state if no results

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/RoomModule.kt (hunk 3 above)
Comment (BillCarsonFr) [reply matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/RoomModule.kt:258]: Done
