### PR TITLE
Unable to render messages

### LINKED ISSUE #4733: Element Android can't render messages
### Steps to reproduce

I'm not sure how to reproduce, but I remember disabling Google Play Services, then open Element, then it can't render messages whatsoever (except for images)

I tried re-enabling Google Play Services as well, but that didn't work, clearing cache didn't work as well, even logging out and logging in again doesn't make the message rendering work normally again

then
> I updated Google Play Services once I re-enabled it, and that seems to fix the message rendering issue

#### What did you expect?
Messages to be rendered normally

#### What happened instead?
Element Android cannot render the messages, I sent a rageshake about this

### Your phone model

Samsung Galaxy J1 ace

### Operating system version

Android 5.1.1

### Application version and app store

1.3.10 [40103101] (G-b4948)

### Homeserver

matrix.org

### Will you send logs?

Yes

### PR DESCRIPTION
**Pull request by ouchadam**
Fixes #4733 

The timeline is failing to render whilst the emoji library is initialising. Fixed by using our safe wrapper which we already use in other places with emoji capabilities 

```
E/ /Tag: failed to create message item
java.lang.IllegalStateException: Not initialized yet
	at androidx.core.util.Preconditions.checkState(Preconditions.java:1)
	at androidx.emoji2.text.EmojiCompat.process(EmojiCompat.java:3)
	at androidx.emoji2.text.EmojiCompat.process(EmojiCompat.java:2)
	at im.vector.app.features.html.SpanUtils.getBindingOptions(SpanUtils.kt:1)
	at im.vector.app.features.home.room.detail.timeline.factory.MessageItemFactory.buildMessageTextItem(MessageItemFactory.kt:1)
	at im.vector.app.features.home.room.detail.timeline.factory.MessageItemFactory.buildItemForTextContent(MessageItemFactory.kt:18)
	at im.vector.app.features.home.room.detail.timeline.factory.MessageItemFactory.create(MessageItemFactory.kt:33)
	at im.vector.app.features.home.room.detail.timeline.factory.TimelineItemFactory.create(TimelineItemFactory.kt:15)
	at im.vector.app.features.home.room.detail.timeline.TimelineEventController.buildCacheItem(TimelineEventController.kt:9)
	at im.vector.app.features.home.room.detail.timeline.TimelineEventController.buildCacheItemsIfNeeded(TimelineEventController.kt:27)
	at im.vector.app.features.home.room.detail.timeline.TimelineEventController.getModels(TimelineEventController.kt:1)
	at im.vector.app.features.home.room.detail.timeline.TimelineEventController.buildModels(TimelineEventController.kt:9)
	at com.airbnb.epoxy.EpoxyController$1.run(EpoxyController.java:6)
```

| BEFORE | AFTER |
| --- | --- |
|Screenshot_20211217_091758|Screenshot_20211217_091942

### CODE REVIEW

**Review by BillCarsonFr — APPROVED** [review]
LGTM

**Review by ganfra — APPROVED** [review]
Thanks

File: vector/src/main/java/im/vector/app/EmojiCompatWrapper.kt [hunk 1]
```diff
@@ -23,8 +23,12 @@ import timber.log.Timber
 import javax.inject.Inject
 import javax.inject.Singleton
 
+fun interface EmojiSpanify {
```
Comment (ouchadam) [inline vector/src/main/java/im/vector/app/EmojiCompatWrapper.kt:26]: extracted out the processing to allow the tests to provide their own implementation that doesn't rely on any singleton flags

Comment (bmarty) [reply vector/src/main/java/im/vector/app/EmojiCompatWrapper.kt:26]: `fun interface` 🎉
