### PR TITLE
Remove redundant highlight on add poll option button

### LINKED ISSUE #5178: Remove redundant highlight on add poll option button
### Steps to reproduce

Highlighting "add option" button seems weird.

### Outcome

Remove highlight of the button

### Your phone model

_No response_

### Operating system version

_No response_

### Application version and app store

_No response_

### Homeserver

_No response_

### Will you send logs?

No

### PR DESCRIPTION
**Pull request by onurays**
Fixes #5178.

### CODE REVIEW

File: vector/src/main/java/im/vector/app/core/ui/list/GenericButtonItem.kt [hunk 1]
```diff
@@ -70,6 +75,12 @@ abstract class GenericButtonItem : VectorEpoxyModel<GenericButtonItem.Holder>()
         val textStyle = if (bold) Typeface.BOLD else Typeface.NORMAL
         holder.button.setTypeface(null, textStyle)
 
+        holder.button.rippleColor = if (highlight) {
```
Comment (ouchadam) [inline vector/src/main/java/im/vector/app/core/ui/list/GenericButtonItem.kt:78]: was `R.attr.colorSecondary` also the previous highlight colour? just in case we've changed the default value for a generic component which might be used in other places

Comment (onurays) [reply vector/src/main/java/im/vector/app/core/ui/list/GenericButtonItem.kt:78]: Good point, button has `style="@style/Widget.Vector.Button.Text"` and this style has `<item name="colorControlHighlight">?colorSecondary</item>`. But I will check if `rippleCount` has the same effect with `colorControlHighlight`.

Comment (ouchadam) [reply vector/src/main/java/im/vector/app/core/ui/list/GenericButtonItem.kt:78]: thanks!

Comment (onurays) [reply vector/src/main/java/im/vector/app/core/ui/list/GenericButtonItem.kt:77]: Actually was not the exact color. Sorry, now fixed.

**Review by ouchadam — APPROVED** [review]
