### PR TITLE
Thread list crashes

### LINKED ISSUE #7912: Thread list screen crashes - no network and 400.
### Steps to reproduce

1. Airplane mode
2. go the the tread list of a room
3. Observe the crash

The app also crashes when there is network, but when the homeserver does not support the API `_matrix/client/v1/rooms/{roomId}/threads` causing a HTTP 400. The app should be robust to this server limitation. If possible roll back to the previous way to show the thread list.

#### What did you expect?

No crash and a message describing the issue

#### What happened instead?
 
The app crashes.

### Your phone model

any

### Operating system version

any

### Application version and app store

1.5.18

### Homeserver

any for no network case, old one for the 400.

### Will you send logs?

No

### Are you willing to provide a PR?

Yes

### PR DESCRIPTION
**Pull request by bmarty**
## Type of change

- [ ] Feature
- [x] Bugfix
- [ ] Technical
- [ ] Other :

## Content

Handle network error on API `rooms/{roomId}/threads`

## Motivation and context

Fixes #7912 

## Tests

- See #7912 

## Tested devices

- [ ] Physical
- [x] Emulator
- OS version(s):

## Checklist

- [ ] Changes has been tested on an Android device or Android emulator with API 21
- [ ] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#accessibility
- [ ] Pull request is based on the develop branch
- [ ] Pull request includes a new file under ./changelog.d. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#changelog
- [ ] Pull request includes screenshots or videos if containing UI changes
- [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [ ] You've made a self review of your PR
- [ ] If you have modified the screen flow, or added new screens to the application, you have updated the test [UiAllScreensSanityTest.allScreensTest()](https://github.com/vector-im/element-android/blob/main/vector/src/androidTest/java/im/vector/app/ui/UiAllScreensSanityTest.kt#L73)

### CODE REVIEW

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/threads/FetchThreadsResult.kt [hunk 1]
```diff
@@ -19,5 +19,4 @@ package org.matrix.android.sdk.api.session.room.threads
 sealed class FetchThreadsResult {
     data class ShouldFetchMore(val nextBatch: String) : FetchThreadsResult()
     object ReachedEnd : FetchThreadsResult()
-    object Failed : FetchThreadsResult()
```
Comment (bmarty) [inline matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/threads/FetchThreadsResult.kt:22]: (this was not used)

**Review by yostyle — APPROVED** [review]
LGTM
