### PR TITLE
Fixing crash adding room by QR code

### LINKED ISSUE #5295: Crash - Mavericks IllegalArgumentException in QrCodeScannerFragment
```
java.lang.RuntimeException: 
  at android.app.ActivityThread.performResumeActivity (ActivityThread.java:4539)
  at android.app.ActivityThread.handleResumeActivity (ActivityThread.java:4575)
  at android.app.servertransaction.ResumeActivityItem.execute (ResumeActivityItem.java:52)
  at android.app.servertransaction.TransactionExecutor.executeLifecycleState (TransactionExecutor.java:181)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:102)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2235)
  at android.os.Handler.dispatchMessage (Handler.java:107)
  at android.os.Looper.loop (Looper.java:227)
  at android.app.ActivityThread.main (ActivityThread.java:7822)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:492)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1027)
Caused by: java.lang.IllegalArgumentException: 
  at com.airbnb.mvrx.MavericksExtensionsKt$args$1.getValue (MavericksExtensions.kt:8)
  at im.vector.app.features.qrcode.QrCodeScannerFragment.getScannerArgs (QrCodeScannerFragment.kt:1)
  at im.vector.app.features.qrcode.QrCodeScannerFragment.onViewCreated (QrCodeScannerFragment.kt:2)
  at androidx.fragment.app.Fragment.performViewCreated (Fragment.java:1)
  at androidx.fragment.app.FragmentStateManager.createView (FragmentStateManager.java:39)
  at androidx.fragment.app.FragmentStateManager.moveToExpectedState (FragmentStateManager.java:27)
  at androidx.fragment.app.FragmentManager.executeOpsTogether (FragmentManager.java:122)
  at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute (FragmentManager.java:9)
  at androidx.fragment.app.FragmentManager.execPendingActions (FragmentManager.java:14)
  at androidx.fragment.app.FragmentActivity.onResume (FragmentActivity.java:5)
  at im.vector.app.core.platform.VectorBaseActivity.onResume (VectorBaseActivity.kt:1)
  at android.app.Instrumentation.callActivityOnResume (Instrumentation.java:1453)
  at android.app.Activity.performResume (Activity.java:8125)
  at android.app.ActivityThread.performResumeActivity (ActivityThread.java:4529)
```

| Occurrences (30 days) | Total Occurrences | Impacted users (lifetime) |
| --- | --- | --- |
| 61 | 76 | 72 |

https://play.google.com/console/u/0/developers/{redacted}/app/{redacted}/vitals/crashes/99f978d5/details?versionCode=40104002/details?installedFrom=PLAY_STORE&days=30

### PR DESCRIPTION
**Pull request by ouchadam**
## Type of change

- [ ] Feature
- [x] Bugfix
- [ ] Technical
- [ ] Other :

## Content

Adds missing `QrScannerFragment` arguments when scanning a QR code accept accepting the camera permission for the first time 

## Motivation and context

Fixes #5295

## Screenshots / GIFs

| BEFORE | AFTER | 
| --- | --- |
|before-add-room-qr|after-add-room-qa

## Tests

- With a fresh install
- Attempt to add a room by qr code

## Tested devices

- [x] Physical
- [ ] Emulator
- OS version(s): Android 10

### CODE REVIEW

File: vector/src/main/java/im/vector/app/features/qrcode/QrCodeScannerFragment.kt [hunk 1]
```diff
@@ -53,10 +53,10 @@ data class QrScannerArgs(
         @StringRes val titleRes: Int
 ) : Parcelable
 
-open class QrCodeScannerFragment @Inject constructor() : VectorBaseFragment<FragmentQrCodeScannerBinding>(), ZXingScannerView.ResultHandler {
+class QrCodeScannerFragment @Inject constructor() : VectorBaseFragment<FragmentQrCodeScannerBinding>(), ZXingScannerView.ResultHandler {
 
     private val qrViewModel: QrCodeScannerViewModel by activityViewModel()
-    private val scannerArgs: QrScannerArgs? by args()
+    private val scannerArgs: QrScannerArgs by args()
```
Comment (ouchadam) [inline vector/src/main/java/im/vector/app/features/qrcode/QrCodeScannerFragment.kt:59]: `args()` can't be null

```kotlin
fun args(): T {
  ...
  return value ?: throw IllegalArgumentException("")
} 
```

**Review by ganfra — APPROVED** [review]
LGTM

**Review by bmarty — APPROVED** [review]
Thanks!
