### PR TITLE
Open general settings performance

### LINKED ISSUE #5918: If media cache is large, Settings > General takes a long time to open
### Steps to reproduce

1. Have a large enough media cache. 100+ MB was enough for my device. Others might need a larger cache.
2. Open the General menu in Settings. Note the time it takes to open the menu.
3. Clear media cache.
4. Open the menu again. Note the drastically reduced time taken for it to open.

#### What did you expect?

The menu should open just as fast as other menus do. And it should take roughly the same time to open on every try.

#### What happened instead?

With a large enough media cache, the menu takes a long time to open (~5-10 seconds).

A wild guess is that the app doesn't open the menu until it has calculated the media cache, which can take a long time if the cache is large enough, or if the device is old, with slow I/O.

### Your phone model

_No response_

### Operating system version

_No response_

### Application version and app store

1.4.11 (F-Droid)

### Homeserver

_No response_

### Will you send logs?

No

### PR DESCRIPTION
**Pull request by bmarty**
## Type of change

- [ ] Feature
- [x] Bugfix
- [ ] Technical
- [ ] Other :

## Content

Compute cache storage in background.

## Motivation and context

Closes #5918 
Also reported in FOSDEM.

## Tests

- Open the general setting with a big cache. For test add a delay to simulate a long computation and see that the screen is opened and `Loading...` is displayed in the preference summary.

## Tested devices

- [ ] Physical
- [x] Emulator
- OS version(s):

## Checklist

- [ ] Changes has been tested on an Android device or Android emulator with API 21
- [ ] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#accessibility
- [ ] Pull request is based on the develop branch
- [ ] Pull request includes a new file under ./changelog.d. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#changelog
- [ ] Pull request includes screenshots or videos if containing UI changes
- [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [ ] You've made a self review of your PR
- [ ] If you have modified the screen flow, or added new screens to the application, you have updated the test [UiAllScreensSanityTest.allScreensTest()](https://github.com/vector-im/element-android/blob/main/vector/src/androidTest/java/im/vector/app/ui/UiAllScreensSanityTest.kt#L73)

### CODE REVIEW

File: vector/src/main/java/im/vector/app/features/settings/VectorSettingsGeneralFragment.kt [hunk 1]
```diff
@@ -250,37 +250,28 @@ class VectorSettingsGeneralFragment :
...
-
-                    withContext(Dispatchers.IO) {
-                        // On BG thread
-                        Glide.get(requireContext()).clearDiskCache()
-
-                        newSize = getSizeOfFiles(File(requireContext().cacheDir, DiskCache.Factory.DEFAULT_DISK_CACHE_DIR))
-                        newSize += session.fileService().getCacheSize()
+            lifecycleScope.launch(Dispatchers.Main) {
+                it.summary = getString(R.string.loading)
+                val size = getCacheSize()
```
Comment (BillCarsonFr) [inline vector/src/main/java/im/vector/app/features/settings/VectorSettingsGeneralFragment.kt:255]: This should be dipatched to .io I think?

Comment (BillCarsonFr) [reply vector/src/main/java/im/vector/app/features/settings/VectorSettingsGeneralFragment.kt:255]: Oh I see it's done in the method itself

**Review by BillCarsonFr — APPROVED** [review]
LGTM
