### PR TITLE
Thread redaction will now update the thread summary counter

### LINKED ISSUE #5598: Thread summary counts redacted messages
### Steps to reproduce

1. Where are you starting? What can you see?
 -There's a thread with multiple replies from different users
2. What do you click?
 -Room admin deletes some of those replies
3. More steps…
 -Those replies are gone but the reply counter in thread summary still shows them

Thread summary:
image

Actual thread:
image

#### What did you expect?
I expected the thread summary to show the correct count of replies within that thread (in this case one).
#### What happened instead?
Thread summary shows three replies instead.

### Your phone model

Samsung Galaxy A40

### Operating system version

Android 11

### Application version and app store

1.4.6-dev [40104060] (G-b6953) feature/aris/thread_labs_notice_users

### Homeserver

matrix.org

### Will you send logs?

No

### LINKED ISSUE #5625: Empty threads should update thread summary
When there is an empty thread after a thread event redaction, thread summary should be gone and thread list should remove that root thread record

How to reproduce?
1. Create a thread
2. Reply to in that thread
3. Thread will have 1 message
4. Delete that message

Thread should be destroyed, while its empty:
1. Main timeline thread summary should be gone
2. Thread list record for that thread should be gone

### PR DESCRIPTION
**Pull request by ariskotsomitopoulos**
## Type of change

- [x] Bugfix
## Content

- When there is an empty thread after a thread event redaction, thread summary should be gone and thread list should remove that root thread record
- Redaction of a thread event should reduce the thread counter in main timeline thread summary

|Before redaction|After redaction|
| --- | --- | 
|Screenshot_20220324-170027_Element dbg|Screenshot_20220324-170045_Element dbg|

Closes #5598
Closes #5625

### CODE REVIEW

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/helper/ThreadEventsHelper.kt [hunk 1]
```diff
@@ -124,9 +128,38 @@ internal fun EventEntity.threadSummaryInThread(realm: Realm, rootThreadEventId:
...
 
-    return Summary(messages, result)
+    return Summary(numberOfThread, result)
 }
 
+/**
+ * Counts the number of threads in the main timeline thread summary,
+ * with respect to redactions.
+ */
+internal fun countThreads(realm: Realm, roomId: String, rootThreadEventId: String): Int? =
```
Comment (ouchadam) [inline matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/helper/ThreadEventsHelper.kt:138]: is this counting replies in threads?

Comment (ariskotsomitopoulos) [reply matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/helper/ThreadEventsHelper.kt:138]: Yes, maybe I should rename it to be more clear :)

**Comment by bmarty** [comment]
You have to repeat the keyword of GitHub

image

Here only 1 issues will be closed when the PR will be merged

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/helper/ThreadEventsHelper.kt [hunk 2]
```diff
@@ -90,19 +95,18 @@ internal fun EventEntity.markEventAsRoot(
...
  */
 internal fun EventEntity.threadSummaryInThread(realm: Realm, rootThreadEventId: String, chunkEntity: ChunkEntity?): Summary {
-    // Number of messages
-    val messages = TimelineEventEntity
-            .whereRoomId(realm, roomId = roomId)
-            .equalTo(TimelineEventEntityFields.ROOT.ROOT_THREAD_EVENT_ID, rootThreadEventId)
-            .distinct(TimelineEventEntityFields.ROOT.EVENT_ID)
-            .count()
-            .toInt()
+    val numberOfThread = countThreadReplies(
```
Comment (ouchadam) [inline matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/helper/ThreadEventsHelper.kt:103]: would be handy to sync up the variable names with the function as well ^^^

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/prune/RedactionEventProcessor.kt [hunk 3]
```diff
@@ -104,6 +109,39 @@ internal class RedactionEventProcessor @Inject constructor() : EventInsertLivePr
...
+            val rootThreadEvent = eventToPrune.findRootThreadEvent() ?: return
+            val rootThreadEventId = eventToPrune.rootThreadEventId ?: return
+
+            val numberOfThreads = countThreadReplies(
+                    realm = realm,
+                    roomId = roomId,
+                    rootThreadEventId = rootThreadEventId
+            ) ?: return
+
+            rootThreadEvent.numberOfThreads = numberOfThreads
```
Comment (ouchadam) [inline matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/prune/RedactionEventProcessor.kt:132]: `rootThreadEvent.numberOfThreads` I'm assuming this is also number of replies in the thread?

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/prune/RedactionEventProcessor.kt [hunk 4]
```diff
@@ -104,6 +109,39 @@ internal class RedactionEventProcessor @Inject constructor() : EventInsertLivePr
...
+        if (eventToPrune.isThread() && !isLocalEcho) {
+            val roomId = eventToPrune.roomId
+            val rootThreadEvent = eventToPrune.findRootThreadEvent() ?: return
+            val rootThreadEventId = eventToPrune.rootThreadEventId ?: return
+
+            val numberOfThreads = countThreadReplies(
+                    realm = realm,
+                    roomId = roomId,
+                    rootThreadEventId = rootThreadEventId
+            ) ?: return
```
Comment (ouchadam) [inline matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/prune/RedactionEventProcessor.kt:130]: should we treat `null` the same as `0` replies?

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/prune/RedactionEventProcessor.kt (hunk 3 above)
Comment (ariskotsomitopoulos) [reply matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/prune/RedactionEventProcessor.kt:132]: Yes, I didn't name it thread replies, while someone may be confused that are the replies (long press reply) within threads. I decided to call a `thread` every individual thread message, but now I don't really like it. A better name might be `threadNormalReplies`, `threadMessages`, `inThreadMessages`

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/prune/RedactionEventProcessor.kt (hunk 4 above)
Comment (ariskotsomitopoulos) [reply matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/prune/RedactionEventProcessor.kt:130]: Null will never happen here, I refactored the code to be more clear

**Review by ouchadam — APPROVED** [review]
thanks for updates, much easier to follow! :100:
