### PR TITLE
Unable to upload .ogg to rooms

### LINKED ISSUE #4552: Unable to upload .ogg audio files
### Steps to reproduce

1. Upload a local .ogg file to a room
2. Upload fails and retry fails

permission-denied

#### What did you expect?
The file to upload

#### What happened instead?
The file failed to upload

### Your phone model

_No response_

### Operating system version

_No response_

### Application version and app store

1.3.7

### Homeserver

matrix.org

### Will you send logs?

No

### PR DESCRIPTION
**Pull request by ouchadam**
Fixes #4552 .ogg files failing to upload

- We were inferring that uploaded `.ogg` audio files were our temporary voice messages and attempting to delete, android throws a security exception as we open external files as read only which caused the upload to fail entirely.
- Adds a dedicated `VOICE_MESSAGE` type in order to only delete the files which we control

| PENDING VOICE MESSAGE | FILE EXISTS | VOICE MESSAGE SENT | FILE DELETED |
| --- | --- | --- | --- |
|Screenshot_20211124_103538|2021-11-24T10:36:15,422339591+00:00|Screenshot_20211124_103640|2021-11-24T10:36:45,675599838+00:00

| BEFORE UPLOADING .OGG | AFTER UPLOADING .OGG | 
| --- | --- |
|permission-denied|after-upload-ogg

### CODE REVIEW

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/content/UploadContentWorker.kt [hunk 1]
```diff
@@ -280,7 +280,7 @@ internal class UploadContentWorker(val context: Context, params: WorkerParameter
                 }
 
                 // Delete the temporary voice message file
-                if (params.attachment.type == ContentAttachmentData.Type.AUDIO && params.attachment.mimeType == MimeTypes.Ogg) {
+                if (params.attachment.type == ContentAttachmentData.Type.VOICE_MESSAGE) {
```
Comment (bmarty) [inline matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/content/UploadContentWorker.kt:283]: I assume that the file was actually sent but in the UI it appears as an error? Anyway thanks for the fix!

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/LocalEchoEventFactory.kt [hunk 2]
```diff
@@ -205,10 +205,11 @@ internal class LocalEchoEventFactory @Inject constructor(
...
     fun createMediaEvent(roomId: String, attachment: ContentAttachmentData): Event {
         return when (attachment.type) {
-            ContentAttachmentData.Type.IMAGE -> createImageEvent(roomId, attachment)
-            ContentAttachmentData.Type.VIDEO -> createVideoEvent(roomId, attachment)
-            ContentAttachmentData.Type.AUDIO -> createAudioEvent(roomId, attachment)
-            ContentAttachmentData.Type.FILE  -> createFileEvent(roomId, attachment)
+            ContentAttachmentData.Type.IMAGE         -> createImageEvent(roomId, attachment)
+            ContentAttachmentData.Type.VIDEO         -> createVideoEvent(roomId, attachment)
+            ContentAttachmentData.Type.AUDIO         -> createAudioEvent(roomId, attachment)
+            ContentAttachmentData.Type.VOICE_MESSAGE -> createAudioEvent(roomId, attachment)
```
Comment (bmarty) [inline matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/LocalEchoEventFactory.kt:211]: Maybe an opportunity to add a boolean in parameter to avoid doing this other [not nice check](https://github.com/vector-im/element-android/blob/main/matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/LocalEchoEventFactory.kt#L300), or create a brand new `createVoiceEvent` for clarity.

File: vector/src/main/java/im/vector/app/features/voice/AbstractVoiceRecorder.kt [hunk 3]
```diff
@@ -62,7 +62,7 @@ abstract class AbstractVoiceRecorder(
 
     override fun startRecord() {
         init()
-        outputFile = File(outputDirectory, "${UUID.randomUUID()}$filenameExt")
+        outputFile = File(outputDirectory, "${UUID.randomUUID()}.$filenameExt")
```
Comment (bmarty) [inline vector/src/main/java/im/vector/app/features/voice/AbstractVoiceRecorder.kt:65]: Ah I missed that in my previous review. Good catch!

**Review by bmarty — COMMENTED** [review]
Small remarks, else LGTM!

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/LocalEchoEventFactory.kt (hunk 2 above)
Comment (ouchadam) [reply matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/LocalEchoEventFactory.kt:211]: ahhh I missed that, will do :+1:

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/content/UploadContentWorker.kt (hunk 1 above)
Comment (ouchadam) [reply matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/content/UploadContentWorker.kt:283]: the file is uploaded but the associated timeline event is not sent (because we fail before `handleSuccess -> MultipleEventSendingDispatcherWorker`)

so I guess it's floating in limbo

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/LocalEchoEventFactory.kt (hunk 2 above)
Comment (ouchadam) [reply matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/LocalEchoEventFactory.kt]: https://github.com/vector-im/element-android/pull/4553/commits/31bd4fd2d04706355bf10b4541673682a15f4a73 added a boolean to avoid duplication

**Review by bmarty — APPROVED** [review]
Thanks!
