### PR TITLE
Fix the next button disable issue after visiting homeserver screen

### LINKED ISSUE #7928: Next button is disabled after going to change homeserver screen.
### Steps to reproduce

1. start app (no session)
2. Click on `create account` or `I already have an account`
3. choose an account type
4. Enter `username` and `password`. `Next` button can be clicked (do not click it)
5. Click on `Edit` to change the homeserver URL
6. Go back
7. `username` and `password` are still there, but `Next` button **cannot** be clicked

Editing the username AND the password make the button clickable again.

#### What did you expect?

`Next` button can be clicked when the form is filled.

#### What happened instead?

`Next` button is not clickable

### Your phone model

any

### Operating system version

any

### Application version and app store

1.5.18

### Homeserver

any

### Will you send logs?

No

### Are you willing to provide a PR?

No

### PR DESCRIPTION
**Pull request by ByeongsuPark**
## Type of change

- [ ] Feature
- [x] Bugfix
- [ ] Technical
- [ ] Other :

## Content

Fix the next button disabled issue after going to change homeserver screen.
The initial emission of flow is an empty string when coming back after visiting homeserver screen.
Because at that time(```onViewCreated```) the view's state is not restored yet.
Collecting flow after ```onViewStateRestored``` can be the one way to solve this problem.
So ```flowWithLifecycle()``` is added to collect flow after ```onViewStateRestored``` is called.

## Motivation and context

Fix #7928 

## Screenshots / GIFs

|Before|After|
|-|-|
|<video src="https://user-images.githubusercontent.com/39683194/217267533-0564ba09-f107-4a2c-8872-dcf361225de4.mp4" />|<video src="https://user-images.githubusercontent.com/39683194/217267763-681c30e0-8060-4c53-986c-dd3565c53025.mp4" />|
 -->

## Tests

Same steps as mentioned in the issue #7928

## Tested devices

- [x] Physical
- OS version(s): API 33
- [x] Emulator
- OS version(s): API 21

## Checklist

- [x] Changes has been tested on an Android device or Android emulator with API 21
- [ ] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#accessibility
- [x] Pull request is based on the develop branch
- [x] Pull request includes a new file under ./changelog.d. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#changelog
- [x] Pull request includes screenshots or videos if containing UI changes
- [x] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [=] You've made a self review of your PR
- [ ] If you have modified the screen flow, or added new screens to the application, you have updated the test [UiAllScreensSanityTest.allScreensTest()](https://github.com/vector-im/element-android/blob/main/vector/src/androidTest/java/im/vector/app/ui/UiAllScreensSanityTest.kt#L73)

### CODE REVIEW

File: vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthCombinedLoginFragment.kt [hunk 1]
```diff
@@ -103,7 +104,7 @@ class FtueAuthCombinedLoginFragment :
 
         combine(views.loginInput.editText().textChanges(), views.loginPasswordInput.editText().textChanges()) { account, password ->
             views.loginSubmit.isEnabled = account.isNotEmpty() && password.isNotEmpty()
-        }.launchIn(viewLifecycleOwner.lifecycleScope)
+        }.flowWithLifecycle(lifecycle).launchIn(viewLifecycleOwner.lifecycleScope)
```
Comment (bmarty) [inline vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthCombinedLoginFragment.kt:107]: TIL

**Review by bmarty — APPROVED** [review]
Perfect, thanks!
