### PR TITLE
Compress thumbnail: change Jpeg quality from 100 to 80 (#3396)

### LINKED ISSUE #3396: Thumbnail not being compressed
#### Describe the bug
When sharing a Video picked from Gallery the video is being compressed but the Thumbnail not.

### PR DESCRIPTION
**Pull request by bmarty**
Fix #3396 

### In the timeline

image

### Thumbnail size

Quality 100: 1_032_382 bytes
Quality 80: 134_085

File size is 7 times smaller.

### CODE REVIEW

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/content/ThumbnailExtractor.kt [hunk 1]
```diff
@@ -52,7 +52,7 @@ internal class ThumbnailExtractor @Inject constructor(
             mediaMetadataRetriever.setDataSource(context, attachment.queryUri)
             mediaMetadataRetriever.frameAtTime?.let { thumbnail ->
                 val outputStream = ByteArrayOutputStream()
-                thumbnail.compress(Bitmap.CompressFormat.JPEG, 100, outputStream)
+                thumbnail.compress(Bitmap.CompressFormat.JPEG, 80, outputStream)
```
Comment (ganfra) [inline matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/content/ThumbnailExtractor.kt:55]: Why 80 and not 79? (Joking)

**Review by ganfra — APPROVED** [review]
Wow, awesome, thanks!

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/content/ThumbnailExtractor.kt (hunk 1 above)
Comment (bmarty) [reply matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/content/ThumbnailExtractor.kt:55]: I hesitated for a long time...
