### PR TITLE
Fix crashes when opening Thread (#6463)

### LINKED ISSUE #6463: Crashes when opening Thread
Found several times in rageshake reports:

```
Thread: DefaultTimeline_Thread, Exception: java.lang.IllegalStateException: Cannot create asynchronous query while in a write transaction in /tmp/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsResults.cpp line 243
at io.realm.internal.OsResults.nativeStartListening(Native Method)
at io.realm.internal.OsResults.addListener(OsResults.java:2)
at org.matrix.android.sdk.internal.session.room.timeline.TimelineChunk.(TimelineChunk.kt:30)
at org.matrix.android.sdk.internal.session.room.timeline.TimelineChunk.createTimelineChunk(TimelineChunk.kt:14)
at org.matrix.android.sdk.internal.session.room.timeline.TimelineChunk$$ExternalSyntheticLambda1.onChange(R8$$SyntheticClass:27)
at io.realm.internal.OsObject.notifyChangeListeners(OsObject.java:10)
at io.realm.internal.OsSharedRealm.nativeBeginTransaction(Native Method)
at io.realm.internal.OsSharedRealm.beginTransaction(OsSharedRealm.java:3)
at io.realm.BaseRealm.beginTransaction(BaseRealm.java:2)
at io.realm.Realm.executeTransaction(Realm.java:7)
at org.matrix.android.sdk.internal.session.room.timeline.DefaultTimeline$openAround$2.invokeSuspend(DefaultTimeline.kt:59)
at org.matrix.android.sdk.internal.session.room.timeline.DefaultTimeline$openAround$2.invoke(Unknown Source:8)
at org.matrix.android.sdk.internal.session.room.timeline.DefaultTimeline$openAround$2.invoke(Unknown Source:4)
at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:1)
at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:9)
at org.matrix.android.sdk.internal.session.room.timeline.DefaultTimeline.access$openAround(DefaultTimeline.kt:1)
at org.matrix.android.sdk.internal.session.room.timeline.DefaultTimeline$start$2$1.invokeSuspend(DefaultTimeline.kt:29)
at org.matrix.android.sdk.internal.session.room.timeline.DefaultTimeline$start$2$1.invoke(Unknown Source:8)
at org.matrix.android.sdk.internal.session.room.timeline.DefaultTimeline$start$2$1.invoke(Unknown Source:2)
at org.matrix.android.sdk.internal.task.SemaphoreCoroutineSequencer.post$suspendImpl(CoroutineSequencer.kt:7)
at org.matrix.android.sdk.internal.session.room.timeline.DefaultTimeline$start$2.invokeSuspend(DefaultTimeline.kt:8)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
at android.os.Handler.handleCallback(Handler.java:883)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:237)
at android.os.HandlerThread.run(HandlerThread.java:67)
```

### PR DESCRIPTION
**Pull request by ganfra**
Fixes #6463

### CODE REVIEW

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/DefaultTimeline.kt [hunk 1]
```diff
@@ -185,6 +189,7 @@ internal class DefaultTimeline(
 
     override fun paginate(direction: Timeline.Direction, count: Int) {
         timelineScope.launch {
+            startTimelineJob?.join()
```
Comment (ouchadam) [inline matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/DefaultTimeline.kt:192]: are the `joins` the fix for the crash?

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/LoadTimelineStrategy.kt [hunk 2]
```diff
@@ -309,8 +310,8 @@ internal class LoadTimelineStrategy constructor(
     /**
      * Clear any existing thread chunk.
      */
-    private fun clearThreadChunkEntity(realm: Realm, rootThreadEventId: String) {
-        realm.executeTransaction {
+    private suspend fun clearThreadChunkEntity(realm: Realm, rootThreadEventId: String) {
+        awaitTransaction(realm.configuration) {
```
Comment (bmarty) [inline matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/LoadTimelineStrategy.kt:314]: I am wondering if it would be safer to use `realm.executeTransactionAwait` which has the advantage to perform a `refresh()` at the end of the transaction, rather than our home made `awaitTransaction`.

**Review by bmarty — APPROVED** [review]
LGTM

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/DefaultTimeline.kt (hunk 1 above)
Comment (ouchadam) [reply matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/DefaultTimeline.kt:192]: thanks for explaining :100:

**Review by ouchadam — APPROVED** [review]
:crossed_fingers:
