### PR TITLE
Ensure sync thread is started

### LINKED ISSUE #6782: Messages are not arriving
### Steps to reproduce

1. Be actively chatting with someone in a DM
2. Sometimes see typing notifications for a long time, sometimes not see anything to indicate that the other person is sending a message
3. See the timeline not updating
4. Swipe the app up to close it and then open it again (see green loading screen)
5. Open DM and see messages that were sent minutes ago

#### What did you expect?
I can have a live conversation

#### What happened instead?
I had to keep closing/opening the app to see my messages

### Your phone model

_No response_

### Operating system version

Android 11

### Application version and app store

1.4.31 playstore

### Homeserver

matrix.org

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

### PR DESCRIPTION
**Pull request by bmarty**
## Type of change

- [ ] Feature
- [x] Bugfix
- [ ] Technical
- [ ] Other :

## Content

- Fix #6782. This is this commit: 0b1b228. - **I am still investigating, because sometimes, the SyncThread stays in the  PAUSE state, which is not correct.**
- Improve SDK Debug API
- Log Thread before rageshake are sent.
- Rename thread names

## Motivation and context

- Fix #6782

Regression from #6710, release in Element and SDK v1.4.31 (2022-08-01)

## Screenshots / GIFs

NA

## Tests

- See the step to repro [here](https://github.com/vector-im/element-android/issues/6782#issuecomment-1219602578).

## Tested devices

- [ ] Physical
- [x] Emulator
- OS version(s):

## Checklist

- [ ] Changes has been tested on an Android device or Android emulator with API 21
- [ ] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#accessibility
- [ ] Pull request is based on the develop branch
- [ ] Pull request includes a new file under ./changelog.d. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#changelog
- [ ] Pull request includes screenshots or videos if containing UI changes
- [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [ ] You've made a self review of your PR
- [ ] If you have modified the screen flow, or added new screens to the application, you have updated the test [UiAllScreensSanityTest.allScreensTest()](https://github.com/vector-im/element-android/blob/main/vector/src/androidTest/java/im/vector/app/ui/UiAllScreensSanityTest.kt#L73)

### CODE REVIEW

File: vector/src/main/java/im/vector/app/core/di/ActiveSessionHolder.kt [hunk 1]
```diff
@@ -100,10 +101,16 @@ class ActiveSessionHolder @Inject constructor(
     }
 
     suspend fun getOrInitializeSession(startSync: Boolean): Session? {
-        return activeSessionReference.get() ?: sessionInitializer.tryInitialize(readCurrentSession = { activeSessionReference.get() }) { session ->
-            setActiveSession(session)
-            session.configureAndStart(applicationContext, startSyncing = startSync)
-        }
+        return activeSessionReference.get()
```
Comment (ouchadam) [inline vector/src/main/java/im/vector/app/core/di/ActiveSessionHolder.kt:104]: this might be clashing with https://github.com/vector-im/element-android/blob/develop/vector/src/main/java/im/vector/app/VectorApplication.kt#L176

I've always wondered if we should stop syncing when entering the foreground :thinking:

**Comment by opusforlife2** [comment]
> I am still investigating, because sometimes, the SyncThread stays in the PAUSE state, which is not correct.

I don't know about you guys, but I have occasionally encountered the Paused state on my device since forever. I don't remember if it started in a particular version. The solution has always been to remove the app from Recent Apps and then open it again, which causes the sync to resume.

**Comment by bmarty** [comment]
> > I am still investigating, because sometimes, the SyncThread stays in the PAUSE state, which is not correct.
> 
> I don't know about you guys, but I have occasionally encountered the Paused state on my device since forever. I don't remember if it started in a particular version. The solution has always been to remove the app from Recent Apps and then open it again, which causes the sync to resume.

Thanks for the feedback.

On my side I did not repro in the past days.
We will investigate this issue separately.

Moving this PR to ready to review.

File: vector/src/main/java/im/vector/app/core/di/ActiveSessionHolder.kt [hunk 2]
```diff
@@ -100,10 +101,16 @@ class ActiveSessionHolder @Inject constructor(
...
+                ?.also {
+                    if (startSync && !it.syncService().isSyncThreadAlive()) {
```
Comment (ouchadam) [inline vector/src/main/java/im/vector/app/core/di/ActiveSessionHolder.kt:106]: for my understanding of the error scenario

- app is not started
- receive a push
- session instance is created with `startSyncing = false` and cached
- next time the is launched the sync is not started because the session instance already exists and we only `configureAndStart` brand new instances


the fix is to always start the sync (if `startStart = true`) on our cached instances if they're not already syncing?

Comment (bmarty) [reply vector/src/main/java/im/vector/app/core/di/ActiveSessionHolder.kt:106]: Yes, that's it, sorry, the code is not crystal clear.

**Review by ouchadam — APPROVED** [review]

**Comment by bmarty** [comment]
`checkCantVerifyPopup[test(AVD) - 9] FAILED` for some other reason.

**Comment by opusforlife2** [comment]
> I don't know about you guys, but I have occasionally encountered the Paused state on my device since forever.

It's still a bit early to be sure, but I don't think I've encountered this after switching to ntfy for push notifications, from F-Droid's 60 second polling. It might have been specific to that particular config.

**Comment by opusforlife2** [comment]
Yep. Too early. Got a Paused even with ntfy. I have no STR, sadly, otherwise I would have created a new issue.
