### PR TITLE
Some fixies

### LINKED ISSUE #2509: Encrypted reactions are not managed
**Describe the bug**
Some emoji reactions in the timeline don't get interpreted properly. Instead they show up as `{ "type": m.reaction }`

**To Reproduce**
1. Send an emoji reaction in an encrypted room from FluffyChat.
2. Check the room from a different FluffyChat device: The reaction is rendered correctly.
3. Check the room from Element Web: The reaction is rendered correctly.
4. Check the room from Element Android.

**Expected behavior**
The reaction is rendered correctly.

**Screenshots**
Screenshot_20201209-094024_Bliss_Launcher

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S7 Edge
 - OS: /e/ 0.12 (based on Android 8.1.0)

**Additional context**
 - Element Android 1.0.11 from F-Droid
 - FluffyChat 0.23.0 from F-Droid
 - Homeserver: matrix.org

It's hard to tell whether the underlying bug is on the FluffyChat or Element Android end. The former seems likely but since Element Web renders the reaction correctly, I am not entirely sure.

The corresponding FluffyChat issue is here: https://gitlab.com/ChristianPauly/fluffychat/-/issues/178

### LINKED ISSUE #3017: If there are only emojis and whitespace in a t.text, make them larger

### PR DESCRIPTION
**Pull request by bmarty**
Fixes #3017 
Fixes #2509 

Improve UX for the enter passphrase bottom sheet, from

image

to

image

and many other small fixes

### CODE REVIEW

File: vector/src/main/java/im/vector/app/core/utils/Emoji.kt [hunk 1]
```diff
@@ -82,6 +85,9 @@ fun isSingleEmoji(string: String): Boolean {
  * @return true if the body contains only emojis
  */
 fun containsOnlyEmojis(str: String?): Boolean {
+    // Now rely on vanniktech library
+    return EmojiUtils.isOnlyEmojis(str)
+    /*
```
Comment (ganfra) [inline vector/src/main/java/im/vector/app/core/utils/Emoji.kt:90]: Commenting old code is really necessary?

**Review by ganfra — APPROVED** [review]
One small remark, otherwise LGTM (not tested)

File: vector/src/main/java/im/vector/app/core/utils/Emoji.kt (hunk 1 above)
Comment (bmarty) [reply vector/src/main/java/im/vector/app/core/utils/Emoji.kt:90]: I do the clean up
