### PR TITLE
Fix crash when opening an unknown room

### LINKED ISSUE #5611: Crash - TimelineViewModel.<init> NullPointerException
```
java.lang.RuntimeException: 
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:610)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:967)
Caused by: java.lang.reflect.InvocationTargetException: 
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:600)
Caused by: java.lang.reflect.InvocationTargetException: 
  at java.lang.reflect.Method.invoke (Native Method)
  at com.airbnb.mvrx.MavericksFactory.create (MavericksFactory.kt:12)
  at com.airbnb.mvrx.MavericksViewModelProvider.get$default (MavericksViewModelProvider.kt:34)
  at im.vector.app.features.home.room.detail.TimelineFragment$special$$inlined$fragmentViewModel$default$1.invoke (MavericksExtensions.kt:10)
  at im.vector.app.features.home.room.detail.TimelineFragment$special$$inlined$fragmentViewModel$default$1.invoke (MavericksExtensions.kt:1)
  at com.airbnb.mvrx.DefaultViewModelDelegateFactory$createLazyViewModel$1.invoke (ViewModelDelegateProvider.kt:2)
  at com.airbnb.mvrx.DefaultViewModelDelegateFactory$createLazyViewModel$1.invoke (ViewModelDelegateProvider.kt:1)
  at com.airbnb.mvrx.lifecycleAwareLazy.getValue (lifecycleAwareLazy.kt:5)
  at com.airbnb.mvrx.lifecycleAwareLazy$initializeWhenCreated$1.onCreate (lifecycleAwareLazy.kt:1)
  at androidx.lifecycle.FullLifecycleObserverAdapter.onStateChanged (FullLifecycleObserverAdapter.java:8)
  at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent (LifecycleRegistry.java:3)
  at androidx.lifecycle.LifecycleRegistry.sync (LifecycleRegistry.java:45)
  at androidx.lifecycle.LifecycleRegistry.moveToState (LifecycleRegistry.java:5)
  at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent (LifecycleRegistry.java:2)
  at androidx.fragment.app.Fragment.performCreate (Fragment.java:9)
  at androidx.fragment.app.FragmentStateManager.create (FragmentStateManager.java:5)
  at androidx.fragment.app.FragmentStateManager.moveToExpectedState (FragmentStateManager.java:28)
  at androidx.fragment.app.FragmentManager.executeOpsTogether (FragmentManager.java:122)
  at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute (FragmentManager.java:9)
  at androidx.fragment.app.FragmentManager.execPendingActions (FragmentManager.java:14)
  at androidx.fragment.app.FragmentManager.dispatchStateChange (FragmentManager.java:10)
  at androidx.fragment.app.FragmentActivity.onStart (FragmentActivity.java:12)
  at androidx.appcompat.app.AppCompatActivity.onStart (AppCompatActivity.java:1)
  at android.app.Instrumentation.callActivityOnStart (Instrumentation.java:1436)
  at android.app.Activity.performStart (Activity.java:8140)
  at android.app.ActivityThread.handleStartActivity (ActivityThread.java:3505)
  at android.app.servertransaction.TransactionExecutor.performLifecycleSequence (TransactionExecutor.java:221)
  at android.app.servertransaction.TransactionExecutor.cycleToPath (TransactionExecutor.java:201)
  at android.app.servertransaction.TransactionExecutor.executeLifecycleState (TransactionExecutor.java:173)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:97)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2104)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:236)
  at android.app.ActivityThread.main (ActivityThread.java:7861)
Caused by: java.lang.NullPointerException: 
  at im.vector.app.features.home.room.detail.TimelineViewModel.<init> (TimelineViewModel.kt:18)
  at im.vector.app.DaggerVectorApplication_HiltComponents_SingletonC$MavericksViewModelCImpl$SwitchingProvider$86.create (DaggerVectorApplication_HiltComponents_SingletonC.java:14)
  at im.vector.app.core.di.HiltMavericksViewModelFactory.create (HiltMavericksViewModelFactory.kt:6)
  at im.vector.app.features.home.room.detail.TimelineViewModel$Companion.create (Unknown Source:12)
  at im.vector.app.features.home.room.detail.TimelineViewModel$Companion.create (TimelineViewModel.kt:1)
```

| Occurrences (30 days) | Affected users |
| --- | --- | 
| 634 | 415 |

https://play.google.com/console/u/0/developers/{redacted}/app/{redacted}/vitals/crashes/58bec65f/details?installedFrom=PLAY_STORE&days=30

`NullPointerException` thrown when force unwrapping the `Room` returns null https://github.com/vector-im/element-android/blob/develop/vector/src/main/java/im/vector/app/features/home/room/detail/TimelineViewModel.kt#L149

### PR DESCRIPTION
**Pull request by bmarty**
## Type of change

- [ ] Feature
- [x] Bugfix
- [ ] Technical
- [ ] Other :

## Content

Fix a crash when user opens a Timeline of a unknown room. This PR also contains some code cleanup, can be reviewed commit per commit if necessary.

This PR does not fix the root cause, which is quite unclear for now. This can be related to thread / space / etc. But it fixes the crash, and display a full screen error to the user.

If we got rageshake with the screen content in developer mode, we may have more info on the room which is tried to be open.

Note: I have seen #6543, but I think this is compatible with this change. I would prefer to first merge this PR, and then handle #6543.

## Motivation and context

Less crash.
fixes #5611 

## Screenshots / GIFs

|Before|After|
|-|-|
|**crash**|RoomNotFound|

In developer mode, more info will be displayed:

image

## Tests

- Update the line https://github.com/vector-im/element-android/blob/1ced47fbd2cfa6515cf0b52b40f0a304d9487fb9/vector/src/main/java/im/vector/app/features/home/room/detail/TimelineViewModel.kt#L152 for instance with `session.getRoom(initialState.roomId + "_you_will_not_find_me")`
- Try to open any room

## Tested devices

- [ ] Physical
- [x] Emulator
- OS version(s):

## Checklist

- [ ] Changes has been tested on an Android device or Android emulator with API 21
- [ ] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#accessibility
- [ ] Pull request is based on the develop branch
- [ ] Pull request includes a new file under ./changelog.d. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#changelog
- [ ] Pull request includes screenshots or videos if containing UI changes
- [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [ ] You've made a self review of your PR
- [ ] If you have modified the screen flow, or added new screens to the application, you have updated the test [UiAllScreensSanityTest.allScreensTest()](https://github.com/vector-im/element-android/blob/main/vector/src/androidTest/java/im/vector/app/ui/UiAllScreensSanityTest.kt#L73)

### CODE REVIEW

File: vector/src/main/java/im/vector/app/features/home/room/detail/TimelineViewModel.kt [hunk 1]
```diff
@@ -143,16 +145,16 @@ class TimelineViewModel @AssistedInject constructor(
         private val cryptoConfig: CryptoConfig,
         buildMeta: BuildMeta,
         timelineFactory: TimelineFactory,
-        spaceStateHandler: SpaceStateHandler,
+        private val spaceStateHandler: SpaceStateHandler,
 ) : VectorViewModel<RoomDetailViewState, RoomDetailAction, RoomDetailViewEvents>(initialState),
         Timeline.Listener, ChatEffectManager.Delegate, CallProtocolsChecker.Listener, LocationSharingServiceConnection.Callback {
 
-    private val room = session.getRoom(initialState.roomId)!!
+    private val room = session.getRoom(initialState.roomId)
```
Comment (bmarty) [inline vector/src/main/java/im/vector/app/features/home/room/detail/TimelineViewModel.kt:152]: `room` can be null now.

File: vector/src/main/java/im/vector/app/features/home/room/detail/TimelineViewModel.kt [hunk 2]
```diff
@@ -266,6 +278,7 @@ class TimelineViewModel @AssistedInject constructor(
     }
 
     private fun prepareForEncryption() {
+        if (room == null) return
```
Comment (bmarty) [inline vector/src/main/java/im/vector/app/features/home/room/detail/TimelineViewModel.kt:281]: I could have used `?` like `room?.` and `timeline?.` everywhere, but I think this is cleaner like this. When the room is null, there is nothing we can really do with this ViewModel.

File: vector/src/main/java/im/vector/app/features/home/room/detail/error/RoomNotFound.kt [hunk 3]
```diff
@@ -0,0 +1,19 @@
...
+ * Unless required by applicable law or agreed to in writing, software
+ * distributed under the License is distributed on an "AS IS" BASIS,
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+package im.vector.app.features.home.room.detail.error
+
+class RoomNotFound: Throwable()
```
Comment (ElementBot) [inline vector/src/main/java/im/vector/app/features/home/room/detail/error/RoomNotFound.kt:19]: - :no_entry_sign: Missing spacing before ":"

**Review by jmartinesp — APPROVED** [review]
LGTM!

File: vector/src/main/java/im/vector/app/features/home/room/detail/TimelineViewModel.kt [hunk 4]
```diff
@@ -538,11 +553,13 @@ class TimelineViewModel @AssistedInject constructor(
     }
 
     private fun handleJumpToReadReceipt(action: RoomDetailAction.JumpToReadReceipt) {
+        if (room == null) return
```
[the remark this answers is not in the document]
Comment (bmarty) [reply vector/src/main/java/im/vector/app/features/home/room/detail/TimelineViewModel.kt:556]: Yes, I have use the same pattern (nearly) everywhere for code consistency, but I admit that sometimes it's a bit too much.
Also doing like this has the advantage to not impact the `git blame`.
