### PR TITLE
[Location tracker] - Fix some location tracking issues (PSF-1000)

### LINKED ISSUE #5913: [Location tracker] - Fix some location tracking issues
#### What would you like to do?
Issues to fix : 
- At start, use the latest known location of all available providers to avoid inconsistencies
- Prioritize locations received from the providers in the following order: “Fused”, “GPS”, other providers
- Debounce the location updates to avoid sending too many events
- Avoid calling callback for provider not available when only one of them is disabled (should be called only when all providers are disabled)

#### Why would you like to do it?
Using the last known location from all providers leads to notification of multiple locations with different accuracy and uncorrect location tracking.

#### How would you like to achieve it?
Select the best last known location to notify callbacks.

### Have you considered any alternatives?

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mnaturel**
## Type of change

- [ ] Feature
- [ ] Bugfix
- [ ] Technical
- [x] Other : Enhancement

## Content

- Use the latest known location among the ones from all providers when starting tracking.
- Adding minimal period of update to notify callback of location change to avoid too many notifications.
- Prioritize locations received from the providers in the following order: “Fused”, “GPS”, other providers
- Avoid calling callback for provider not available when only one of them is disabled (should be called only when all providers are disabled)

## Motivation and context

Closes #5913 

## Tests

- Check location sharing is enabled in the settings
- Go to a room
- Start to share location
- Check the current location is good on the map
- Check the logs of the LocationTracker

## Tested devices

- [x] Physical
- [x] Emulator
- OS version(s): Android 11

## Checklist

- [ ] Changes has been tested on an Android device or Android emulator with API 21
- [ ] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#accessibility
- [x] Pull request is based on the develop branch
- [x] Pull request includes a new file under ./changelog.d. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#changelog
- [ ] Pull request includes screenshots or videos if containing UI changes
- [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [x] You've made a self review of your PR
- [ ] If you have modified the screen flow, or added new screens to the application, you have updated the test [UiAllScreensSanityTest.allScreensTest()](https://github.com/vector-im/element-android/blob/main/vector/src/androidTest/java/im/vector/app/ui/UiAllScreensSanityTest.kt#L73)

### CODE REVIEW

File: vector/src/main/java/im/vector/app/features/location/LocationTracker.kt [hunk 1]
```diff
@@ -127,6 +128,19 @@ class LocationTracker @Inject constructor(
                 }
             }
         }
+
+        val nowMillis = System.currentTimeMillis()
+        val elapsedMillis = nowMillis - (lastLocationUpdateMillis ?: 0)
+        if (elapsedMillis >= MIN_TIME_TO_UPDATE_LOCATION_MILLIS) {
+            lastLocationUpdateMillis = nowMillis
+            notifyLocation(location)
```
Comment (bmarty) [inline vector/src/main/java/im/vector/app/features/location/LocationTracker.kt:136]: Nit You could use our handy `FirstThrottler`.

File: vector/src/main/java/im/vector/app/features/location/LocationTracker.kt [hunk 2]
```diff
@@ -55,34 +57,36 @@ class LocationTracker @Inject constructor(
...
+                        locationManager.requestLocationUpdates(
+                                provider,
+                                MIN_TIME_TO_UPDATE_LOCATION_MILLIS,
+                                MIN_DISTANCE_TO_UPDATE_LOCATION_METERS,
+                                this
+                        )
+
+                        locationManager.getLastKnownLocation(provider)
+                    }
+                    .maxByOrNull { location -> location.time }
```
Comment (bmarty) [inline vector/src/main/java/im/vector/app/features/location/LocationTracker.kt:80]: 👍

**Review by bmarty — COMMENTED** [review]
Just a small remark

File: vector/src/main/java/im/vector/app/features/location/LocationTracker.kt (hunk 1 above)
Comment (mnaturel) [reply vector/src/main/java/im/vector/app/features/location/LocationTracker.kt:136]: Thanks for the info. In fact, I realized a debouce operation is more suitable here. I will try to rework on it.

File: vector/src/main/java/im/vector/app/features/location/LocationTracker.kt [hunk 3]
```diff
@@ -36,62 +42,90 @@ class LocationTracker @Inject constructor(
...
     @RequiresPermission(anyOf = [Manifest.permission.ACCESS_COARSE_LOCATION, Manifest.permission.ACCESS_FINE_LOCATION])
     fun start() {
-        Timber.d("## LocationTracker. start()")
-        hasGpsProviderLiveLocation = false
+        Timber.d("start()")
 
         if (locationManager == null) {
-            callbacks.forEach { it.onLocationProviderIsNotAvailable() }
-            Timber.v("## LocationTracker. LocationManager is not available")
+            callbacks.forEach { it.onNoLocationProviderAvailable() }
```
Comment (ganfra) [inline vector/src/main/java/im/vector/app/features/location/LocationTracker.kt:74]: Maybe try catch the dispatching

File: vector/src/main/java/im/vector/app/features/location/LocationTracker.kt [hunk 4]
```diff
@@ -36,62 +42,90 @@ class LocationTracker @Inject constructor(
...
-                // Take GPS first
-                ?.sortedByDescending { if (it == LocationManager.GPS_PROVIDER) 1 else 0 }
-                ?.forEach { provider ->
-                    Timber.d("## LocationTracker. track location using $provider")
+        val providers = locationManager.allProviders
 
-                    // Send last known location without waiting location updates
-                    locationManager.getLastKnownLocation(provider)?.let { lastKnownLocation ->
+        if (providers.isEmpty()) {
+            callbacks.forEach { it.onNoLocationProviderAvailable() }
```
Comment (ganfra) [inline vector/src/main/java/im/vector/app/features/location/LocationTracker.kt:82]: same

File: vector/src/main/java/im/vector/app/features/location/LocationTracker.kt [hunk 5]
```diff
@@ -36,62 +42,90 @@ class LocationTracker @Inject constructor(
...
+            Timber.v("There is no location provider available")
+        } else {
+            // Take GPS first
+            providers.sortedByDescending { getProviderPriority(it) }
```
Comment (ganfra) [inline vector/src/main/java/im/vector/app/features/location/LocationTracker.kt:86]: use method reference?

File: vector/src/main/java/im/vector/app/features/location/LocationTracker.kt [hunk 6]
```diff
@@ -110,41 +144,67 @@ class LocationTracker @Inject constructor(
...
+        if (BuildConfig.LOW_PRIVACY_LOG_ENABLE) {
+            Timber.d("notify location: $location")
+        } else {
+            Timber.d("notify location: ${location.provider}")
         }
+
         val locationData = location.toLocationData()
         lastLocation = locationData
-        callbacks.forEach { it.onLocationUpdate(locationData) }
+        callbacks.forEach { it.onLocationUpdate(location.toLocationData()) }
```
Comment (ganfra) [inline vector/src/main/java/im/vector/app/features/location/LocationTracker.kt:193]: Same, try/catch?

**Review by ganfra — COMMENTED** [review]
Just small remarks otherwise LGTM and thanks for the tests!

File: vector/src/main/java/im/vector/app/features/location/LocationTracker.kt (hunk 4 above)
Comment (mnaturel) [reply vector/src/main/java/im/vector/app/features/location/LocationTracker.kt]: Done, see [e21b696](https://github.com/vector-im/element-android/pull/5923/commits/e21b6963c0ea53ff4a4760dcf06dc798049b3939)

File: vector/src/main/java/im/vector/app/features/location/LocationTracker.kt (hunk 6 above)
Comment (mnaturel) [reply vector/src/main/java/im/vector/app/features/location/LocationTracker.kt]: Done, see [e21b696](https://github.com/vector-im/element-android/pull/5923/commits/e21b6963c0ea53ff4a4760dcf06dc798049b3939)

File: vector/src/main/java/im/vector/app/features/location/LocationTracker.kt (hunk 5 above)
Comment (mnaturel) [reply vector/src/main/java/im/vector/app/features/location/LocationTracker.kt]: Done, see [af0ae61](https://github.com/vector-im/element-android/pull/5923/commits/af0ae6123b9a7a9a1249cd9a1c672db9268fef0f). Should we prioritize this syntax as a general rule?

**Comment by mnaturel** [comment]
I have fixed a regression I introduced concerning the stopping of the location tracking: [0e11e4b](https://github.com/vector-im/element-android/pull/5923/commits/0e11e4b2a6d25c02b21b8ec35adacc506657cec4)

File: vector/src/main/java/im/vector/app/features/location/LocationTracker.kt (hunk 5 above)
Comment (ganfra) [reply vector/src/main/java/im/vector/app/features/location/LocationTracker.kt]: We might yes!

**Review by ganfra — APPROVED** [review]
LGTM!

File: vector/src/test/java/im/vector/app/features/location/LocationTrackerTest.kt [hunk 7]
```diff
@@ -0,0 +1,302 @@
...
+
+    private val locationTracker = LocationTracker(fakeContext.instance)
+
+    @Before
+    fun setUp() {
+        fakeLocationManager.givenRemoveUpdates(locationTracker)
+    }
+
+    @After
+    fun tearDown() {
```
Comment (Claire1817) [inline vector/src/test/java/im/vector/app/features/location/LocationTrackerTest.kt:76]: Maybe you should unmockk the objects after each tests ? 
Location or LocationTracker for exemple ?

Comment (mnaturel) [reply vector/src/test/java/im/vector/app/features/location/LocationTrackerTest.kt:76]: > Maybe you should unmockk the objects after each tests ? Location or LocationTracker for exemple ?

I am not sure to correctly understand your suggestion. Do you suggest to create a new `LocationTracker` object for each test? I didn't think about it but if so, I agree so that we can keep each test isolated from each other.

File: vector/src/main/java/im/vector/app/features/location/LocationTracker.kt [hunk 8]
```diff
@@ -117,34 +151,84 @@ class LocationTracker @Inject constructor(
...
+        locationManager?.allProviders
+                ?.takeIf { it.isEmpty() }
+                ?.let {
+                    Timber.e("all providers have been disabled")
+                    onNoLocationProviderAvailable()
+                }
+    }
+
+    private fun onNoLocationProviderAvailable() {
+        callbacks.forEach {
```
Comment (bmarty) [inline vector/src/main/java/im/vector/app/features/location/LocationTracker.kt:215]: Is there a risk of `ConcurrentModificationException` here?

File: vector/src/main/java/im/vector/app/features/location/LocationTracker.kt [hunk 9]
```diff
@@ -117,34 +151,84 @@ class LocationTracker @Inject constructor(
...
+            try {
+                it.onNoLocationProviderAvailable()
+            } catch (error: Exception) {
+                Timber.e(error, "error in onNoLocationProviderAvailable callback $it")
+            }
+        }
+    }
+
+    private fun onLocationUpdate(locationData: LocationData) {
+        callbacks.forEach {
```
Comment (bmarty) [inline vector/src/main/java/im/vector/app/features/location/LocationTracker.kt:225]: Same remark.

**Review by bmarty — COMMENTED** [review]
Just one latest remark.

File: vector/src/main/java/im/vector/app/features/location/LocationTracker.kt (hunk 8 above)
Comment (mnaturel) [reply vector/src/main/java/im/vector/app/features/location/LocationTracker.kt:215]: Hum I guess there is... I will try to add a test to see if it passes.

Comment (mnaturel) [reply vector/src/main/java/im/vector/app/features/location/LocationTracker.kt:220]: Updated here: [1ee852d](https://github.com/vector-im/element-android/pull/5923/commits/1ee852dbf4e223ebab5a7de775ba4e2c14de3b6c)

File: vector/src/test/java/im/vector/app/features/location/LocationTrackerTest.kt (hunk 7 above)
Comment (mnaturel) [reply vector/src/test/java/im/vector/app/features/location/LocationTrackerTest.kt:72]: I have done an update here: [abe7fe9](https://github.com/vector-im/element-android/pull/5923/commits/abe7fe917615b588a1e932ce6a30373cda9312c3)

**Review by bmarty — APPROVED** [review]
(Did not perform a full review, but my remarks have been handled)

**Review by Claire1817 — APPROVED** [review]
