### PR TITLE
Crash / Attachment viewer: Cannot draw a recycled Bitmap

### LINKED ISSUE #2034: Crash / Attachment viewer: Cannot draw a recycled Bitmap
Crash occurs when you open the attachment viewer on a room with lots of (not small) images/video/gifs.
Scroll fast to the left several time then scroll back to the right (and so on)

### PR DESCRIPTION
**Pull request by BillCarsonFr**
Fixes  #2034

Some cleaning. Can't reproduce crash after those changes

### CODE REVIEW

File: attachment-viewer/src/main/java/im/vector/lib/attachmentviewer/VideoViewHolder.kt [hunk 1]
```diff
@@ -118,8 +119,13 @@ class VideoViewHolder constructor(itemView: View) :
                         eventListener?.get()?.onEvent(AttachmentEvents.VideoEvent(isPlaying, progress, duration))
                     }
         }
+        try {
+            videoView.setVideoPath(mVideoPath)
+        } catch (failure: Throwable) {
+            // Couldn't open
+            Log.v(VideoViewHolder::class.java.name, "Failed to start video ${failure.message}")
```
Comment (bmarty) [inline attachment-viewer/src/main/java/im/vector/lib/attachmentviewer/VideoViewHolder.kt:126]: the `failure.message` could leak the filename, please remove for privacy reason

**Review by bmarty — COMMENTED** [review]
LGTM, just one remark
