### PR TITLE
warn on cross signing reset

### LINKED ISSUE #6702: Parity with web | Add Warning shield when a user previously verified rotated his cross signing keys
Web remembers when a user that was previously verified rotates his keys.
As a consequence, in such scenario the shield on the user (or room when applicable), will revert to black shield on android but will be red on web.

Step to reproduce:
- Sign in alice on android 
- Sign in bob on web
- Start and complete Verification on bob session for alice

- On web (bob) go to settings and reset cross signing keys

Expected: 
On android bob should have a Red shield (and option to re-start verification)

Actual:
On android bob has a black shield

### PR DESCRIPTION
**Pull request by BillCarsonFr**
## Type of change

- [x] Bugfix

## Content

Fixes #6702 
Parity with web. Show a warning when a previously verified user rotated his cross signing keys.

We now remember locally when a user was verified once.
When/If that user rotate his cross signing keys he will be marked with a red shield instead of black shield.

- Requires a database migration to remember that the user was verfied once
- Refactoring: The shield state of users was using the same enum as rooms `RoomEncryptionTrustLevel`, now I introduced a new enum for users `UserVerificationLevel` that is used in UI to decorate avatars.

## Tests

- Step 1
- Step 2
- Step ...

## Tested devices

- [ ] Physical
- [x] Emulator
- OS version(s):

## Checklist

- [x] Changes has been tested on an Android device or Android emulator with API 21
- [x] UI change has been tested on both light and dark themes
- [x] Accessibility has been taken into account. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#accessibility
- [x] Pull request is based on the develop branch
- [x] Pull request includes a new file under ./changelog.d. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#changelog
- [ ] Pull request includes screenshots or videos if containing UI changes
- [x] You've made a self review of your PR
- [ ] If you have modified the screen flow, or added new screens to the application, you have updated the test [UiAllScreensSanityTest.allScreensTest()](https://github.com/vector-im/element-android/blob/main/vector/src/androidTest/java/im/vector/app/ui/UiAllScreensSanityTest.kt#L73)

### CODE REVIEW

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/crosssigning/UpdateTrustWorker.kt [hunk 1]
```diff
@@ -161,6 +161,7 @@ internal class UpdateTrustWorker(context: Context, params: WorkerParameters, ses
             // i have all the new trusts, update DB
             trusts.forEach {
                 val verified = it.value?.isVerified() == true
+                Timber.v("[$myUserId] ## CrossSigning - Updating user trust: ${it.key} to ${verified}")
```
Comment (ElementBot) [inline matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/crosssigning/UpdateTrustWorker.kt:164]: - :no_entry_sign: Redundant curly braces

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/crosssigning/DefaultCrossSigningService.kt [hunk 2]
```diff
@@ -60,7 +60,7 @@ import javax.inject.Inject
 
 @SessionScope
 internal class DefaultCrossSigningService @Inject constructor(
-        @UserId private val userId: String,
+        @UserId private val myUserId: String,
```
Comment (ouchadam) [inline matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/crosssigning/DefaultCrossSigningService.kt:63]: I'm wondering if we should create a dedicated type for `MyUserId/SelfId`, do you think it would help reduce potential errors?

File: changelog.d/6702.bugfix [hunk 3]
```diff
@@ -0,0 +1 @@
+Add Warning shield when a user previously verified rotated his cross signing keys
```
Comment (bmarty) [inline changelog.d/6702.bugfix:1]:
```suggestion
Add Warning shield when a user previously verified rotated their cross signing keys
```

**Review by bmarty — APPROVED** [review]
LGTM, just a small remark on the changelog, and the tests are not compiling.

File: vector/src/test/java/im/vector/app/features/RoomMemberListControllerTest.kt [hunk 4]
```diff
@@ -0,0 +1,132 @@
...
+import org.junit.Rule
+import org.junit.Test
+import org.junit.runner.RunWith
+import org.matrix.android.sdk.api.session.crypto.model.UserVerificationLevel
+import org.matrix.android.sdk.api.session.room.model.Membership
+import org.matrix.android.sdk.api.session.room.model.RoomMemberSummary
+import org.matrix.android.sdk.api.session.room.model.RoomSummary
+import org.robolectric.RobolectricTestRunner
+
+@RunWith(RobolectricTestRunner::class)
```
Comment (ouchadam) [inline vector/src/test/java/im/vector/app/features/RoomMemberListControllerTest.kt:38]: do we need to introduce `Robolectric`?  if we need real android classes the test might be better suited to the `androidTest` sourceset, that way we can keep the unit tests quick

Comment (BillCarsonFr) [reply vector/src/test/java/im/vector/app/features/RoomMemberListControllerTest.kt:38]: Well I just took that from the epoxy tests samples. No idea if we can do another way, just trying to reach my test coverage threshold
