### PR TITLE
#5005: Add save media icon in gallery

### LINKED ISSUE #5005: Unable to dowload images???
### Steps to reproduce

1. Click on an image
2. Try holding your finger on it, nothing happens
3. Try hitting share, no option to save
4. Cant download???

#### What did you expect?
The ability to download images
#### What happened instead?
This functionality does not seem to exist

### Your phone model

Pixel 4a5g

### Operating system version

Android 11 LineageOS 18.1

### Application version and app store

Element Version 1.3.14 Olm Version 3.2.10

### Homeserver

yiff.social

### Will you send logs?

No

### PR DESCRIPTION
**Pull request by mnaturel**
## Type of change

- [x] Feature
- [ ] Bugfix
- [ ] Technical
- [ ] Other :

## Content

A download icon has been added into the media gallery screen to be able to download the media (not only images) from that screen. Message actions "share", "save" and "remove" have been re-order in the message actions menu which appears on long press on message. 
Introducing UseCase pattern to better encapsulate code and to be able to unit test (see interface `VectorBaseInOutUseCase`).

## Motivation and context

Closes #5005.

## Tests

- Go to a room where there are shared media (e.g. image, video)
- Long press on a shared media
- Check the order of actions in the appearing menu is correct (see [this comment](https://github.com/vector-im/element-android/issues/5005#issuecomment-1020463094))
- Cancel the menu
- Click on a shared media
- Check the media is displayed in the gallery
- Check download icon is shown along share icon
- Click on the download icon
- Check if write permissions is asked (only for devices with version < Android 10)
- Check a notification appears saying the media has been downloaded

## Tested devices

- [ ] Physical
- [x] Emulator
- OS version(s): Android 9 and 11

## Checklist

- [ ] Changes has been tested on an Android device or Android emulator with API 21
- [x] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#accessibility
- [x] Pull request is based on the develop branch
- [x] Pull request includes a new file under ./changelog.d. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#changelog
- [x] Pull request includes screenshots or videos if containing UI changes
- [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [x] You've made a self review of your PR
- [ ] If you have modified the screen flow, or added new screens to the application, you have updated the test [UiAllScreensSanityTest.allScreensTest()](https://github.com/vector-im/element-android/blob/main/vector/src/androidTest/java/im/vector/app/ui/UiAllScreensSanityTest.kt#L73)

### CODE REVIEW

File: vector/src/main/java/im/vector/app/features/media/VectorAttachmentViewerViewModel.kt [hunk 1]
```diff
@@ -0,0 +1,74 @@
...
+            is VectorAttachmentViewerAction.DownloadMedia -> handleDownloadAction(action)
+        }
+    }
+
+    /* ==========================================================================================
+     * Private methods
+     * ========================================================================================== */
+
+    private fun handleDownloadAction(action: VectorAttachmentViewerAction.DownloadMedia) {
+        viewModelScope.launch {
```
Comment (mnaturel) [inline vector/src/main/java/im/vector/app/features/media/VectorAttachmentViewerViewModel.kt:68]: Should use `session.coroutineScope` to avoid binding the download to the lifecycle of the `ViewModel`.

**Comment by mnaturel** [comment]
Hi @amshakal , I have added screenshots of the requested modifications. Please, can you check if it is correct?

File: vector/src/main/java/im/vector/app/features/media/VectorAttachmentViewerViewModel.kt [hunk 2]
```diff
@@ -0,0 +1,78 @@
...
+import kotlinx.coroutines.launch
+import org.matrix.android.sdk.api.session.Session
+
+class VectorAttachmentViewerViewModel @AssistedInject constructor(
+        @Assisted initialState: VectorDummyViewState,
+        private val session: Session,
+        private val downloadMediaUseCase: DownloadMediaUseCase
+) : VectorViewModel<VectorDummyViewState, VectorAttachmentViewerAction, VectorAttachmentViewerViewEvents>(initialState) {
+
+    /* ==========================================================================================
```
Comment (ouchadam) [inline vector/src/main/java/im/vector/app/features/media/VectorAttachmentViewerViewModel.kt:39]: are these headers necessary?  I would lean into them being a symptom of classes becoming too large, it also means method ordering becomes fractured rather than by usage

```kotlin
fun foo() {
  bar()
}

private fun bar() {}

fun baz() {
  fuzz()
}

private fun fuzz() {}
```

I'm not aware of project conventions for either though :sweat_smile:

File: vector/src/main/java/im/vector/app/features/media/domain/usecase/DownloadMediaUseCase.kt [hunk 3]
```diff
@@ -0,0 +1,52 @@
...
+        @ApplicationContext private val appContext: Context,
+        private val notificationUtils: NotificationUtils
+) : VectorBaseInOutUseCase<File, Unit> {
+
+    /* ==========================================================================================
+     * Public API
+     * ========================================================================================== */
+
+    // TODO declare Dispatcher via an Interface provider to be able to unit tests
+    override suspend fun execute(input: File): Result<Unit> = withContext(Dispatchers.IO) {
```
Comment (ouchadam) [inline vector/src/main/java/im/vector/app/features/media/domain/usecase/DownloadMediaUseCase.kt:41]: we already have one! :raised_hands:  [test matrix dispatchers](https://github.com/vector-im/element-android/blob/develop/vector/src/test/java/im/vector/app/test/TestCoroutineDispatchers.kt) or we can use the abstraction directly passing `unconfined` https://github.com/vector-im/element-android/blob/develop/vector/src/main/java/im/vector/app/core/dispatchers/CoroutineDispatchers.kt

File: vector/src/main/java/im/vector/app/features/media/domain/usecase/DownloadMediaUseCase.kt [hunk 4]
```diff
@@ -0,0 +1,52 @@
...
+import im.vector.app.core.intent.getMimeTypeFromUri
+import im.vector.app.core.usecase.VectorBaseInOutUseCase
+import im.vector.app.core.utils.saveMedia
+import im.vector.app.features.notifications.NotificationUtils
+import kotlinx.coroutines.Dispatchers
+import kotlinx.coroutines.withContext
+import java.io.File
+import javax.inject.Inject
+
+class DownloadMediaUseCase @Inject constructor(
```
Comment (ouchadam) [inline vector/src/main/java/im/vector/app/features/media/domain/usecase/DownloadMediaUseCase.kt:31]: :100:

File: vector/src/main/java/im/vector/app/core/usecase/VectorBaseInOutUseCase.kt [hunk 5]
```diff
@@ -0,0 +1,21 @@
...
+ * Unless required by applicable law or agreed to in writing, software
+ * distributed under the License is distributed on an "AS IS" BASIS,
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+package im.vector.app.core.usecase
+
+interface VectorBaseInOutUseCase<T, R> {
```
Comment (ouchadam) [inline vector/src/main/java/im/vector/app/core/usecase/VectorBaseInOutUseCase.kt:19]: do you think we should enforce every use case to have its own request input type?

I'm wondering if we'll end up with multiple declarations (which rx/coroutines are also doing~)

```kotlin
VectorBaseInOutUseCase2<T, T2, R>
VectorBaseInOutUseCase3<T, T3, R>
// etc
```

File: vector/src/main/java/im/vector/app/features/media/VectorAttachmentViewerViewModel.kt (hunk 2 above)
Comment (mnaturel) [reply vector/src/main/java/im/vector/app/features/media/VectorAttachmentViewerViewModel.kt:39]: I would say it is not "necessary", but I think it make the code more structured and unified. Every class is structured the same way so we know where to look for something. But this is the way I am used to work 😄 . Maybe we can decide together of best practices to structure code.

For the size of classes, I have never had such problem of size, it adds extra space in the class for sure, but if we respect the single responsability principle for each component, in most cases there is no problem.

Good point for the order by usage, I have never thought this way.

**Review by ouchadam — APPROVED** [review]
minor comments/questions, looks great to me! :100: 

would be awesome to also include a unit test for the use case :eyes: (there's some fixtures/fake available https://github.com/vector-im/element-android/tree/develop/vector/src/test/java/im/vector/app/test )

File: vector/src/main/java/im/vector/app/features/media/VectorAttachmentViewerViewModel.kt (hunk 2 above)
Comment (ouchadam) [reply vector/src/main/java/im/vector/app/features/media/VectorAttachmentViewerViewModel.kt:39]: > For the size of classes, I have never had such problem of size, it adds extra space in the class for sure, but if we respect the single responsability principle for each component, in most cases there is no problem.

that's my thinking, if the classes are small enough, they might not be needed :crossed_fingers:

File: vector/src/main/java/im/vector/app/features/media/domain/usecase/DownloadMediaUseCase.kt (hunk 3 above)
Comment (mnaturel) [reply vector/src/main/java/im/vector/app/features/media/domain/usecase/DownloadMediaUseCase.kt:41]: Thanks! I will take a look at it to make the change.

File: vector/src/main/java/im/vector/app/features/media/VectorAttachmentViewerAction.kt [hunk 6]
```diff
@@ -0,0 +1,24 @@
+/*
+ * Copyright 2019 New Vector Ltd
```
Comment (ariskotsomitopoulos) [inline vector/src/main/java/im/vector/app/features/media/VectorAttachmentViewerAction.kt:2]: Copyright `2022`*

**Comment by mnaturel** [comment]
> minor comments/questions, looks great to me! 💯
> 
> would be awesome to also include a unit test for the use case 👀 (there's some examples of fixtures/fakes available https://github.com/vector-im/element-android/tree/develop/vector/src/test/java/im/vector/app/test )

Yes indeed! I will try to add a unit test since this is the main goal of usecases.

File: vector/src/main/java/im/vector/app/features/media/VectorAttachmentViewerAction.kt (hunk 6 above)
Comment (mnaturel) [reply vector/src/main/java/im/vector/app/features/media/VectorAttachmentViewerAction.kt:2]: Thanks. I may have done a copy/paste from an older file. I will fix it.

File: vector/src/main/java/im/vector/app/features/media/VectorAttachmentViewerViewEvents.kt [hunk 7]
```diff
@@ -0,0 +1,23 @@
+/*
+ * Copyright (c) 2020 New Vector Ltd
```
Comment (ariskotsomitopoulos) [inline vector/src/main/java/im/vector/app/features/media/VectorAttachmentViewerViewEvents.kt:2]: **2022***

File: vector/src/main/java/im/vector/app/core/usecase/VectorBaseInOutUseCase.kt (hunk 5 above)
Comment (ganfra) [reply vector/src/main/java/im/vector/app/core/usecase/VectorBaseInOutUseCase.kt:19]: And I kind of think we shouldn't not have interface/base class for UseCase. It's not really solving anything, having just a naming convention would be enough in my opinion. Also UseCase don't absolutely have to be a class...

**Review by amshakal — APPROVED** [review]
TY! 👯

File: vector/src/main/java/im/vector/app/features/media/VectorAttachmentViewerViewModel.kt (hunk 2 above)
Comment (mnaturel) [reply vector/src/main/java/im/vector/app/features/media/VectorAttachmentViewerViewModel.kt]: As discussed, I removed all added section bloc comments.

File: vector/src/main/java/im/vector/app/core/usecase/VectorBaseInOutUseCase.kt (hunk 5 above)
Comment (mnaturel) [reply vector/src/main/java/im/vector/app/core/usecase/VectorBaseInOutUseCase.kt]: As discussed earlier, I removed the interface.

**Comment by mnaturel** [comment]
> minor comments/questions, looks great to me! 💯
> 
> would be awesome to also include a unit test for the use case 👀 (there's some examples of fixtures/fakes available https://github.com/vector-im/element-android/tree/develop/vector/src/test/java/im/vector/app/test )

@ouchadam I have added some unit tests, if you want to look at it.

File: vector/src/main/java/im/vector/app/features/media/domain/usecase/DownloadMediaUseCase.kt [hunk 8]
```diff
@@ -0,0 +1,47 @@
...
+        @ApplicationContext private val appContext: Context,
+        private val session: Session,
+        private val notificationUtils: NotificationUtils
+) {
+
+    suspend fun execute(input: File): Result<Unit> = withContext(session.coroutineDispatchers.io) {
+        runCatching {
+            saveMedia(
```
Comment (ouchadam) [inline vector/src/main/java/im/vector/app/features/media/domain/usecase/DownloadMediaUseCase.kt:38]: thinking out loud, I'm wondering if this `usecase` could inline and replace the static `saveMedia` function and if doing so would also help justify the usecase's existence :thinking:   

it would also have the benefit of making any other classes that use `saveMedia` easier to test.

File: vector/src/test/java/im/vector/app/features/media/domain/usecase/DownloadMediaUseCaseTest.kt [hunk 9]
```diff
@@ -0,0 +1,136 @@
...
+        unmockkStatic("im.vector.app.core.utils.ExternalApplicationsUtilKt")
+        unmockkStatic("im.vector.app.core.intent.VectorMimeTypeKt")
+        unmockkStatic(Uri::class)
+    }
+
+    @Test
+    fun `given a file when calling execute then save the file in local with success`() = runBlockingTest {
+        // Given
+        val file = mockk<File>()
+        val uri = mockk<Uri>()
```
Comment (ouchadam) [inline vector/src/test/java/im/vector/app/features/media/domain/usecase/DownloadMediaUseCaseTest.kt:82]: on another branch I've made a start on faking the `Uri` https://github.com/vector-im/element-android/pull/5323/files#diff-9661d91c5ac4526d77f2f6e67a2504518b064337839fe57abe3fe7e521072550

it would be great if we could also have a reusable `FakeFile`

File: vector/src/test/java/im/vector/app/features/media/domain/usecase/DownloadMediaUseCaseTest.kt [hunk 10]
```diff
@@ -0,0 +1,136 @@
...
+
+    @OverrideMockKs
+    lateinit var downloadMediaUseCase: DownloadMediaUseCase
+
+    @Before
+    fun setUp() {
+        MockKAnnotations.init(this)
+        mockkStatic("im.vector.app.core.utils.ExternalApplicationsUtilKt")
+        mockkStatic("im.vector.app.core.intent.VectorMimeTypeKt")
+        mockkStatic(Uri::class)
```
Comment (ouchadam) [inline vector/src/test/java/im/vector/app/features/media/domain/usecase/DownloadMediaUseCaseTest.kt:68]: do we need to statically mock the uri?

File: vector/src/test/java/im/vector/app/features/media/domain/usecase/DownloadMediaUseCaseTest.kt (hunk 9 above)
Comment (mnaturel) [reply vector/src/test/java/im/vector/app/features/media/domain/usecase/DownloadMediaUseCaseTest.kt:82]: Yes good idea! I will try add a `FakeFile` class. Should I keep the way I mock the `Uri`? Since you will add it in your PR.

Comment (ouchadam) [reply vector/src/test/java/im/vector/app/features/media/domain/usecase/DownloadMediaUseCaseTest.kt:82]: only the `FakeFile` sounds good to me (will also mean less conflicts!). I'll make a note to try and introduce the `FakeUri` here once the other PR is merged

File: vector/src/test/java/im/vector/app/features/media/domain/usecase/DownloadMediaUseCaseTest.kt (hunk 10 above)
Comment (mnaturel) [reply vector/src/test/java/im/vector/app/features/media/domain/usecase/DownloadMediaUseCaseTest.kt:68]: Yes, this is needed due to the hidden usage of a static method into the extension method `toUri()`: 
`public inline fun File.toUri(): Uri = Uri.fromFile(this)`

File: vector/src/main/java/im/vector/app/features/media/domain/usecase/DownloadMediaUseCase.kt (hunk 8 above)
Comment (mnaturel) [reply vector/src/main/java/im/vector/app/features/media/domain/usecase/DownloadMediaUseCase.kt:38]: Is your suggestion is to move the existing `saveMedia` code into the `useCase`? And then replace all `saveMedia` usage by the `useCase`. If yes, I totally agree since static method are very hard to test. Maybe I can do this in another PR.

File: vector/src/test/java/im/vector/app/features/media/domain/usecase/DownloadMediaUseCaseTest.kt (hunk 10 above)
Comment (ouchadam) [reply vector/src/test/java/im/vector/app/features/media/domain/usecase/DownloadMediaUseCaseTest.kt:68]: ah, thanks for explaining :+1:

File: vector/src/main/java/im/vector/app/features/media/domain/usecase/DownloadMediaUseCase.kt (hunk 8 above)
Comment (ouchadam) [reply vector/src/main/java/im/vector/app/features/media/domain/usecase/DownloadMediaUseCase.kt:38]: yep exactly ^^^ a future PR sounds great (potentially a github issue so anyone could pick up the task)

Comment (mnaturel) [reply vector/src/main/java/im/vector/app/features/media/domain/usecase/DownloadMediaUseCase.kt:38]: I have created the corresponding issue: https://github.com/vector-im/element-android/issues/5374

Comment (ouchadam) [reply vector/src/main/java/im/vector/app/features/media/domain/usecase/DownloadMediaUseCase.kt:38]: thanks! :100:
