### PR TITLE
Fix StackOverflowError while recording voice message [PSF-1065]

### LINKED ISSUE #6137: Long voice message: crash with StackOverflowError
Since 1.4.11, we observe StackOverflowError crashes reported by the PlayStore .

image

```
java.lang.StackOverflowError: 
  at java.util.ArrayList$SubList.add (ArrayList.java:1066)
  at java.util.ArrayList$SubList.add (ArrayList.java:1066)
  at java.util.ArrayList$SubList.add (ArrayList.java:1066)
  at java.util.ArrayList$SubList.add (ArrayList.java:1066)
```

Quick investigation:
- Create a diff between 1.4.8 and 1.4.10 (1.4.11 is just a bugfix) with
> git diff d589758 e7a2e65 > 1_4_8__1_4_10.patch
- Check all the `.add(` instances in the file `1_4_8__1_4_10.patch`
- I suspect this code https://github.com/vector-im/element-android/blob/main/vector/src/main/java/im/vector/app/features/voice/AudioWaveformView.kt#L139 to be the source of the crash.

Have not investigate more so far, nor test the code.

**Edit** I can repro the crash:
- start recording a voice message and lock the mic.
- wait for 2 minutes (max length of a voice message)
- the app crash

Add the labels A-Voice-Messages

### PR DESCRIPTION
**Pull request by onurays**
## Type of change

- [ ] Feature
- [x] Bugfix
- [ ] Technical
- [ ] Other :

## Content

- Start recording a voice message and lock the mic.
- Wait for 2 minutes (max length of a voice message)
- The app crashes

## Motivation and context

Fixes #6137 

## Tests

- Start recording a voice message and wait for 2 minutes
- Send the record, delete the record and everything should work as expected

## Tested devices

- [x] Physical
- [ ] Emulator
- OS version(s):

## Checklist

- [x] Changes has been tested on an Android device or Android emulator with API 21
- [x] UI change has been tested on both light and dark themes
- [x] Accessibility has been taken into account. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#accessibility
- [x] Pull request is based on the develop branch
- [x] Pull request includes a new file under ./changelog.d. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#changelog
- [ ] Pull request includes screenshots or videos if containing UI changes
- [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [x] You've made a self review of your PR
- [ ] If you have modified the screen flow, or added new screens to the application, you have updated the test [UiAllScreensSanityTest.allScreensTest()](https://github.com/vector-im/element-android/blob/main/vector/src/androidTest/java/im/vector/app/ui/UiAllScreensSanityTest.kt#L73)

### CODE REVIEW

**Review by ouchadam — APPROVED** [review]

File: vector/src/main/java/im/vector/app/features/voice/AudioWaveformView.kt [hunk 1]
```diff
@@ -156,7 +156,9 @@ class AudioWaveformView @JvmOverloads constructor(
             val barHeight = max(fft.value / MAX_FFT * (height - verticalPadding * 2), barMinHeight)
             visibleBarHeights.add(FFT(barHeight, fft.color))
             if (visibleBarHeights.size > maxVisibleBarCount) {
-                visibleBarHeights = visibleBarHeights.subList(visibleBarHeights.size - maxVisibleBarCount, visibleBarHeights.size)
+                visibleBarHeights = mutableListOf<FFT>().apply {
+                    addAll(visibleBarHeights.subList(visibleBarHeights.size - maxVisibleBarCount, visibleBarHeights.size))
+                }
```
Comment (bmarty) [inline vector/src/main/java/im/vector/app/features/voice/AudioWaveformView.kt:161]: I understand that we want to keep the last `maxVisibleBarCount` items on the list.

Can it be rewritten like this:

```kotlin
if (visibleBarHeights.size > maxVisibleBarCount) {
        visibleBarHeights = visibleBarHeights.takeLast(maxVisibleBarCount).toMutableList()
        // Or, but maybe less clear
        visibleBarHeights = visibleBarHeights.drop(maxVisibleBarCount - visibleBarHeights.size).toMutableList()
}
```

Alternatively we could drop the first items like this:

```kotlin
            while (visibleBarHeights.size > maxVisibleBarCount) {
                visibleBarHeights.removeAt(0)
            }
```

which has the advantage of not creating a new list. Also it should in fact only drop one item, each time we add an item and make the list too long.

To me those both suggestions are easier to read.

**Review by fedrunov — APPROVED** [review]

File: vector/src/main/java/im/vector/app/features/voice/AudioWaveformView.kt (hunk 1 above)
Comment (onurays) [reply vector/src/main/java/im/vector/app/features/voice/AudioWaveformView.kt]: Good idea, thanks!
