### PR TITLE
Keep device screen on during voice message playback and recording

### LINKED ISSUE #4022: voice message fail after phone lock
### Steps to reproduce

1. I move up voice button
2. I see, that voice record begin
3. Wait ~15 seconds and my phone was lock screen and off screen
4. Wait ~5 seconds 
5. Unlock screen
6. Unlock phone by gesture
7. I see, that voce recording is abort without any messages

Situation 2:
1. I still press on voice button and 
2. I see, that voice record begin
1. I still pressing on voice button
3. Wait ~15 seconds and my phone was lock screen and off screen
4. Wait ~5 seconds 
5. Unlock screen
6. Unlock phone by gesture
7. I see, that voce recording is abort without any messages

### What did you expect?
1. I expect, that when I start voice recording (by still pressing on button or move record icon to up for lock record) - phone will not lock screen.
2. If user lock voice record and lock phone screen manually - voice record must be continue at background.
### What happened?
1. If phone lock quickly - voice recording not usable - it break record.

### Your phone model

Yotaphone 2

### Operating system version

android 6.0.1

### Application version and app store

Element android gplay 1.2.2

### Homeserver

rsprim.ru

### Have you submitted a rageshake?

Yes

### PR DESCRIPTION
**Pull request by ouchadam**
Fixes #4022 Forces the device screen to stay awake during voice message playback and recording, this state is only active for the room details activity.

No gifs this time as it requires unplugging the device

### CODE REVIEW

File: vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailFragment.kt [hunk 1]
```diff
@@ -693,7 +695,20 @@ class RoomDetailFragment @Inject constructor(
...
 
     private fun setupVoiceMessageView() {
-        voiceMessagePlaybackTracker.track(VoiceMessagePlaybackTracker.RECORDING_ID, views.voiceMessageRecorderView)
+        voiceMessagePlaybackTracker.track(VoiceMessagePlaybackTracker.RECORDING_ID, object : VoiceMessagePlaybackTracker.Listener {
+            var lastKnownState: VoiceMessagePlaybackTracker.Listener.State? = null
+            override fun onUpdate(state: VoiceMessagePlaybackTracker.Listener.State) {
+                views.voiceMessageRecorderView.onUpdate(state)
+                if (lastKnownState == state) return
+                when (state) {
+                    is VoiceMessagePlaybackTracker.Listener.State.Playing,
```
Comment (bmarty) [inline vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailFragment.kt:704]: Is it also mandatory to keep the screen on for the playback? I guess this can be improve if in the future we implement a BG service.

**Review by bmarty — APPROVED** [review]
LGTM

File: vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailFragment.kt (hunk 1 above)
Comment (ouchadam) [reply vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailFragment.kt:704]: not mandatory but my thinking is if a voice recording is longer than 30/60 seconds~ (whatever the default screen timeout is) the user may not interact with the screen which would cause the playback to pause

I've had similar issues in the past when reading long messages

**Comment by DoM1niC** [comment]
Playback only not working for me, but playback  after this recording seems ok ...

**Comment by ouchadam** [comment]
> Playback only not working for me (screen turn off), but playback after recording seems ok (screen still active)...

interesting... I'll see if there's a missing code branch, thanks!

File: vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailActivity.kt [hunk 2]
```diff
@@ -114,6 +121,13 @@ class RoomDetailActivity :
             }
         }
         views.drawerLayout.addDrawerListener(drawerListener)
+
+        playbackTracker.trackActivity(ROOM_DETAILS_SCREEN_ON_TRACKER) { isActive ->
```
Comment (ouchadam) [inline vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailActivity.kt:125]: @bmarty using a different approach, this version is checking for all audio playback/recording activity within the `RoomDetailActivity`.

The previous version was only taking into account the voice recording view/composer, the new version also includes timeline audio playback

File: vector/src/main/java/im/vector/app/features/home/room/detail/timeline/helper/VoiceMessagePlaybackTracker.kt [hunk 3]
```diff
@@ -26,8 +26,17 @@ class VoiceMessagePlaybackTracker @Inject constructor() {
 
     private val mainHandler = Handler(Looper.getMainLooper())
     private val listeners = mutableMapOf<String, Listener>()
+    private val activityListeners = mutableMapOf<String, ActivityListener>()
     private val states = mutableMapOf<String, Listener.State>()
 
+    fun trackActivity(key: String, listener: ActivityListener) {
+        activityListeners[key] = listener
```
Comment (bmarty) [inline vector/src/main/java/im/vector/app/features/home/room/detail/timeline/helper/VoiceMessagePlaybackTracker.kt:33]: What is the advantage to have a `key` here? I see that it's easier to remove the listener since the caller does not have to pass it.
Maybe log a warning if `activityListeners[key]` already exist?

File: vector/src/main/java/im/vector/app/features/home/room/detail/timeline/helper/VoiceMessagePlaybackTracker.kt [hunk 4]
```diff
@@ -26,8 +26,17 @@ class VoiceMessagePlaybackTracker @Inject constructor() {
 
     private val mainHandler = Handler(Looper.getMainLooper())
     private val listeners = mutableMapOf<String, Listener>()
+    private val activityListeners = mutableMapOf<String, ActivityListener>()
     private val states = mutableMapOf<String, Listener.State>()
 
+    fun trackActivity(key: String, listener: ActivityListener) {
```
Comment (bmarty) [inline vector/src/main/java/im/vector/app/features/home/room/detail/timeline/helper/VoiceMessagePlaybackTracker.kt:32]: Maybe rename `key` to `id` for symmetry with `fun unTrackActivity()` and the other methods related to listeners

File: vector/src/main/java/im/vector/app/features/home/room/detail/timeline/helper/VoiceMessagePlaybackTracker.kt [hunk 5]
```diff
@@ -125,4 +136,8 @@ class VoiceMessagePlaybackTracker @Inject constructor() {
             data class Recording(val amplitudeList: List<Int>) : State()
         }
     }
+
+    fun interface ActivityListener {
+        fun onUpdate(isActive: Boolean)
```
Comment (bmarty) [inline vector/src/main/java/im/vector/app/features/home/room/detail/timeline/helper/VoiceMessagePlaybackTracker.kt:141]: Nit: `isActive` is not really accurate to me. Maybe rename to `isPlayingOrRecording`? Also for the `val` at line 64.
This is not a big deal though, I can live with it :)

**Review by bmarty — APPROVED** [review]
LGTM

File: vector/src/main/java/im/vector/app/features/home/room/detail/timeline/helper/VoiceMessagePlaybackTracker.kt (hunk 3 above)
Comment (ouchadam) [reply vector/src/main/java/im/vector/app/features/home/room/detail/timeline/helper/VoiceMessagePlaybackTracker.kt:33]: it was mainly for being able to remove the listener, happy to switch to something instance based

File: vector/src/main/java/im/vector/app/features/home/room/detail/timeline/helper/VoiceMessagePlaybackTracker.kt (hunk 5 above)
Comment (ouchadam) [reply vector/src/main/java/im/vector/app/features/home/room/detail/timeline/helper/VoiceMessagePlaybackTracker.kt:141]: makes sense, will update!

File: vector/src/main/java/im/vector/app/features/home/room/detail/timeline/helper/VoiceMessagePlaybackTracker.kt (hunk 3 above)
Comment (ouchadam) [reply vector/src/main/java/im/vector/app/features/home/room/detail/timeline/helper/VoiceMessagePlaybackTracker.kt]: https://github.com/vector-im/element-android/pull/4557/commits/28af0a637fb5d0fa1b77ba741c306cfeb9f7bcea also renames the parameter

**Comment by DoM1niC** [comment]
Can it happen @ouchadam if a playback is done, that the screen still active ? :P Is not bad but normal should be track by state after play/stop a Voice Message

**Comment by ouchadam** [comment]
> Can it happen @ouchadam if a playback is done, that the screen still active ? :P Is not bad but normal should be track by state after play/stop a Voice Message

for playback, the screen logic seemed to work fine for me (at least the logs were working as expected), but I did catch an issue where the voice recording didn't re-enable the automatic screen turning off after finishing recording https://github.com/vector-im/element-android/pull/4557/commits/9e9116df2f75eace6ef3ea076fb14db01260aca0
