### PR TITLE
Fix | Explore room list: the RoomId is displayed instead of name (#3371)

### LINKED ISSUE #3371: Spaces | Explore room list: the RoomId is displayed instead of name
In #community:matrix.org 

image

### PR DESCRIPTION
**Pull request by BillCarsonFr**
Fixes #3371

### CODE REVIEW

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/util/MatrixItem.kt [hunk 1]
```diff
@@ -159,4 +159,4 @@ fun RoomMemberSummary.toMatrixItem() = MatrixItem.UserItem(userId, displayName,
 
 fun SenderInfo.toMatrixItem() = MatrixItem.UserItem(userId, disambiguatedDisplayName, avatarUrl)
 
-fun SpaceChildInfo.toMatrixItem() = MatrixItem.RoomItem(childRoomId, name, avatarUrl)
+fun SpaceChildInfo.toMatrixItem() = MatrixItem.RoomItem(childRoomId, name ?: canonicalAlias ?: aliases?.firstOrNull(), avatarUrl)
```
Comment (bmarty) [inline matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/util/MatrixItem.kt:162]: I remember that we should never use `aliases` as a room name fallback. Only canonical alias is permitted. But `getPrimaryAlias()` is still a thing...

**Review by bmarty — APPROVED** [review]
LGTM, one remark about usage of aliases

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/util/MatrixItem.kt (hunk 1 above)
Comment (BillCarsonFr) [reply matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/util/MatrixItem.kt]: Ok updated
