### PR TITLE
Fix always jumps to the bottom of the timeline #8090

### LINKED ISSUE #8090: Element Android always jumps to the bottom of the timeline
It seems like it is a design decision for leaving a room and opening it back up (although maybe that should be reconsidered), but opening an image, a profile, threads, the room settings and so on should not reset the position in the timeline.

Reproduce:
- scroll up
- open image
- close image
- you are at the bottom of the timeline again

### PR DESCRIPTION
**Pull request by ganfra**
Fix #8090 
The regression came from this https://github.com/vector-im/element-android/pull/7734 
I've checked it was still fixing the related notification issue ^

### CODE REVIEW

**Review by jmartinesp — APPROVED** [review]
LGTM, we just need to fix the lint issues.

File: vector/src/main/java/im/vector/app/features/home/room/detail/TimelineFragment.kt [hunk 1]
```diff
@@ -1038,7 +1039,6 @@ class TimelineFragment :
         timelineEventController.callback = this
         timelineEventController.timeline = timelineViewModel.timeline
 
-        views.timelineRecyclerView.trackItemsVisibilityChange()
```
Comment (bmarty) [inline vector/src/main/java/im/vector/app/features/home/room/detail/TimelineFragment.kt:1041]: I am wondering if this extension is correct since we never detach the tracker...

**Review by bmarty — COMMENTED** [review]
Thanks a lot!
