### PR TITLE
Fix default encrypted for restricted

### LINKED ISSUE #4045: Align new room encryption default to Web
### Your use case

In a space, create a new room.
In the Create New Room dialog, Room settings -> Enable encryption should be on by default as it is in Web because we want to encourage secure communications

### Have you considered any alternatives?

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by BillCarsonFr**
Fixes #4045 

Align default encrypted for restricted room as web is doing it, i.e use what is in well-known (default e2e).
Private and restricted encrypted switch is on if well-known e2e is by default.
=> Also if the user did manually change the encrypted toggled then always take that value and not the default.

Additional Fix:
When no space was selected, the option to set the room to restricted was visible, that would create a room restricted to nothing. So now if no space selected you'll only have a choice between Private or Public

### CODE REVIEW

File: vector/src/main/java/im/vector/app/features/roomdirectory/createroom/CreateRoomController.kt [hunk 1]
```diff
@@ -165,7 +165,11 @@ class CreateRoomController @Inject constructor(
                             host.stringProvider.getString(R.string.create_room_encryption_description)
                         }
                 )
-                switchChecked(viewState.isEncrypted)
+                if (viewState.isEncrypted != null) {
```
Comment (ouchadam) [inline vector/src/main/java/im/vector/app/features/roomdirectory/createroom/CreateRoomController.kt:168]: NIT: Something I've noticed through the codebase is we tend to favour inverted if conditions, it might just be me but I find positive conditions much easier on the brain 

```kotlin
if (viewState.isEncrypted == null) {
  switchChecked(viewState.defaultEncrypted[viewState.roomJoinRules] ?: false)
} else {
  switchChecked(viewState.isEncrypted)
}
``` 

and whilst inverting the if ^^^ I also noticed we could simplify the checked state by chaining the fallbacks

```kotlin
val isSwitchChecked = viewState.isEncrypted ?: viewState.defaultEncrypted[viewState.roomJoinRules] ?: false
```

File: vector/src/main/java/im/vector/app/features/roomdirectory/createroom/CreateRoomFragment.kt [hunk 2]
```diff
@@ -163,8 +163,9 @@ class CreateRoomFragment @Inject constructor(
     }
 
     override fun selectVisibility() = withState(viewModel) { state ->
-
-        val allowed = if (state.supportsRestricted) {
+        // If restricted is supported and the user is in the context of a parent space
+        // then show restricted option.
+        val allowed = if (state.supportsRestricted && state.parentSpaceId != null) {
```
Comment (ouchadam) [inline vector/src/main/java/im/vector/app/features/roomdirectory/createroom/CreateRoomFragment.kt:168]: NIT: if we wanted to avoid using separate branches for appending to the list (and potentially be more kotlin idiomatic) we could use 

`listOfNotNull`

```kotlin
val list = listOfNotNull(
        INVITE,
        PUBLIC,
        RESTRICTED.takeIf { state.supportsRestricted && state.parentSpaceId != null }
)
```

or `buildList`

```kotlin
val list = buildList {
    add(INVITE)
    add(PUBLIC)
    if (state.supportsRestricted && state.parentSpaceId != null) {
        add(RESTRICTED)
    }
}
```

File: vector/src/main/java/im/vector/app/features/roomdirectory/createroom/CreateRoomViewModel.kt [hunk 3]
```diff
@@ -286,8 +291,17 @@ class CreateRoomViewModel @AssistedInject constructor(@Assisted private val init
                     disableFederation = state.disableFederation
 
                     // Encryption
-                    if (state.isEncrypted) {
-                        enableEncryption()
+                    // we ignore the isEncrypted for public room as the switch is hidden in this case
+                    if (state.roomJoinRules != RoomJoinRules.PUBLIC && state.isEncrypted != null) {
```
Comment (ouchadam) [inline vector/src/main/java/im/vector/app/features/roomdirectory/createroom/CreateRoomViewModel.kt:295]: NIT: it might be clearer to convert this to a `when` and decouple `isEncrypted` creation from the `enableEncryption()`

```kotlin
val isEncrpyted = when {
  // public rooms use the default encrypted join rules as the switch is hidden
  state.roomJoinRules == RoomJoinRules.PUBLIC -> state.defaultEncrypted[state.roomJoinRules] ?: false
  else -> state.isEncrypted ?: false
}

if (isEncrpyted) {
  enableEncryption()
}
```

what do you think?

**Comment by ouchadam** [comment]
awesome stuff! :100:  I'm attempting to use https://emmer.dev/blog/code-review-comment-prefixes/ to hopefully avoid confusion in my reviews :sweat_smile: 

`NIT` being opinionated optional comments

File: vector/src/main/java/im/vector/app/features/roomdirectory/createroom/CreateRoomController.kt (hunk 1 above)
Comment (bmarty) [reply vector/src/main/java/im/vector/app/features/roomdirectory/createroom/CreateRoomController.kt:168]: Generally I agree to avoid `if(!cond) {} else {}`, but sometimes it also nice to have the most common case first. I'm not saying this is the case here, just wanted to add my two pence :)

File: vector/src/main/java/im/vector/app/features/roomdirectory/createroom/CreateRoomController.kt [hunk 4]
```diff
@@ -165,7 +165,11 @@ class CreateRoomController @Inject constructor(
...
+                    switchChecked(viewState.isEncrypted)
+                } else {
+                    switchChecked(viewState.defaultEncrypted[viewState.roomJoinRules] ?: false)
+                }
```
Comment (bmarty) [inline vector/src/main/java/im/vector/app/features/roomdirectory/createroom/CreateRoomController.kt:172]: In this case, I would have probably write:
```kotlin
switchChecked(
    viewState.isEncrypted
    ?: viewState.defaultEncrypted[viewState.roomJoinRules]
    ?: false
)
```

File: vector/src/main/java/im/vector/app/features/roomdirectory/createroom/CreateRoomViewModel.kt (hunk 3 above)
Comment (bmarty) [reply vector/src/main/java/im/vector/app/features/roomdirectory/createroom/CreateRoomViewModel.kt:295]: `?: false` can also get out the `when` branch. We also have a nice `.orFalse` extension.
@BillCarsonFr if you copy this code, please fix the typo in `isEncrpyted` 😛

**Review by bmarty — COMMENTED** [review]
LGTM, just some comment on top on @adam comments :)

File: vector/src/main/java/im/vector/app/features/roomdirectory/createroom/CreateRoomViewModel.kt (hunk 3 above)
Comment (ouchadam) [reply vector/src/main/java/im/vector/app/features/roomdirectory/createroom/CreateRoomViewModel.kt:295]: for some reason I can't type `isEncrypted` :facepalm:

File: vector/src/main/java/im/vector/app/features/roomdirectory/createroom/CreateRoomFragment.kt (hunk 2 above)
Comment (BillCarsonFr) [reply vector/src/main/java/im/vector/app/features/roomdirectory/createroom/CreateRoomFragment.kt:168]: AS is telling me that it's experimental

File: vector/src/main/java/im/vector/app/features/roomdirectory/createroom/CreateRoomViewModel.kt (hunk 3 above)
Comment (BillCarsonFr) [reply vector/src/main/java/im/vector/app/features/roomdirectory/createroom/CreateRoomViewModel.kt:295]: ah ah I definitly failed to make it clearer :D

File: vector/src/main/java/im/vector/app/features/roomdirectory/createroom/CreateRoomController.kt (hunk 1 above)
Comment (BillCarsonFr) [reply vector/src/main/java/im/vector/app/features/roomdirectory/createroom/CreateRoomController.kt:168]: Yes I explicitly used the if/else like that thinking it will ease reading of the code (otherwise I would have gone for the chaining).
Looks like I failed  :D.

File: vector/src/main/java/im/vector/app/features/roomdirectory/createroom/CreateRoomFragment.kt (hunk 2 above)
Comment (ouchadam) [reply vector/src/main/java/im/vector/app/features/roomdirectory/createroom/CreateRoomFragment.kt:168]: ah my bad, I totally forgot that `buildList` is still experimental

File: vector/src/main/java/im/vector/app/features/roomdirectory/createroom/CreateRoomViewState.kt [hunk 5]
```diff
@@ -38,7 +38,8 @@ data class CreateRoomViewState(
         val parentSpaceSummary: RoomSummary? = null,
         val supportsRestricted: Boolean = false,
         val aliasLocalPart: String? = null,
-        val isSubSpace: Boolean = false
+        val isSubSpace: Boolean = false,
+        val defaultEncrypted: Map<RoomJoinRules, Boolean> = emptyMap()
```
[the remark this answers is not in the document]
Comment (BillCarsonFr) [reply vector/src/main/java/im/vector/app/features/roomdirectory/createroom/CreateRoomViewState.kt]: done

**Review by ouchadam — APPROVED** [review]

**Review by bmarty — APPROVED** [review]
