### PR TITLE
Fix flaky tests for voice recording feature

### LINKED ISSUE #6329: Instrumented tests for VoiceRecorders are a bit flaky
### Steps to reproduce

Run `vector`'s  androidTest, sometimes `im.vector.app.features.voice` tests fail for no good reason. As those rely on Android APIs such as AudioRecorder and VoiceRecorder and some JNI code, timing can be tricky while testing.

#### What did you expect?

Those tests to always pass.

#### What happened instead?

They fail sometimes.

### Your phone model

Emulator

### Operating system version

Android 9.0

### Application version and app store

_No response_

### Homeserver

_No response_

### Will you send logs?

No

### Are you willing to provide a PR?

Yes

### PR DESCRIPTION
**Pull request by jmartinesp**
## Type of change

- [ ] Feature
- [ ] Bugfix
- [x] Technical
- [ ] Other :

## Content

Added a couple of methods to `vector`'s  instrumented tests to retry a check several times, applied this to VoiceRecorder tests.

Fixes #6329 .

## Motivation and context

VoiceRecorder instrumented tests are a bit flaky as they depend on Audio/MediaRecorder and some JNI code. With this code we'll retry those several times instead of failing on the first try.

## Checklist

- [ ] Changes has been tested on an Android device or Android emulator with API 21
- [ ] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#accessibility
- [x] Pull request is based on the develop branch
- [x] Pull request includes a new file under ./changelog.d. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#changelog
- [ ] Pull request includes screenshots or videos if containing UI changes
- [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [x] You've made a self review of your PR
- [ ] If you have modified the screen flow, or added new screens to the application, you have updated the test [UiAllScreensSanityTest.allScreensTest()](https://github.com/vector-im/element-android/blob/main/vector/src/androidTest/java/im/vector/app/ui/UiAllScreensSanityTest.kt#L73)

### CODE REVIEW

File: vector/src/androidTest/java/im/vector/app/core/utils/WaitUntil.kt [hunk 1]
```diff
@@ -0,0 +1,69 @@
...
+    do {
+        if (condition()) return
+        delay(delay.inWholeMilliseconds)
+    } while (System.currentTimeMillis() - start < timeout.inWholeMilliseconds)
+    fail(errorMessage)
+}
+
+/**
+ * Tries a [block] several times until it runs with no errors or a [timeout] is reached waiting for some [delay] time between retries.
+ * On timeout it fails with a caught [AssertionError] or a custom [errorMessage].
```
Comment (bmarty) [inline vector/src/androidTest/java/im/vector/app/core/utils/WaitUntil.kt:45]: I would change the order here since `errorMessage` seems to have priority over `AssertionError`

File: vector/src/androidTest/java/im/vector/app/core/utils/WaitUntil.kt [hunk 2]
```diff
@@ -0,0 +1,69 @@
...
+            return
+        } catch (e: AssertionError) {
+            error = e
+        }
+        delay(delay.inWholeMilliseconds)
+    } while (System.currentTimeMillis() - start < timeout.inWholeMilliseconds)
+    if (errorMessage != null) {
+        fail(errorMessage)
+    } else {
+        error?.let { throw it }
```
Comment (bmarty) [inline vector/src/androidTest/java/im/vector/app/core/utils/WaitUntil.kt:67]: We can use `error!!` for code clarity maybe. Else we could think that a case is missing.
So maybe just write `throw error!!`.

File: vector/src/androidTest/java/im/vector/app/core/utils/WaitUntil.kt [hunk 3]
```diff
@@ -0,0 +1,69 @@
...
+ * limitations under the License.
+ */
+
+package im.vector.app.core.utils
+
+import kotlinx.coroutines.delay
+import org.amshove.kluent.fail
+import kotlin.time.Duration
+import kotlin.time.Duration.Companion.milliseconds
+import kotlin.time.Duration.Companion.seconds
```
Comment (bmarty) [inline vector/src/androidTest/java/im/vector/app/core/utils/WaitUntil.kt:23]: TIL !

**Review by bmarty — COMMENTED** [review]
Some remarks

File: vector/src/androidTest/java/im/vector/app/core/utils/WaitUntil.kt [hunk 4]
```diff
@@ -0,0 +1,69 @@
...
+
+/**
+ * Tries a [condition] several times until it returns true or a [timeout] is reached waiting for some [delay] time between retries.
+ * On timeout it fails with an [errorMessage].
+ */
+suspend fun waitUntilCondition(
+        errorMessage: String,
+        timeout: Duration = 1.seconds,
+        delay: Duration = 50.milliseconds,
```
Comment (ouchadam) [inline vector/src/androidTest/java/im/vector/app/core/utils/WaitUntil.kt:32]: tiny nit, maybe just me :smile:  on first read `delay` makes me think this is _only_ an initial delay, `interval` or `retryDelay` might give a little extra context~

**Review by ouchadam — APPROVED** [review]
LGTM :crossed_fingers:

**Review by ganfra — APPROVED** [review]
LGTM
