### PR TITLE
legacy groups removal

### LINKED ISSUE #5733: Remove support for communities/groups
Communities have been deprecated so they should be removed from the app.

## Tasks

*   [x] ~~Estimate this issue~~
*   [x] ~~Announce to users who have communities enabled that they will be removed with the next release~~
*   [ ] Remove support for communities
*  [ ] Add copy for when a user tries to access a community (e.g. through a matrix.to link)
*   [ ] Compile a list of potential areas of the app that are touched as part of the coding work
*   [ ] Run a regression testing session to confirm that the removal of communities does not break anything else

## References

*   [Web task](https://github.com/vector-im/element-web/issues/17532)

### PR DESCRIPTION
**Pull request by fedrunov**
## Type of change

- [ ] Feature
- [ ] Bugfix
- [x] Technical
- [ ] Other :

## Content

since we don't support communities/groups, we need to clean up code from it

## Motivation and context

closes #5733 

## Tests

There are many things to be tested for this PR, since I had to remove some abstractions, since they are obsolete now.
affected areas:

Selecting/Switching space
Add room
Invite users to room
Handling permalinks
Unreads count

## Tested devices

- [ ] Physical
- [ ] Emulator
- OS version(s):

## Checklist

- [ ] Changes has been tested on an Android device or Android emulator with API 21
- [ ] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#accessibility
- [ ] Pull request is based on the develop branch
- [ ] Pull request includes a new file under ./changelog.d. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#changelog
- [ ] Pull request includes screenshots or videos if containing UI changes
- [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [ ] You've made a self review of your PR
- [ ] If you have modified the screen flow, or added new screens to the application, you have updated the test [UiAllScreensSanityTest.allScreensTest()](https://github.com/vector-im/element-android/blob/main/vector/src/androidTest/java/im/vector/app/ui/UiAllScreensSanityTest.kt#L73)

### CODE REVIEW

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/permalinks/PermalinkData.kt [hunk 1]
```diff
@@ -54,7 +54,5 @@ sealed class PermalinkData {
 
     data class UserLink(val userId: String) : PermalinkData()
 
-    data class GroupLink(val groupId: String) : PermalinkData()
-
-    data class FallbackLink(val uri: Uri) : PermalinkData()
+    data class FallbackLink(val uri: Uri, val isLegacyGroupLink: Boolean = false) : PermalinkData()
```
Comment (fedrunov) [inline matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/permalinks/PermalinkData.kt:57]: I've added a param here instead of keeping `GroupLink` to not force every `when` which will handle `PermalinkData` to explicitly handle `GroupLink` class. Since it's legacy I'd like to reduce impact on future development, but I'm not sure that making it param really helps, so I'd like to hear your thoughts

File: vector/src/main/java/im/vector/app/features/home/room/list/RoomListSectionBuilderSpace.kt [hunk 2]
```diff
@@ -65,7 +64,7 @@ class RoomListSectionBuilderSpace(
         private val onUpdatable: (UpdatableLivePageResult) -> Unit,
         private val suggestedRoomJoiningState: LiveData<Map<String, Async<Unit>>>,
         private val onlyOrphansInHome: Boolean = false
-) : RoomListSectionBuilder {
```
Comment (ericdecanini) [inline vector/src/main/java/im/vector/app/features/home/room/list/RoomListSectionBuilderSpace.kt:68]: I would maybe rename this class to `RoomListSectionBuilder` since it's now the only one

File: vector/src/main/java/im/vector/app/features/navigation/DefaultNavigator.kt [hunk 3]
```diff
@@ -355,54 +329,22 @@ class DefaultNavigator @Inject constructor(
...
-
-                                    override fun inviteToRoom(roomId: String) {
-                                        val intent = InviteUsersToRoomActivity.getIntent(context, roomId)
-                                        context.startActivity(intent)
-                                    }
-                                }
-                        ).show(fm, InviteRoomSpaceChooserBottomSheet::class.java.name)
+        when (val currentSpace = appStateHandler.getCurrentSpace()) {
+            null -> InviteUsersToRoomActivity.getIntent(context, roomId).start(context)
+            else -> {
```
Comment (ericdecanini) [inline vector/src/main/java/im/vector/app/features/navigation/DefaultNavigator.kt:341]: I know we just had a conversation about not overusing smaller functions to the point that it obscures intent but this is something I'd definitely extract

File: vector/src/main/java/im/vector/app/features/navigation/DefaultNavigator.kt [hunk 4]
```diff
@@ -355,54 +329,22 @@ class DefaultNavigator @Inject constructor(
...
-                } else {
-                    CreateDirectRoomActivity.getIntent(context)
-                }
-            }
-            else -> null
-        } ?: return
-        context.startActivity(intent)
+        when (val currentSpace = appStateHandler.getCurrentSpace()) {
+            null -> CreateDirectRoomActivity.getIntent(context)
+            else -> SpacePeopleActivity.newIntent(context, currentSpace.roomId)
```
Comment (ericdecanini) [inline vector/src/main/java/im/vector/app/features/navigation/DefaultNavigator.kt:334]: I'm a bit confused here as the function says `openCreateDirectRoom`, but within a space it looks like it's doing something different (same for the function higher above). I know this was also the way it was in the old code but maybe now is a good time to improve upon it

File: vector/src/main/res/values/strings.xml [hunk 5]
```diff
@@ -174,7 +174,8 @@
     <string name="initial_sync_start_importing_account_joined_rooms">Initial sync:\nLoading your conversations\nIf you\'ve joined lots of rooms, this might take a while</string>
     <string name="initial_sync_start_importing_account_invited_rooms">Initial sync:\nImporting invited rooms</string>
     <string name="initial_sync_start_importing_account_left_rooms">Initial sync:\nImporting left rooms</string>
-    <string name="initial_sync_start_importing_account_groups">Initial sync:\nImporting communities</string>
+    <!--TODO:delete-->
```
Comment (ericdecanini) [inline vector/src/main/res/values/strings.xml:177]: Todo? (a few of this in this file)

**Review by ericdecanini — COMMENTED** [review]
Real good cleanup. It's nice to not have a disambiguity between spaces and groups now. Just a few comments

File: vector/src/main/res/values/strings.xml (hunk 5 above)
Comment (fedrunov) [reply vector/src/main/res/values/strings.xml:177]: we do not remove translatable resources, instead we mark them to be removed, to not cause conflicts on Webplate

https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#removing-existing-strings

File: vector/src/main/java/im/vector/app/features/navigation/DefaultNavigator.kt (hunk 4 above)
Comment (fedrunov) [reply vector/src/main/java/im/vector/app/features/navigation/DefaultNavigator.kt:334]: In space it opens a list of users in this space while at home it opens an activity to search for public users. So it's quite similar and it's part of "create dm" flow. I agree that naming is confusing a bit, but not sure if we can do something better here

Comment (ericdecanini) [reply vector/src/main/java/im/vector/app/features/navigation/DefaultNavigator.kt:334]: I see, it makes sense. Maybe a comment here mentioning that `SpacePeopleActivity` is where direct rooms are created within a space? WDYT?

File: changelog.d/5733.misc [hunk 6]
```diff
@@ -0,0 +1 @@
+Communities/Groups are removed completely
```
Comment (bmarty) [inline changelog.d/5733.misc:1]: Please add another file `5733.sdk` to notify SDK users about the deleted/updated API(s).

File: vector/src/main/java/im/vector/app/features/navigation/DefaultNavigator.kt (hunk 3 above)
Comment (fedrunov) [reply vector/src/main/java/im/vector/app/features/navigation/DefaultNavigator.kt]: i've updated, take a look now

**Review by bmarty — CHANGES_REQUESTED** [review]
Nice cleanup, thanks!
Some remarks.

File: vector/src/main/res/values/strings.xml [hunk 7]
```diff
@@ -2076,6 +2079,7 @@
     <string name="soft_logout_sso_not_same_user_error">The current session is for user %1$s and you provide credentials for user %2$s. This is not supported by ${app_name}.\nPlease first clear data, then sign in again on another account.</string>
 
     <string name="permalink_malformed">Your matrix.to link was malformed</string>
+    <string name="permalink_unsupported_groups">You\'re trying to access a link to a community (+community:matrix.org). Communities are no longer supported and have been replaced by spaces.</string>
```
[the remark this answers is not in the document]
Comment (bmarty) [reply vector/src/main/res/values/strings.xml:2082]: (this is what is expected in https://github.com/vector-im/element-android/issues/5733#issuecomment-1096774482 by the way)

[the remark this answers is not in the document]
Comment (bmarty) [reply vector/src/main/res/values/strings.xml:2082]: (and there is also a missing link)

File: vector/src/main/java/im/vector/app/features/navigation/DefaultNavigator.kt (hunk 4 above)
Comment (bmarty) [reply vector/src/main/java/im/vector/app/features/navigation/DefaultNavigator.kt:335]: AFAIU `SpacePeopleActivity` and `SpacePeopleFragment` are not only used to create DMs. But `People` could be renamed to `User` probably.

File: vector/src/main/res/values/strings.xml (hunk 7 above)
[the remark this answers is not in the document]
Comment (fedrunov) [reply vector/src/main/res/values/strings.xml]: After some discussion text was updated. I've posted update to the issue

**Review by ericdecanini — APPROVED** [review]
Thanks for making the changes. LGTM

**Review by bmarty — COMMENTED** [review]
Thanks for the update!
Did not made a full review, so I am just commenting here, but my remarks have been handled.

**Review by bmarty — APPROVED** [review]

**Comment by bmarty** [comment]
> I don't think I saw changes on RoomSummaryEntity (there should be there a list of the groups a room belongs to); Also a database migration is needed no?

This is what I see on develop, so yes, a cleanup and DB migration is necessary: https://github.com/vector-im/element-android/blob/develop/matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/model/RoomSummaryEntity.kt#L243

```kotlin
    var groupIds: String? = null
        set(value) {
            if (value != field) field = value
        }
```

@fedrunov can you handle it please?

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/migration/MigrateSessionTo032.kt [hunk 8]
```diff
@@ -0,0 +1,29 @@
...
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+package org.matrix.android.sdk.internal.database.migration
+
+import io.realm.DynamicRealm
+import org.matrix.android.sdk.internal.util.database.RealmMigrator
+
+internal class MigrateSessionTo032(realm: DynamicRealm) : RealmMigrator(realm, 31) {
```
Comment (bmarty) [inline matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/migration/MigrateSessionTo032.kt:22]: Not a big deal, but the correct value for RealmMigrator's 2nd param should be `32`.

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/migration/MigrateSessionTo032.kt [hunk 9]
```diff
@@ -0,0 +1,29 @@
...
+
+    override fun doMigrate(realm: DynamicRealm) {
+        // Add hasFailedSending in RoomSummary and a small warning icon on room list
+        realm.schema.get("RoomSummaryEntity")
```
Comment (bmarty) [inline matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/migration/MigrateSessionTo032.kt:26]: Also please update (or just remove) the comment above.

**Review by BillCarsonFr — APPROVED** [review]
LGTM
