### PR TITLE
Uploading a file to a room caused it to have a info.size of -1

### LINKED ISSUE #2141: Uploading a file to a room caused it to have a info.size of -1
The file itself was fine, but the info is wrong. The file was uploaded via the sharing feature from another app.

```json
{
  "content": {
    "body": "2020-09-20 14:17.kmz",
    "file": {
      "hashes": {
        "sha256": "teCKsNkRVo5VAxZu9+/CSbd1V9psNTjbEEeXRJxvUCE"
      },
      "iv": "49Ra2xgOSs8AAAAAAAAAAA",
      "key": {
        "alg": "A256CTR",
        "ext": true,
        "k": "B6xVPtphPdn3NPttOAWmxsjcCC9pUWrTIoFyjZ-ySPw",
        "key_ops": [
          "encrypt",
          "decrypt"
        ],
        "kty": "oct"
      },
      "mimetype": "application/vnd.google-earth.kmz",
      "url": "mxc://half-shot.uk/3194e07c835b6d4fc3430606f7fdf19fc76a68f9",
      "v": "v2"
    },
    "info": {
      "mimetype": "application/vnd.google-earth.kmz",
      "size": -1
    },
    "msgtype": "m.file"
  },
  "room_id": "!vHHXZqTuzXCuldIVQJ:half-shot.uk",
  "type": "m.room.message"
}
```

### PR DESCRIPTION
**Pull request by onurays**
Fixes #2141

### CODE REVIEW

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/content/ContentAttachmentData.kt [hunk 1]
```diff
@@ -25,7 +25,7 @@ import kotlinx.android.parcel.Parcelize
 @Parcelize
 @JsonClass(generateAdapter = true)
 data class ContentAttachmentData(
-        val size: Long = 0,
+        var size: Long = 0,
```
Comment (bmarty) [inline matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/content/ContentAttachmentData.kt:28]: I do not like this change...

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/content/UploadContentWorker.kt [hunk 2]
```diff
@@ -154,11 +154,11 @@ internal class UploadContentWorker(val context: Context, params: WorkerParameter
                                 compressedFile.inputStream().use {
                                     val options = BitmapFactory.Options().apply { inJustDecodeBounds = true }
                                     val bitmap = BitmapFactory.decodeStream(it, null, options)
-                                    val fileSize = bitmap?.byteCount ?: 0
+                                    val fileSize = bitmap?.byteCount ?: compressedFile.length()
```
Comment (bmarty) [inline matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/content/UploadContentWorker.kt:157]: Add `toInt()` here:
```suggestion
                                    val fileSize = bitmap?.byteCount ?: compressedFile.length().toInt()
```

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/content/UploadContentWorker.kt [hunk 3]
```diff
@@ -154,11 +154,11 @@ internal class UploadContentWorker(val context: Context, params: WorkerParameter
...
                                     newImageAttributes = NewImageAttributes(
                                             options.outWidth,
                                             options.outHeight,
-                                            fileSize
+                                            fileSize.toInt()
```
Comment (bmarty) [inline matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/content/UploadContentWorker.kt:161]: and not here

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/content/UploadContentWorker.kt [hunk 4]
```diff
@@ -200,6 +200,11 @@ internal class UploadContentWorker(val context: Context, params: WorkerParameter
                     Timber.e(failure, "## FileService: Failed to update file cache")
                 }
 
+                // Fix: OpenableColumns.SIZE may return -1
+                if (params.attachment.size <= 0) {
```
Comment (bmarty) [inline matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/content/UploadContentWorker.kt:204]:
```suggestion
                if (params.attachment.size < 0) {
```

?

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/content/UploadContentWorker.kt [hunk 5]
```diff
@@ -288,7 +293,7 @@ internal class UploadContentWorker(val context: Context, params: WorkerParameter
                                       newImageAttributes: NewImageAttributes?): Result {
         notifyTracker(params) { contentUploadStateTracker.setSuccess(it) }
         params.localEchoIds.forEach {
-            updateEvent(it.eventId, attachmentUrl, encryptedFileInfo, thumbnailUrl, thumbnailEncryptedFileInfo, newImageAttributes)
+            updateEvent(it.eventId, attachmentUrl, encryptedFileInfo, thumbnailUrl, thumbnailEncryptedFileInfo, newImageAttributes, params.attachment.size)
```
Comment (bmarty) [inline matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/content/UploadContentWorker.kt:296]: I do not understand why you are adding a param here, can't we use `NewImageAttributes.newFileSize`

Maybe rename `NewImageAttributes` with `NewAttachmentAttributes` by the same occasion.

**Review by bmarty — CHANGES_REQUESTED** [review]
I think this will fix the problem, thanks, but as usual I have a few remarks :)

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/content/ContentAttachmentData.kt (hunk 1 above)
Comment (onurays) [reply matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/content/ContentAttachmentData.kt:28]: Me too, reverted.

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/content/UploadContentWorker.kt (hunk 2 above)
Comment (onurays) [reply matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/content/UploadContentWorker.kt:157]: Done.

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/content/UploadContentWorker.kt (hunk 4 above)
Comment (onurays) [reply matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/content/UploadContentWorker.kt:204]: I was afraid of any other Android api related bugs. But your suggestion makes sense, done.

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/content/UploadContentWorker.kt (hunk 5 above)
Comment (onurays) [reply matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/content/UploadContentWorker.kt:296]: Done.

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/content/UploadContentWorker.kt [hunk 6]
```diff
@@ -48,10 +48,10 @@ import java.io.File
 import java.util.UUID
 import javax.inject.Inject
 
-private data class NewImageAttributes(
-        val newWidth: Int?,
-        val newHeight: Int?,
-        val newFileSize: Int
+private data class NewAttachmentAttributes(
+        val newWidth: Int? = 0,
+        val newHeight: Int? = 0,
```
Comment (bmarty) [inline matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/content/UploadContentWorker.kt:53]: Would have defaulted those 2 val to `null`

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/content/UploadContentWorker.kt [hunk 7]
```diff
@@ -48,10 +48,10 @@ import java.io.File
...
+        var newFileSize: Long
```
Comment (bmarty) [inline matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/content/UploadContentWorker.kt:54]: Why not a val?

**Comment by bmarty** [comment]
Thanks @onurays for the update, 2 more comments

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/content/UploadContentWorker.kt (hunk 6 above)
Comment (onurays) [reply matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/content/UploadContentWorker.kt:53]: Done.

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/content/UploadContentWorker.kt (hunk 7 above)
Comment (onurays) [reply matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/content/UploadContentWorker.kt:54]: Because we are changing it (line 209) if api bug occurs.

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/content/UploadContentWorker.kt [hunk 8]
```diff
@@ -154,8 +158,8 @@ internal class UploadContentWorker(val context: Context, params: WorkerParameter
                                 compressedFile.inputStream().use {
                                     val options = BitmapFactory.Options().apply { inJustDecodeBounds = true }
                                     val bitmap = BitmapFactory.decodeStream(it, null, options)
-                                    val fileSize = bitmap?.byteCount ?: 0
-                                    newImageAttributes = NewImageAttributes(
+                                    val fileSize = bitmap?.byteCount?.toLong() ?: compressedFile.length()
```
Comment (bmarty) [inline matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/content/UploadContentWorker.kt:161]: Reading it again, I'm not sure it will be bug free, since the inputStream is still open here.

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/content/UploadContentWorker.kt (hunk 7 above)
Comment (bmarty) [reply matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/content/UploadContentWorker.kt:54]: Please make it a val and use copy() if necessary

Comment (onurays) [reply matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/content/UploadContentWorker.kt:54]: Done.

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/content/UploadContentWorker.kt (hunk 8 above)
Comment (bmarty) [reply matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/content/UploadContentWorker.kt:161]: it's ok, my bad

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/content/UploadContentWorker.kt (hunk 4 above)
Comment (bmarty) [reply matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/content/UploadContentWorker.kt:208]: (reverted to `<=` because sometimes the system returns 0, which is wrong

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/content/UploadContentWorker.kt [hunk 9]
```diff
@@ -306,14 +315,14 @@ internal class UploadContentWorker(val context: Context, params: WorkerParameter
...
                                     thumbnailUrl: String? = null,
                                     thumbnailEncryptedFileInfo: EncryptedFileInfo?,
-                                    newImageAttributes: NewImageAttributes?) {
+                                    newAttachmentAttributes: NewAttachmentAttributes) {
         localEchoRepository.updateEcho(eventId) { _, event ->
             val messageContent: MessageContent? = event.asDomain().content.toModel()
             val updatedContent = when (messageContent) {
-                is MessageImageContent -> messageContent.update(url, encryptedFileInfo, newImageAttributes)
+                is MessageImageContent -> messageContent.update(url, encryptedFileInfo, newAttachmentAttributes)
                 is MessageVideoContent -> messageContent.update(url, encryptedFileInfo, thumbnailUrl, thumbnailEncryptedFileInfo)
```
Comment (bmarty) [inline matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/content/UploadContentWorker.kt:323]: Why not passing newAttachmentAttributes here?

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/content/UploadContentWorker.kt [hunk 10]
```diff
@@ -326,14 +335,14 @@ internal class UploadContentWorker(val context: Context, params: WorkerParameter
...
         return copy(
                 url = if (encryptedFileInfo == null) url else null,
                 encryptedFileInfo = encryptedFileInfo?.copy(url = url),
                 info = info?.copy(
-                        width = newImageAttributes?.newWidth ?: info.width,
-                        height = newImageAttributes?.newHeight ?: info.height,
-                        size = newImageAttributes?.newFileSize ?: info.size
+                        width = newAttachmentAttributes?.newWidth ?: info.width,
+                        height = newAttachmentAttributes?.newHeight ?: info.height,
+                        size = newAttachmentAttributes?.newFileSize?.toInt() ?: info.size
```
Comment (bmarty) [inline matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/content/UploadContentWorker.kt:345]: info.size should probably be a Long instead of Int
