### PR TITLE
Fixing notifications not being dismissed when read from other devices

### LINKED ISSUE #3347: Notification does not vanish if the message is read on another session
- Bob has 2 sessions: one on Element Android, one on Element Web, and share a room with Alice.
- Bob is viewing the room list on Element Android
- Alice sends a message to Bob in room A
- The notification appears on Bob's Android device.
- Bob read the room in his Element Web session
- The notification is still visible to Bob's Android device -> KO

The notification should be cancel on Bob's Android device.

It used to work, so this is regression.

During the while process Element Android is in foreground (so is syncing permanently). If Element Android app goes to background, I'm not sure we will receive a Push to update the read marker of Bob, but it is acceptable in this case.

### PR DESCRIPTION
**Pull request by ouchadam**
Fixes #3347 and #523 

Our notification dismissing works by matching the currently held notification events to the latest timeline chunk for the room, this presents a problem when the next chunk is created which doesn't reference those original notification events, which then presents itself as notifications not being dismissed when read from other sessions.

The fix is to check the existence of missing events against the entire chunk history if there's also a read receipt event in the latest chunk.

- I was able to to reproduce the issue by spamming messages to force the timeline to create a new chunk

Here's the worlds least exciting gif... notice the element icon in the top
| |
| --- |
|after-new-chunk

### CODE REVIEW

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/query/ReadQueries.kt [hunk 1]
```diff
@@ -23,6 +23,9 @@ import org.matrix.android.sdk.internal.database.model.TimelineEventEntity
 import io.realm.Realm
 import io.realm.RealmConfiguration
 
+private const val MARK_OLD_EVENT_AS_READ = true
+private const val MARK_UNREAD_DUE_TO_FASTLANE = false
```
Comment (bmarty) [inline matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/query/ReadQueries.kt:27]: I'm not sure declaring const for boolean returned value increases the readability of the code. Maybe a good comment is better?

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/query/ReadQueries.kt [hunk 2]
```diff
@@ -59,6 +59,25 @@ internal fun isEventRead(realmConfiguration: RealmConfiguration,
...
+        MARK_UNREAD_DUE_TO_FASTLANE
+    }
+}
+
+private fun Realm.doesEventExistInChunkHistory(eventId: String): Boolean {
+    return ChunkEntity.findIncludingEvent(this, eventId) != null
+}
+
+private fun Realm.hasReadReceiptInLatestChunk(latestChunkEntity: ChunkEntity, roomId: String, userId: String) : Boolean {
+    return ReadReceiptEntity.where(this, roomId, userId).findFirst()?.let {
```
Comment (bmarty) [inline matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/query/ReadQueries.kt:76]: Nit: The code is OK, but maybe use named arguments for roomId and userId to avoid confusion, since the types are the same (String)

**Review by bmarty — APPROVED** [review]
That a really good catch, thanks!
I have not tested it, but I understand the idea.
See my 2 small remarks.

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/query/ReadQueries.kt (hunk 2 above)
Comment (ouchadam) [reply matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/query/ReadQueries.kt:76]: :100: will do

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/query/ReadQueries.kt (hunk 1 above)
Comment (ouchadam) [reply matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/query/ReadQueries.kt:27]: :+1: I think this is a sign that the `handleMissingEvent` is the wrong name, renaming to `hasReadMissingEvent` allows us to infer the return result is `has read` or `has not read`

Comment (ouchadam) [reply matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/query/ReadQueries.kt]: 4a51583a7608e8a83add318332d0f3cbab244595

**Review by bmarty — APPROVED** [review]
Thanks for the update! It's more readable to me now!
