### PR TITLE
Feature/fga/fix sdk integration tests

### LINKED ISSUE #4546: Fix integration tests
Lots of integration tests are not passing due to at least those issues:
- Matrix object is not overrode in androidTest source
- Sync is canceled because app is in background (no UI)
- Some timings are not ok when sending lots of messages

### PR DESCRIPTION
**Pull request by ganfra**
This will fix #4546 
All of the tests are not passing yet, but we are progressing.
Most notable stuff is introduction of TestMatrix class and MatrixWorkerFactory.

### CODE REVIEW

File: matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/api/TestMatrix.kt [hunk 1]
```diff
@@ -35,16 +35,16 @@ import org.matrix.android.sdk.internal.SessionManager
...
 import java.util.concurrent.atomic.AtomicBoolean
 import javax.inject.Inject
 
 /**
- * This is the main entry point to the matrix sdk.
- * To get the singleton instance, use getInstance static method.
+ * This mimics the Matrix class but using TestMatrixComponent internally instead of regular MatrixComponent.
  */
-class Matrix private constructor(context: Context, matrixConfiguration: MatrixConfiguration) {
+class TestMatrix constructor(context: Context, matrixConfiguration: MatrixConfiguration) {
```
Comment (bmarty) [inline matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/api/TestMatrix.kt:47]: Shouldn't it be `internal`?

File: matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/session/space/SpaceCreationTest.kt [hunk 2]
```diff
@@ -57,11 +55,9 @@ class SpaceCreationTest : InstrumentedTest {
         val topic = "A public space for test"
         var spaceId: String = ""
         commonTestHelper.waitWithLatch {
-            GlobalScope.launch {
```
Comment (bmarty) [inline matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/session/space/SpaceCreationTest.kt:60]: Since you are not using GlobalScope anymore, `@Suppress("EXPERIMENTAL_API_USAGE")` can be removed. There are maybe other places in the PR.

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/SyncTokenStore.kt [hunk 3]
```diff
@@ -25,13 +25,18 @@ import javax.inject.Inject
 internal class SyncTokenStore @Inject constructor(@SessionDatabase private val monarchy: Monarchy) {
 
     fun getLastToken(): String? {
-        return Realm.getInstance(monarchy.realmConfiguration).use {
+        val token = Realm.getInstance(monarchy.realmConfiguration).use {
+            // Makes sure realm is up-to-date as it's used for querying internally on non looper thread.
+            it.refresh()
```
Comment (bmarty) [inline matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/SyncTokenStore.kt:30]: Will it fix the notification about init sync not displayed after a clear cache? (not sure there is an existing issue about that)

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/SyncTokenStore.kt [hunk 4]
```diff
@@ -25,13 +25,18 @@ import javax.inject.Inject
...
             it.where(SyncEntity::class.java).findFirst()?.nextBatch
         }
+        return token
     }
 
     fun saveToken(realm: Realm, token: String?) {
-        val sync = SyncEntity(token)
-        realm.insertOrUpdate(sync)
+        if (realm.isInTransaction) {
```
Comment (bmarty) [inline matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/SyncTokenStore.kt:37]: it should always be the case, no? Else shouldn't we do something like crashing the app for instance?

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/util/BackgroundDetectionObserver.kt [hunk 5]
```diff
@@ -52,9 +58,16 @@ internal class BackgroundDetectionObserver @Inject constructor() : DefaultLifecy
...
+}
 
-    interface Listener {
-        fun onMoveToForeground()
-        fun onMoveToBackground()
-    }
+/**
+ * Force foreground for testing
+ */
+internal class TestBackgroundDetectionObserver : BackgroundDetectionObserver {
```
Comment (bmarty) [inline matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/util/BackgroundDetectionObserver.kt:66]: Maybe extract to its own file

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/worker/MatrixWorkerFactory.kt [hunk 6]
```diff
@@ -20,25 +20,64 @@ import android.content.Context
...
+                SendVerificationMessageWorker(appContext, workerParameters, sessionManager)
+            SyncWorker::class.java.name                           ->
+                SyncWorker(appContext, workerParameters, sessionManager)
+            UpdateTrustWorker::class.java.name                    ->
+                UpdateTrustWorker(appContext, workerParameters, sessionManager)
+            UploadContentWorker::class.java.name                  ->
+                UploadContentWorker(appContext, workerParameters, sessionManager)
+            else                                                  ->
+                // Return null to delegate to the default WorkerFactory.
+                null
```
Comment (bmarty) [inline matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/worker/MatrixWorkerFactory.kt:80]: Maybe log a warning for the developers, if they forget to add their new worker instanciation above?

**Review by bmarty — COMMENTED** [review]
Some remarks. Also:
- Please check the CI
- Add a file for the changelog
- Thanks!

**Comment by bmarty** [comment]
Also for big 1d9da6c7d3e7fdc619d2b20c483881e6646ea708 next time please do separate commits to split renaming of members, and more impactful changes, it will ease the review. Thanks!

File: matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/api/TestMatrix.kt (hunk 1 above)
Comment (ganfra) [reply matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/api/TestMatrix.kt:47]: it's in androidTest package so not needed I guess

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/SyncTokenStore.kt (hunk 4 above)
Comment (ganfra) [reply matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/SyncTokenStore.kt:37]: oh yes sorry, miss from testing

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/util/BackgroundDetectionObserver.kt (hunk 5 above)
Comment (ganfra) [reply matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/util/BackgroundDetectionObserver.kt:66]: ok

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/worker/MatrixWorkerFactory.kt (hunk 6 above)
Comment (ganfra) [reply matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/worker/MatrixWorkerFactory.kt:80]: Yes good point

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/di/WorkManagerProvider.kt [hunk 7]
```diff
@@ -60,6 +74,27 @@ internal class WorkManagerProvider @Inject constructor(
...
+            workManager.enqueue(checkWorkerRequest)
+            val checkWorkerLiveState = workManager.getWorkInfoByIdLiveData(checkWorkerRequest.id)
+            val observer = object : Observer<WorkInfo> {
+                override fun onChanged(workInfo: WorkInfo) {
+                    if (workInfo.state.isFinished) {
+                        checkWorkerLiveState.removeObserver(this)
+                        if (workInfo.state == WorkInfo.State.FAILED) {
+                            throw RuntimeException("MatrixWorkerFactory is not being set on your worker configuration.\n" +
+                                    "Makes sure to add it to a DelegatingWorkerFactory if you have your own factory or use it directly.\n" +
+                                    "You can grab the instance through the Matrix class.")
```
Comment (bmarty) [inline matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/di/WorkManagerProvider.kt:89]: The message is maybe a bit hard to understand (to me at least) :/. I cannot propose better though, but maybe add a link to the Element code where it's done?

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/worker/MatrixWorkerFactory.kt [hunk 8]
```diff
@@ -75,9 +78,29 @@ internal class MatrixWorkerFactory @Inject constructor(private val sessionManage
...
+                Timber.w("No worker defined on MatrixWorkerFactory for $workerClassName will delegate to default.")
                 // Return null to delegate to the default WorkerFactory.
                 null
+            }
+        }
+    }
+
+    /**
+     * This worker is launched by the factory with the isCreatedByMatrixWorkerFactory flag to true.
+     * If the MatrixWorkerFactory is not set up, it will default to the other constructor and it will throw
```
Comment (bmarty) [inline matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/worker/MatrixWorkerFactory.kt:91]: it will not throw but it will fail :)

**Review by bmarty — APPROVED** [review]
LGTM, 2 small remarks but no blockers

File: matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/api/TestMatrix.kt [hunk 9]
```diff
@@ -44,7 +44,7 @@ import javax.inject.Inject
 /**
  * This mimics the Matrix class but using TestMatrixComponent internally instead of regular MatrixComponent.
  */
-class TestMatrix constructor(context: Context, matrixConfiguration: MatrixConfiguration) {
+internal class TestMatrix constructor(context: Context, matrixConfiguration: MatrixConfiguration) {
```
Comment (bmarty) [inline matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/api/TestMatrix.kt:47]: I told you!

Comment (bmarty) [reply matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/api/TestMatrix.kt:47]: CI does not like this change though. I think some other test classes have to be declared internal

**Review by bmarty — APPROVED** [review]
Thanks for the update
