### PR TITLE
Feature/fix send room v6

### LINKED ISSUE #1879: Uploads still don't work with room v6
This is a duplicate of #1558 and #363, but those are closed. The original issue is not fixed, build G-b3395 still sends floats:

```
2020-08-05 15:21:40,949 - synapse.http.server - 74 - INFO - PUT-1025098- <XForwardedForRequest at 0x7fe21aecfcc0 method='PUT' uri='/_matrix/client/r0/rooms/!EgoVrPyOnPSVXERlxj:gruenhage.xyz/send/m.room.message/$local.5c720e50-9523-4594-a666-20b063111cdb' clientproto='HTTP/1.1' site=8008> SynapseError: 400 - Bad JSON value: float
2020-08-05 15:21:40,949 - synapse.access.http.8008 - 310 - INFO - PUT-1025098- 172.19.0.1 - 8008 - {@tulir:maunium.net} Processed request: 0.011sec/0.000sec (0.004sec, 0.000sec) (0.000sec/0.005sec/2) 56B 400 "PUT /_matrix/client/r0/rooms/!EgoVrPyOnPSVXERlxj:gruenhage.xyz/send/m.room.message/$local.5c720e50-9523-4594-a666-20b063111cdb HTTP/1.1" "Element dbg/1.0.5-dev (Linux; U; Android 10; CLT-L29 Build/HUAWEICLT-L2; Flavour GooglePlay; MatrixAndroidSDK_X 0.0.1)" [0 dbevts]
```

image

### PR DESCRIPTION
**Pull request by ganfra**
This should fix #1879
Please try to be sure I didn't miss anything this time.

### CODE REVIEW

**Review by bmarty — APPROVED** [review]
LGTM (static review)

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/SendEventWorker.kt [hunk 1]
```diff
@@ -47,12 +47,10 @@ internal class SendEventWorker(context: Context,
     @JsonClass(generateAdapter = true)
     internal data class Params(
             override val sessionId: String,
-            // TODO remove after some time, it's used for compat
             val event: Event? = null,
             val eventId: String? = null,
             val roomId: String? = null,
             val type: String? = null,
-            val contentStr: String? = null,
```
Comment (bmarty) [inline matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/SendEventWorker.kt:55]: Maybe keep it for the moment during the migration?

Comment (ganfra) [reply matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/SendEventWorker.kt:55]: It won't crash as it's not mandatory, so I think it's OK
