### PR TITLE
Show a loader if all the Room Member are not yet loaded.

### LINKED ISSUE #6393: RoomMemberList can display limited number of user
### Steps to reproduce

1. Perform an Init sync
2. Join a public room with a large number of users
3. Go fast to the room member list of this room

#### What did you expect?

See all the members of the room, or if all the members are not yet loaded, see a loader

#### What happened instead?

Only the know users are displayed, and after a while the list is updated with all the members.

The whole room members list is loaded when the user open the timeline. This is due to the lazy loading of the room member.

The Matrix SDK knows that all the members are not yet loaded, but this information does not go to the UI, the no loader can be displayed. This has to be changed too.

### Your phone model

any

### Operating system version

any

### Application version and app store

1.4.25 and lower

### Homeserver

any supporting lazy loading of room members

### Will you send logs?

No

### Are you willing to provide a PR?

No

### PR DESCRIPTION
**Pull request by bmarty**
## Type of change

- [x] Feature
- [ ] Bugfix
- [ ] Technical
- [ ] Other :

## Content

Add a loader to let the user know that all the members are not yet loaded.

## Motivation and context

Fix #6393 

## Screenshots / GIFs

RoomMembersWithLoader

## Tests

- Join a room with lots of people (> 1000)
- Open the room member list of this room

## Tested devices

- [x] Physical
- [ ] Emulator
- OS version(s):

## Checklist

- [ ] Changes has been tested on an Android device or Android emulator with API 21
- [ ] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#accessibility
- [ ] Pull request is based on the develop branch
- [ ] Pull request includes a new file under ./changelog.d. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#changelog
- [ ] Pull request includes screenshots or videos if containing UI changes
- [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [ ] You've made a self review of your PR
- [ ] If you have modified the screen flow, or added new screens to the application, you have updated the test [UiAllScreensSanityTest.allScreensTest()](https://github.com/vector-im/element-android/blob/main/vector/src/androidTest/java/im/vector/app/ui/UiAllScreensSanityTest.kt#L73)

### CODE REVIEW

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/members/MembershipService.kt [hunk 1]
```diff
@@ -30,6 +31,20 @@ interface MembershipService {
...
+     * event to the room.
+     * The fun let the app know if all the members have been loaded for this room.
+     * @return true if all the members are loaded, or false elsewhere.
+     */
+    suspend fun areAllMembersLoaded(): Boolean
+
+    /**
+     * Live version for [areAllMembersLoaded].
+     */
+    fun areAllMembersLoadedLive(): LiveData<Optional<Boolean>>
```
Comment (mnaturel) [inline matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/members/MembershipService.kt:46]: Should we annotate the method with `@MainThread` as in the implementation `Monarchy` will crash if it is not called from main thread?

**Review by mnaturel — APPROVED** [review]
LGTM, I have just small remarks as suggestions.

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/members/MembershipService.kt (hunk 1 above)
Comment (bmarty) [reply matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/members/MembershipService.kt]: I think all methods that return `LiveData` has to be called from the main thread, no?

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/membership/GetRoomMembersLoadStatusTask.kt [hunk 2]
```diff
@@ -0,0 +1,45 @@
...
+import org.matrix.android.sdk.internal.task.Task
+import javax.inject.Inject
+
+internal interface GetRoomMembersLoadStatusTask : Task<GetRoomMembersLoadStatusTask.Params, RoomMembersLoadStatusType> {
+    data class Params(
+            val roomId: String,
+    )
+}
+
+internal class DefaultGetRoomMembersLoadStatusTask @Inject constructor(
```
[the remark this answers is not in the document]
Comment (bmarty) [reply matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/membership/GetRoomMembersLoadStatusTask.kt]: I have changed to a `RoomDataSource`, it's more appropriate. I will check how we can test that.

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/members/MembershipService.kt (hunk 1 above)
Comment (mnaturel) [reply matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/members/MembershipService.kt]: Indeed I guess, I commented on the wrong method, sorry. My comment was for a method exposing a `Flow` relying internally on a `LiveData` like in `FlowRoom`. `Flow` collection is normally not constraint to main thread and it can be surprising if we don't look at the implementation.

**Comment by bmarty** [comment]
I have fixed ktlint issue, no need to wait for the CI to check everything again.
