### PR TITLE
Non dismissing notifications

### LINKED ISSUE #4505: Notifications are not dismissed when app is killed by the system are then interacted with
### Steps to reproduce

1. Receive a notification
2. Stop the app by swiping it away from the recents menu (or have a battery/memory optimisation stop the app) 
3. Interact with the notification (mark as read, or tapping to enter the room)
4. The action happens but the notification is still shown

#### What did you expect?
The notification to be automatically dismissed

#### What happened instead?
The notification is still show

### Your phone model

_No response_

### Operating system version

_No response_

### Application version and app store

1.3.6+

### Homeserver

_No response_

### Will you send logs?

No

### PR DESCRIPTION
**Pull request by ouchadam**
Fixes #4505 Notifications not automatically dismissing, this is caused by the in memory tracking being out of sync.

The most likely trigger of this issue is the android OS reclaiming memory and killing the Element app whilst it's idle in the background (which is perfectly normal)  

- The loading of the persisted events was happening before the current session was active which meant we weren't able to read any previously persisted events.
- Preloads the in memory cache of rendered events with the last known persisted events (this fixes the original issue)
- Persists the event queue every time we receive a new event instead of when the app moves to the background, this allows us to handle crash cashes where the app doesn't gracefully move to the background 
- Also extracts out the `NotificationState` and persistence to their own classes/files

| BEFORE | AFTER | 
| --- | --- |
|before-notifications-staying|after-dismiss-notification

### CODE REVIEW

File: vector/src/main/java/im/vector/app/features/notifications/NotificationDrawerManager.kt [hunk 1]
```diff
@@ -171,85 +149,43 @@ class NotificationDrawerManager @Inject constructor(private val context: Context
...
-            val myUserDisplayName = user?.toMatrixItem()?.getBestName() ?: session.myUserId
-            val myUserAvatarUrl = session.contentUrlResolver().resolveThumbnail(
-                    contentUrl = user?.avatarUrl,
-                    width = avatarSize,
-                    height = avatarSize,
-                    method = ContentUrlResolver.ThumbnailMethod.SCALE
-            )
-            notificationRenderer.render(session.myUserId, myUserDisplayName, myUserAvatarUrl, useCompleteNotificationFormat, eventsToRender)
+            renderEvents(session, eventsToRender)
+            notificationState.persist(context, session)
```
Comment (ouchadam) [inline vector/src/main/java/im/vector/app/features/notifications/NotificationDrawerManager.kt:164]: whilst on the worker thread we persist the queue each time we process new events

File: vector/src/main/java/im/vector/app/features/notifications/NotificationDrawerManager.kt [hunk 2]
```diff
@@ -50,42 +48,24 @@ class NotificationDrawerManager @Inject constructor(private val context: Context
...
+        get() = activeSessionDataSource.currentValue?.orNull()
 
     /**
-     * The last known rendered notifiable events
-     * we keep track of them in order to know which events have been removed from the eventList
-     * allowing us to cancel any notifications previous displayed by now removed events
+     * Lazily initializes the NotificationState as we rely on having a current session in order to fetch the persisted queue of events
      */
-    private var renderedEvents = emptyList<ProcessedEvent<NotifiableEvent>>()
+    private val notificationState by lazy { NotificationState.createInitialNotificationState(context, currentSession) }
```
Comment (ouchadam) [inline vector/src/main/java/im/vector/app/features/notifications/NotificationDrawerManager.kt:58]: not sure if the preloading was working in the past :thinking:  we have to wait for an active session before we can query for the previously persisted events

File: vector/src/main/java/im/vector/app/features/notifications/NotificationEventPersistence.kt [hunk 3]
```diff
@@ -0,0 +1,72 @@
...
+import org.matrix.android.sdk.api.session.Session
+import timber.log.Timber
+import java.io.File
+import java.io.FileOutputStream
+
+// TODO Multi-account
+private const val ROOMS_NOTIFICATIONS_FILE_NAME = "im.vector.notifications.cache"
+private const val KEY_ALIAS_SECRET_STORAGE = "notificationMgr"
+
+object NotificationEventPersistence {
```
Comment (bmarty) [inline vector/src/main/java/im/vector/app/features/notifications/NotificationEventPersistence.kt:29]: Is is possible to inject the constructor with the context to simplify the API?

File: vector/src/main/java/im/vector/app/features/notifications/NotificationEventQueue.kt [hunk 4]
```diff
@@ -19,7 +19,14 @@ package im.vector.app.features.notifications
 import timber.log.Timber
 
 class NotificationEventQueue(
-        private val queue: MutableList<NotifiableEvent> = mutableListOf()
+        private val queue: MutableList<NotifiableEvent> = mutableListOf(),
```
Comment (bmarty) [inline vector/src/main/java/im/vector/app/features/notifications/NotificationEventQueue.kt:22]: I'm wondering why `NotificationEventQueue` is not a data class, also why `queue` has default value and `seenEventIds` does not.

**Review by bmarty — COMMENTED** [review]
LGTM, did not test it though. Some small remarks.

File: vector/src/main/java/im/vector/app/features/notifications/NotificationEventPersistence.kt (hunk 3 above)
Comment (ouchadam) [reply vector/src/main/java/im/vector/app/features/notifications/NotificationEventPersistence.kt:29]: will do :+1: it will mean passing the `persistence` into the `NotificationState` methods that use it or lifting those interactions back to the `NotificationManagerDrawer`

File: vector/src/main/java/im/vector/app/features/notifications/NotificationEventQueue.kt (hunk 4 above)
Comment (ouchadam) [reply vector/src/main/java/im/vector/app/features/notifications/NotificationEventQueue.kt:22]: my original thinking was because the `NotificationEventQueue` is acting as a wrapper around the `List<NotifiableEvent>` and that consumers would use the `rawEvents` for exporting the content instead of comparing equality against the  `NotificationEventQueue` directly

now that you've mentioned it... I can't think any reason not to make it a data class, will change and will also remove the default value to keep all the initialisation in one place :+1:

File: vector/src/main/java/im/vector/app/features/notifications/NotificationEventPersistence.kt (hunk 3 above)
Comment (ouchadam) [reply vector/src/main/java/im/vector/app/features/notifications/NotificationEventPersistence.kt]: done https://github.com/vector-im/element-android/pull/4506/commits/7693f3bc6c7607ade8015838e0cbfaf3bdc1160f

File: vector/src/main/java/im/vector/app/features/notifications/NotificationEventQueue.kt (hunk 4 above)
Comment (ouchadam) [reply vector/src/main/java/im/vector/app/features/notifications/NotificationEventQueue.kt]: done https://github.com/vector-im/element-android/pull/4506/commits/55fd362b3d7fbc8d3806c5e4bafaab99bb14c703

**Review by bmarty — APPROVED** [review]
Thanks for the update. Looks great!
