### PR TITLE
FTUE - Fix trusting certificates during edit server flow

### LINKED ISSUE #6864: Private CA issue
### Steps to reproduce

1. It started with the last release, when the login interface changed on android. (until 1.4.27 was working)
2. When I choose  the server it appears the usual "Trust the certiicate?" I say Yes but I cannot go further
3. If you did not log out you can update Element with no issue

#### What did you expect?
When I choose  the server it appears the usual "Trust the certiicate?" I say Yes but I cannot go further
#### What happened instead?
I cannot go further and it keep asking "Trust Certificate?"

### Your phone model

_No response_

### Operating system version

Android 11

### Application version and app store

Element 1.4.32

### Homeserver

matrix-synapse last stable release with private CA

### Will you send logs?

No

### Are you willing to provide a PR?

No

### PR DESCRIPTION
**Pull request by ouchadam**
## Type of change

- [ ] Feature
- [x] Bugfix
- [ ] Technical
- [ ] Other :

## Content

- Includes the `EditHomeserver` flow when handling certificate trusting
- Removes the mutable `HomeserverConfig` state in favour of recreating when needed (when trusting the certificate) which massively simplifies the unit testing setup
- Supplies a `retryAction` when creating the `CertificateError`, avoids needing _non persisted_ mutable state in the view model and reduces unit test setup 

## Motivation and context

Fixes #6864  - Certificate trusting during the edit homeserver flow doing nothing

## Screenshots / GIFs

|Before|After|
|-|-|
|before-trust-server-ca|after-allow-trusting-ca-during-edits|

## Tests

- Set your device time to the past (to cause the certificate to become invalid)
- Whilst signed out, enter the `I already have an account` flow
- Tap `EDIT`
- Tap `next` with `matrix.org` selected
- Notice the certificate trust dialog, tap next and nothing happens

## Tested devices

- [ ] Physical
- [x] Emulator
- OS version(s): 31

### CODE REVIEW

File: vector/src/main/java/im/vector/app/features/onboarding/OnboardingViewModel.kt [hunk 1]
```diff
@@ -276,20 +270,13 @@ class OnboardingViewModel @AssistedInject constructor(
...
         // It happens when we get the login flow, or during direct authentication.
         // So alter the homeserver config and retrieve again the login flow
-        when (val finalLastAction = lastAction) {
-            is OnboardingAction.HomeServerChange.SelectHomeServer -> {
-                currentHomeServerConnectionConfig
-                        ?.let { it.copy(allowedFingerprints = it.allowedFingerprints + action.fingerprint) }
-                        ?.let { startAuthenticationFlow(finalLastAction, it, serverTypeOverride = null) }
-            }
+        when (action.retryAction) {
+            is OnboardingAction.HomeServerChange -> handleHomeserverChange(action.retryAction, fingerprint = action.fingerprint)
```
Comment (ouchadam) [inline vector/src/main/java/im/vector/app/features/onboarding/OnboardingViewModel.kt:274]: `is OnboardingAction.HomeServerChange.SelectHomeServer` to `is OnboardingAction.HomeServerChange` is the fix, the other changes are refactors to enable unit testing the change

File: vector/src/main/java/im/vector/app/features/onboarding/OnboardingViewModel.kt [hunk 2]
```diff
@@ -276,20 +270,13 @@ class OnboardingViewModel @AssistedInject constructor(
...
                 handleDirectLogin(
-                        finalLastAction,
-                        HomeServerConnectionConfig.Builder()
-                                // Will be replaced by the task
-                                .withHomeServerUri("https://dummy.org")
-                                .withAllowedFingerPrints(listOf(action.fingerprint))
-                                .build()
+                        action.retryAction,
+                        // Will be replaced by the task
+                        homeServerConnectionConfigFactory.create("https://dummy.org", action.fingerprint)
```
Comment (ouchadam) [inline vector/src/main/java/im/vector/app/features/onboarding/OnboardingViewModel.kt:279]: reuses the `factory` to avoid directly interacting with android's `Uri` and making the change untestable without further refactors

File: vector/src/main/java/im/vector/app/features/onboarding/OnboardingViewModel.kt [hunk 3]
```diff
@@ -589,9 +576,19 @@ class OnboardingViewModel @AssistedInject constructor(
         currentJob = viewModelScope.launch {
             directLoginUseCase.execute(action, homeServerConnectionConfig).fold(
                     onSuccess = { onSessionCreated(it, authenticationDescription = AuthenticationDescription.Login) },
-                    onFailure = {
+                    onFailure = { error ->
                         setState { copy(isLoading = false) }
-                        _viewEvents.post(OnboardingViewEvents.Failure(it))
+                        when {
+                            error.isUnrecognisedCertificate() -> {
```
Comment (ouchadam) [inline vector/src/main/java/im/vector/app/features/onboarding/OnboardingViewModel.kt:582]: adding a dedicated `unrecognised certificate` case with retry action is the fix

**Review by fedrunov — APPROVED** [review]
LGTM
