### PR TITLE
Unable to change avatar due to `NetworkOnMainThread`

### LINKED ISSUE #4767: It is not possiable to changing user  avatar
### Steps to reproduce

It is not possiable to changing user  avatar
image
image
cut and uploading photo
image
image

### Outcome

final Exception：android.os.NetworkOnMainThreadException
image
image

### Your phone model

18208727060

### Operating system version

Android 31

### Application version and app store

_No response_

### Homeserver

https://im.ynzzpt.cn/

### Will you send logs?

Yes

### PR DESCRIPTION
**Pull request by ouchadam**
Fixes #4767 Unable to change avatar

We had a report of `NetworkOnMainThread` whilst changing avatar, I've been unable to reproduce the issue but did notice we have an unnecessary main thread dispatcher being used (looks like it was introduced as part of the suspend migration).

- Switches the `main` dispatcher to `io`, the user has also confirmed this fixed their issue
- Bundles the file reading + temp file creation into the same io context 

| |
| --- |
|changing-avatar

### CODE REVIEW

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/profile/DefaultProfileService.kt [hunk 1]
```diff
@@ -68,7 +68,7 @@ internal class DefaultProfileService @Inject constructor(private val taskExecuto
     }
 
     override suspend fun updateAvatar(userId: String, newAvatarUri: Uri, fileName: String) {
-        withContext(coroutineDispatchers.main) {
+        withContext(coroutineDispatchers.io) {
```
Comment (ouchadam) [inline matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/profile/DefaultProfileService.kt:71]: this is the fix

Comment (ganfra) [reply matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/profile/DefaultProfileService.kt:71]: Its something we already had fixed, not sure why its back. But fileUploader should already dispatch on a background thread, its weird

Comment (ouchadam) [reply matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/profile/DefaultProfileService.kt:71]: yeah it's very strange, I checked the okhttp thread pool/interceptors as well, couldn't find any cases where the main thread was being used, unless on some devices the okhttp thread uses the main thread/looper for some reason :thinking:

**Review by ganfra — APPROVED** [review]
Thanks!

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/profile/DefaultProfileService.kt (hunk 1 above)
Comment (bmarty) [reply matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/profile/DefaultProfileService.kt:71]: This is also something which has been fixed by some fork on their side FWIW.

**Review by bmarty — APPROVED** [review]
