### PR TITLE
Show low priority rooms in dm

### LINKED ISSUE #3463: Low priority does nothing for DMs
#### Describe the bug
If you mark a room as low priority, it's moved into under the low priority header at the bottom, separate from the non-low priority rooms. In Element-web, low-priority DMs are also moved to the same place. In Element-Android however, marking a DM as low priority doesn't do anything; low priority DMs are still mixed in with the regular priority DMs.

#### Smartphone (please complete the following information):
 - Device: Oneplus 8T
 - OS: Android 11

#### Additional context
 - App version and store: 1.1.8 - Google Play
 - Homeserver: Self hosted

### PR DESCRIPTION
**Pull request by bmarty**
Fixes #3463:

image

Also some cleanup, I hope I did not break anything. Can you check @BillCarsonFr ?

### CODE REVIEW

File: vector/src/main/java/im/vector/app/features/home/room/list/RoomListViewModel.kt [hunk 1]
```diff
@@ -120,40 +120,34 @@ class RoomListViewModel @Inject constructor(
...
-                    appStateHandler,
-                    autoAcceptInvites,
-                    {
-                        it.disposeOnClear()
-                    },
-                    {
-                        updatableQuery = it
-                    }
-            ).buildSections(initialState.displayMode)
+    private val roomListSectionBuilder = if (appStateHandler.getCurrentRoomGroupingMethod() is RoomGroupingMethod.BySpace) {
```
Comment (bmarty) [inline vector/src/main/java/im/vector/app/features/home/room/list/RoomListViewModel.kt:123]: no more `lazy {}` block here, is it OK @BillCarsonFr ?

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/RoomSummaryQueryParams.kt [hunk 2]
```diff
@@ -39,12 +39,6 @@ fun spaceSummaryQueryParams(init: (RoomSummaryQueryParams.Builder.() -> Unit) =
             .build()
 }
 
-enum class RoomCategoryFilter {
-    ONLY_DM,
-    ONLY_ROOMS,
-    ALL
-}
```
Comment (bmarty) [inline matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/RoomSummaryQueryParams.kt:46]: it was not used

Comment (BillCarsonFr) [reply matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/RoomSummaryQueryParams.kt:46]: Oh strange, was extracted to a top level class but this did stay...

File: vector/src/main/java/im/vector/app/features/home/room/list/RoomListViewModel.kt (hunk 1 above)
Comment (BillCarsonFr) [reply vector/src/main/java/im/vector/app/features/home/room/list/RoomListViewModel.kt:123]: I wanted to avoid setting that up in the viewModel init, I think it's better to avoid doing work in constructor. Can it stay lazy?

Comment (bmarty) [reply vector/src/main/java/im/vector/app/features/home/room/list/RoomListViewModel.kt:123]: OK

Comment (BillCarsonFr) [reply vector/src/main/java/im/vector/app/features/home/room/list/RoomListViewModel.kt:123]: yes

**Review by BillCarsonFr — APPROVED** [review]
