### PR TITLE
Fix lockscreen's 'device locked' crash on Android 12 and 12L devices

### LINKED ISSUE #6768: Crash - KeyStoreCrypto.ensureKey - java.security.InvalidKeyException
```
Exception java.security.InvalidKeyException
```

```
Exception java.security.InvalidKeyException: Keystore operation failed
  at android.security.keystore2.KeyStoreCryptoOperationUtils.getInvalidKeyException (KeyStoreCryptoOperationUtils.java:130)
  at android.security.keystore2.KeyStoreCryptoOperationUtils.getExceptionForCipherInit (KeyStoreCryptoOperationUtils.java:154)
  at android.security.keystore2.AndroidKeyStoreCipherSpiBase.ensureKeystoreOperationInitialized (AndroidKeyStoreCipherSpiBase.java:339)
  at android.security.keystore2.AndroidKeyStoreCipherSpiBase.engineInit (AndroidKeyStoreCipherSpiBase.java:171)
  at javax.crypto.Cipher.tryTransformWithProvider (Cipher.java:2985)
  at javax.crypto.Cipher.tryCombinations (Cipher.java:2892)
  at javax.crypto.Cipher$SpiAndProviderUpdater.updateAndGetSpiAndProvider (Cipher.java:2797)
  at javax.crypto.Cipher.chooseProvider (Cipher.java:774)
  at javax.crypto.Cipher.init (Cipher.java:1144)
  at javax.crypto.Cipher.init (Cipher.java:1085)
  at org.matrix.android.sdk.api.securestorage.SecretStoringUtils.getEncryptCipher (SecretStoringUtils.kt:6)
  at im.vector.app.features.pin.lockscreen.crypto.KeyStoreCrypto.ensureKey (KeyStoreCrypto.kt:2)
  at im.vector.app.features.pin.lockscreen.crypto.KeyStoreCrypto.hasValidKey (KeyStoreCrypto.kt:3)
  at im.vector.app.features.pin.lockscreen.crypto.LockScreenKeyRepository.isSystemKeyValid (LockScreenKeyRepository.kt:1)
  at im.vector.app.features.pin.lockscreen.biometrics.BiometricHelper.isSystemKeyValid (BiometricHelper.kt:1)
  at im.vector.app.features.pin.lockscreen.biometrics.BiometricHelper.isSystemAuthEnabledAndValid (BiometricHelper.kt:1)
  at im.vector.app.features.pin.lockscreen.ui.LockScreenViewModel.updateStateWithBiometricInfo (LockScreenViewModel.kt:4)
  at im.vector.app.features.pin.lockscreen.ui.LockScreenViewModel.updateConfiguration (LockScreenViewModel.kt:2)
  at im.vector.app.features.pin.lockscreen.ui.LockScreenViewModel.access$updateConfiguration (LockScreenViewModel.kt:1)
  at im.vector.app.features.pin.lockscreen.ui.LockScreenViewModel$2.invokeSuspend (LockScreenViewModel.kt:1)
  at im.vector.app.features.pin.lockscreen.ui.LockScreenViewModel$2.invoke
  at im.vector.app.features.pin.lockscreen.ui.LockScreenViewModel$2.invoke
  at kotlinx.coroutines.flow.FlowKt__TransformKt$onEach$$inlined$unsafeTransform$1$2.emit (Emitters.kt:6)
  at kotlinx.coroutines.flow.StateFlowImpl.collect (StateFlow.kt:12)
  at kotlinx.coroutines.flow.FlowKt__TransformKt$onEach$$inlined$unsafeTransform$1.collect (SafeCollector.common.kt:1)
  at kotlinx.coroutines.flow.FlowKt.collect
  at kotlinx.coroutines.flow.FlowKt__CollectKt$launchIn$1.invokeSuspend (Collect.kt:5)
  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith (ContinuationImpl.kt:3)
  at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith (DispatchedContinuation.kt:24)
  at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable (Cancellable.kt:3)
  at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default (Cancellable.kt:1)
  at kotlinx.coroutines.CoroutineStart.invoke (CoroutineStart.kt:28)
  at kotlinx.coroutines.BuildersKt.launch
  at kotlinx.coroutines.BuildersKt.launch$default
  at kotlinx.coroutines.flow.FlowKt.launchIn
  at im.vector.app.features.pin.lockscreen.ui.LockScreenViewModel.<init> (LockScreenViewModel.kt:12)
  at im.vector.app.DaggerVectorApplication_HiltComponents_SingletonC$MavericksViewModelCImpl$SwitchingProvider$1.create (DaggerVectorApplication_HiltComponents_SingletonC.java:14)
  at im.vector.app.core.di.HiltMavericksViewModelFactory.create (HiltMavericksViewModelFactory.kt:6)
  at im.vector.app.features.pin.lockscreen.ui.LockScreenViewModel$Companion.create
  at im.vector.app.features.pin.lockscreen.ui.LockScreenViewModel$Companion.create (LockScreenViewModel.kt:1)
  at java.lang.reflect.Method.invoke
  at com.airbnb.mvrx.MavericksFactory.create (MavericksFactory.kt:12)
  at androidx.lifecycle.ViewModelProvider$Factory$-CC.$default$create (ViewModelProvider.kt:2)
  at com.airbnb.mvrx.MavericksViewModelProvider.get$default (MavericksViewModelProvider.kt:39)
  at im.vector.app.features.pin.lockscreen.ui.LockScreenFragment$special$$inlined$fragmentViewModel$default$1.invoke (MavericksExtensions.kt:10)
  at im.vector.app.features.pin.lockscreen.ui.LockScreenFragment$special$$inlined$fragmentViewModel$default$1.invoke (MavericksExtensions.kt:1)
  at com.airbnb.mvrx.DefaultViewModelDelegateFactory$createLazyViewModel$1.invoke (ViewModelDelegateProvider.kt:2)
  at com.airbnb.mvrx.DefaultViewModelDelegateFactory$createLazyViewModel$1.invoke (ViewModelDelegateProvider.kt:1)
  at com.airbnb.mvrx.lifecycleAwareLazy.getValue (lifecycleAwareLazy.kt:5)
  at com.airbnb.mvrx.lifecycleAwareLazy$initializeWhenCreated$1.onCreate (lifecycleAwareLazy.kt:1)
  at androidx.lifecycle.FullLifecycleObserverAdapter.onStateChanged (FullLifecycleObserverAdapter.java:8)
  at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent (LifecycleRegistry.java:3)
  at androidx.lifecycle.LifecycleRegistry.sync (LifecycleRegistry.java:45)
  at androidx.lifecycle.LifecycleRegistry.moveToState (LifecycleRegistry.java:7)
  at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent (LifecycleRegistry.java:2)
  at androidx.fragment.app.Fragment.performCreate (Fragment.java:9)
  at androidx.fragment.app.FragmentStateManager.create (FragmentStateManager.java:5)
  at androidx.fragment.app.FragmentStateManager.moveToExpectedState (FragmentStateManager.java:28)
  at androidx.fragment.app.FragmentManager.executeOpsTogether (FragmentManager.java:122)
  at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute (FragmentManager.java:9)
  at androidx.fragment.app.FragmentManager.execPendingActions (FragmentManager.java:14)
  at androidx.fragment.app.FragmentManager.dispatchStateChange (FragmentManager.java:10)
  at androidx.fragment.app.FragmentActivity.onStart (FragmentActivity.java:12)
  at androidx.appcompat.app.AppCompatActivity.onStart (AppCompatActivity.java:1)
  at android.app.Instrumentation.callActivityOnStart (Instrumentation.java:1467)
  at android.app.Activity.performStart (Activity.java:8082)
  at android.app.ActivityThread.handleStartActivity (ActivityThread.java:3732)
  at android.app.servertransaction.TransactionExecutor.performLifecycleSequence (TransactionExecutor.java:221)
  at android.app.servertransaction.TransactionExecutor.cycleToPath (TransactionExecutor.java:201)
  at android.app.servertransaction.TransactionExecutor.executeLifecycleState (TransactionExecutor.java:173)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:97)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2253)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loopOnce (Looper.java:201)
  at android.os.Looper.loop (Looper.java:288)
  at android.app.ActivityThread.main (ActivityThread.java:7870)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:548)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1003)
Caused by android.security.KeyStoreException: Device locked
  at android.security.KeyStore2.getKeyStoreException (KeyStore2.java:356)
  at android.security.KeyStoreSecurityLevel.createOperation (KeyStoreSecurityLevel.java:120)
  at android.security.keystore2.AndroidKeyStoreCipherSpiBase.ensureKeystoreOperationInitialized (AndroidKeyStoreCipherSpiBase.java:334)
```

| Occurrences (30 days) | Total Occurrences | Impacted users (lifetime) |
| --- | --- | --- |
| 34 | 34 | 10 |

https://play.google.com/console/u/0/developers/{redacted}//app/{redacted}/vitals/crashes/3eeeb4f81a3d0463339b15915efd8df7/details?installedFrom=PLAY_STORE&days=30&clustering=NEW&versionCode=40104312%2C40104311

### PR DESCRIPTION
**Pull request by jmartinesp**
## Type of change

- [ ] Feature
- [x] Bugfix
- [ ] Technical
- [ ] Other :

## Content

Fixes #6768.
Depends on #6769.

## Motivation and context

On Android 12 and 12L (APIs 31 and 32) there seems to be a bug that causes `KeyguardManager.isDeviceLocked` to be true for a few milliseconds even after the lock screen has been dismissed and the app is already displayed. 

Since we added `setRequiresDeviceUnlocked(true)` to the biometric key, it can only be used after the device is unlocked and `KeyStore` will throw an exception if we try to access the key while it's locked. In this case, it's causing crashes when trying to update `LockScreenViewModel`'s state based on the biometric keys info.

I also tried to simplify the implementation of the lock screen feature by removing some redundant components (LockScreenConfigurationProvider).

## Tests

- Make sure you're on Android 12 or 12L, in a physical device if possible (emulators on those APIs sometimes don't work well with biometric auth).
- Also, make sure the device has biometric authentication enabled.
- Open the app, set up biometric authentication for it if it wasn't already enabled. You can do this on Settings > Security and privacy > Protect access.
- With the app visible, lock and unlock the device using the power button then your pin/pattern/fingerprint.

If the app didn't crash, the fix is working.

## Tested devices

- [x] Physical
- [x] Emulator
- OS version(s): 13, 12L, 12, 11.

## Checklist

- [ ] Changes has been tested on an Android device or Android emulator with API 21
- [ ] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#accessibility
- [x] Pull request is based on the develop branch
- [x] Pull request includes a new file under ./changelog.d. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#changelog
- [ ] Pull request includes screenshots or videos if containing UI changes
- [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [x] You've made a self review of your PR
- [ ] If you have modified the screen flow, or added new screens to the application, you have updated the test [UiAllScreensSanityTest.allScreensTest()](https://github.com/vector-im/element-android/blob/main/vector/src/androidTest/java/im/vector/app/ui/UiAllScreensSanityTest.kt#L73)

### CODE REVIEW

File: vector/src/main/java/im/vector/app/features/pin/lockscreen/biometrics/BiometricHelper.kt [hunk 1]
```diff
@@ -174,16 +180,18 @@ class BiometricHelper @Inject constructor(
...
+                        }
                         prompt = null
                         throw exception
                     }
                 }
             }
-            // Generates the system key on successful authentication
-            if (buildVersionSdkIntProvider.get() >= Build.VERSION_CODES.M) {
-                lockScreenKeyRepository.ensureSystemKey()
-            }
```
Comment (jmartinesp) [inline vector/src/main/java/im/vector/app/features/pin/lockscreen/biometrics/BiometricHelper.kt:186]: Since we started using `CryptoObject`, the system key is created when that `CryptoObject` is instantiated. Instead of ensuring the system key is created on success, make sure it's removed on error if we were on the process of enabling biometric auth.

File: vector/src/main/java/im/vector/app/features/pin/lockscreen/ui/LockScreenViewModel.kt [hunk 2]
```diff
@@ -181,8 +176,19 @@ class LockScreenViewModel @AssistedInject constructor(
...
+     */
+    @SuppressLint("NewApi")
+    @VisibleForTesting(otherwise = VisibleForTesting.PRIVATE)
+    internal suspend fun waitUntilKeyguardIsUnlocked() {
+        if (versionProvider.get() < Build.VERSION_CODES.S) return
+        withTimeoutOrNull(5.seconds) {
+            while (keyguardManager.isDeviceLocked) {
+                delay(50.milliseconds)
+            }
+        }
```
Comment (jmartinesp) [inline vector/src/main/java/im/vector/app/features/pin/lockscreen/ui/LockScreenViewModel.kt:192]: This is the actual code that fixes the issue.

**Comment by ouchadam** [comment]
if the PR is set to be based on https://github.com/vector-im/element-android/pull/6780 we'll get a smaller diff (and it'll automatically update the base branch when the base is merged)

File: vector/src/main/java/im/vector/app/features/pin/lockscreen/ui/LockScreenViewModel.kt (hunk 2 above)
Comment (ouchadam) [reply vector/src/main/java/im/vector/app/features/pin/lockscreen/ui/LockScreenViewModel.kt:192]: do you think it's worth extracting this to a dedicated class/usecase? would also mean we could avoid the `VisibleForTesting`

not a blocker for me

File: vector/src/androidTest/java/im/vector/app/features/pin/lockscreen/biometrics/BiometricHelperTests.kt [hunk 3]
```diff
@@ -239,36 +240,35 @@ class BiometricHelperTests {
...
-    fun authenticateCreatesSystemKeyIfNeededOnSuccessOnAndroidM() = runTest {
+    fun enableAuthenticationDeletesSystemKeyOnFailure() = runTest {
         buildVersionSdkIntProvider.value = Build.VERSION_CODES.M
-        every { lockScreenKeyRepository.isSystemKeyValid() } returns true
         val mockAuthChannel = Channel<Boolean>(capacity = 1)
         val biometricUtils = spyk(createBiometricHelper(createDefaultConfiguration(isBiometricsEnabled = true))) {
             every { createAuthChannel() } returns mockAuthChannel
             every { authenticateWithPromptInternal(any(), any(), any()) } returns mockk()
         }
+        every { lockScreenKeyRepository.deleteSystemKey() } returns Unit
```
Comment (ouchadam) [inline vector/src/androidTest/java/im/vector/app/features/pin/lockscreen/biometrics/BiometricHelperTests.kt:250]: can also use `justRun/coJustRun` for these `Unit` cases

File: vector/src/main/java/im/vector/app/features/pin/lockscreen/ui/LockScreenViewModel.kt (hunk 2 above)
Comment (jmartinesp) [reply vector/src/main/java/im/vector/app/features/pin/lockscreen/ui/LockScreenViewModel.kt:192]: Actually, the `@VisibleForTesting` annotation is no longer needed, I forgot to revert it to private.

I also thought about making it an external component, but it seemed too specific since it's only used here and it's a terrible hack that shouldn't be used anywhere if there's an alternative.

File: vector/src/main/java/im/vector/app/features/pin/lockscreen/ui/LockScreenFragment.kt [hunk 4]
```diff
@@ -55,22 +59,12 @@ class LockScreenFragment : VectorBaseFragment<FragmentLockScreenBinding>() {
...
         }
 
-        withState(viewModel) { state ->
-            if (state.lockScreenConfiguration.mode == LockScreenMode.CREATE) return@withState
-
-            viewLifecycleOwner.lifecycleScope.launchWhenResumed {
-                if (state.canUseBiometricAuth && state.isBiometricKeyInvalidated) {
-                    lockScreenListener?.onBiometricKeyInvalidated()
-                } else if (state.showBiometricPromptAutomatically) {
+        viewModel.stateFlow.distinctUntilChangedBy { it.showBiometricPromptAutomatically }
```
Comment (ouchadam) [inline vector/src/main/java/im/vector/app/features/pin/lockscreen/ui/LockScreenFragment.kt:62]: I'm wondering if we should expose this as a `ViewEvent`, the `ViewModel.init` would register to the state and emit the event in `onEach` rather than the `Fragment` handling the logic (would have the benefit of being testable at the `ViewModel` layer)
 
what do you think? (could be a separate PR if you agree)

Comment (jmartinesp) [reply vector/src/main/java/im/vector/app/features/pin/lockscreen/ui/LockScreenFragment.kt:62]: I think we don't need to observe the field, just checking it once on `init`, inside the launched coroutine should be enough: we only want to display the prompt automatically once when the user enters the lockscreen, so triggering the event several times depending on external changes might be weird behaviour.

Comment (ouchadam) [reply vector/src/main/java/im/vector/app/features/pin/lockscreen/ui/LockScreenFragment.kt:62]: I see! in that case `flow.first { it.showBiometricPromptAutomatically  }` might be better than distinct + filter 

it's also worth highlighting `init` is probably a bad place to emit events as it requires the fragments to be able to start observing before the `ViewModel` has been created, otherwise it creates race conditions :sweat_smile: 

other `ViewModels` has dedicated actions that correlate to the lifecycle like `Resumed/Visible`

File: vector/src/main/java/im/vector/app/features/pin/lockscreen/ui/LockScreenViewModel.kt (hunk 2 above)
Comment (ouchadam) [reply vector/src/main/java/im/vector/app/features/pin/lockscreen/ui/LockScreenViewModel.kt:192]: I don't have tooo strong of an opinion here, up to you! 
I would lean towards extracting as `ViewModels` tend to collect logic, requiring more setup for unit tests

File: vector/src/main/java/im/vector/app/features/pin/lockscreen/ui/LockScreenFragment.kt (hunk 4 above)
Comment (jmartinesp) [reply vector/src/main/java/im/vector/app/features/pin/lockscreen/ui/LockScreenFragment.kt:62]: Do you mean something like this?

```kotlin
init {
    ...
    observeStateChanges()
}

private fun observeStateChanges() {
    viewModelScope.launch {
        if (stateFlow.firstOrNull { it.showBiometricPromptAutomatically } != null) {
            _viewEvents.post(LockScreenViewEvent.ShowBiometricPromptAutomatically)
        }
    }

    viewModelScope.launch {
        if (stateFlow.firstOrNull { it.isBiometricKeyInvalidated } != null) {
            onBiometricKeyInvalidated()
        }
    }
}
```

Comment (ouchadam) [reply vector/src/main/java/im/vector/app/features/pin/lockscreen/ui/LockScreenFragment.kt:62]: yep ^^^ but if it's possible for the view event to trigger before a fragment has a chance to start observing we'll need another `ViewAction` when `onCreate` or `onResume` happens to trigger the logic rather instead of `init`

Comment (jmartinesp) [reply vector/src/main/java/im/vector/app/features/pin/lockscreen/ui/LockScreenFragment.kt]: I added an `OnUIReady` action to be triggered when the fragment's `onViewCreated` is called, right after it starts observing events.

**Review by ouchadam — APPROVED** [review]
