### PR TITLE
Shortcuts must first start MainActivity to ensure the session is restored.

### LINKED ISSUE #6672: Crash when clicking on a room shortcut
### Steps to reproduce

1. Create a room shortcut on home
2. Kill the app
3. Start the app using the shortcut
4. Can also be repro when long clicking on the app launcher and selecting a room here.

#### What did you expect?

The room is opened

#### What happened instead?

The app crashes

### Your phone model

any

### Operating system version

any

### Application version and app store

1.4.28

### Homeserver

any

### Will you send logs?

Yes

### Are you willing to provide a PR?

Yes

### PR DESCRIPTION
**Pull request by bmarty**
## Type of change

- [ ] Feature
- [x] Bugfix (not in prod)
- [ ] Technical
- [ ] Other :

## Motivation and context

Closes #6672 

Fix tested OK on my side, using the two ways to have a shortcut.

Will double check what we can do for existing shortcuts on home screen, but I think there is nothing we can do except try to remove / disable them.

**EDIT** Ok, pinned shortcut can be updated, tested OK on my device.

No changelog since it's not released code.

## Tests

- See #6672 

Also:
- create a shortcut with the previous version
- click on the shortcut: the app crash
- install the app with this PR
- the existing shortcuts are migrated
- clicking on the same shortcut open the app without crashing

## Tested devices

- [x] Physical
- [ ] Emulator
- OS version(s):

## Checklist

- [ ] Changes has been tested on an Android device or Android emulator with API 21
- [ ] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#accessibility
- [ ] Pull request is based on the develop branch
- [ ] Pull request includes a new file under ./changelog.d. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#changelog
- [ ] Pull request includes screenshots or videos if containing UI changes
- [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [ ] You've made a self review of your PR
- [ ] If you have modified the screen flow, or added new screens to the application, you have updated the test [UiAllScreensSanityTest.allScreensTest()](https://github.com/vector-im/element-android/blob/main/vector/src/androidTest/java/im/vector/app/ui/UiAllScreensSanityTest.kt#L73)

### CODE REVIEW

File: vector/src/main/java/im/vector/app/features/MainActivity.kt [hunk 1]
```diff
@@ -171,6 +181,13 @@ class MainActivity : VectorBaseActivity<ActivityMainBinding>(), UnlockedActivity
         } else if (intent.hasExtra(EXTRA_INIT_SESSION)) {
             setResult(RESULT_OK)
             finish()
+        } else if (intent.action == ACTION_ROOM_DETAILS_FROM_SHORTCUT) {
+            val roomId = intent.getStringExtra(EXTRA_ROOM_ID)
+            if (roomId?.isNotEmpty() == true) {
+                // TODO Add a trigger Shortcut to the analytics.
```
Comment (bmarty) [inline vector/src/main/java/im/vector/app/features/MainActivity.kt:187]: I will handle that later

**Review by ouchadam — APPROVED** [review]

File: vector/src/main/java/im/vector/app/features/MainActivity.kt (hunk 1 above)
Comment (ouchadam) [reply vector/src/main/java/im/vector/app/features/MainActivity.kt:187]: worth a ticket so we don't forget?

Comment (bmarty) [reply vector/src/main/java/im/vector/app/features/MainActivity.kt:187]: https://github.com/matrix-org/matrix-analytics-events/pull/69

File: vector/src/main/java/im/vector/app/features/home/ShortcutsHandler.kt [hunk 2]
```diff
@@ -87,6 +96,25 @@ class ShortcutsHandler @Inject constructor(
                 .launchIn(coroutineScope)
     }
 
+    fun updateShortcutsWithPreviousIntent() {
+        // Check if it's been already done
+        if (sharedPreferences.getBoolean(SHARED_PREF_KEY, false)) return
+        ShortcutManagerCompat.getShortcuts(context, ShortcutManagerCompat.FLAG_MATCH_PINNED)
+                .filter { it.intent.component?.className == RoomDetailActivity::class.qualifiedName }
+                .mapNotNull {
+                    it.intent.getStringExtra("EXTRA_ROOM_ID")?.let { roomId ->
```
Comment (bmarty) [inline vector/src/main/java/im/vector/app/features/home/ShortcutsHandler.kt:105]: Previously defined in `RoomDetailActivity` with `const val EXTRA_ROOM_ID = "EXTRA_ROOM_ID"` but I prefer to use hard-coded string here, since we are removing it.

File: vector/src/main/java/im/vector/app/features/MainActivity.kt [hunk 3]
```diff
@@ -131,6 +141,8 @@ class MainActivity : VectorBaseActivity<ActivityMainBinding>(), UnlockedActivity
     override fun onCreate(savedInstanceState: Bundle?) {
         super.onCreate(savedInstanceState)
 
+        shortcutsHandler.updateShortcutsWithPreviousIntent()
```
Comment (bmarty) [inline vector/src/main/java/im/vector/app/features/MainActivity.kt:144]: Should probably be better to put that in the ViewModel, but like many other things in this Activity... This would deserve a proper rework.

Comment (ouchadam) [inline vector/src/main/java/im/vector/app/features/MainActivity.kt:144]: eventually we may want to introduce an app domain migrator for these sorts of changes (could also be used for updating and removing shared prefs etc)

Comment (bmarty) [reply vector/src/main/java/im/vector/app/features/MainActivity.kt:144]: yes, it was requested by other devs too.

**Review by ouchadam — APPROVED** [review]

**Comment by bmarty** [comment]
(Handling lint error :/)
