### PR TITLE
Fix mentions using matrix.to rather than client defined permalink base url

### LINKED ISSUE #5521: HTML/MD mentions spans are based on matrix.to rather than the client defined permalink base url
### Steps to reproduce

See TextPillsUtils.kt

Issue would be detectable when using mentions on any client that defines its own permalink base url

#### What did you expect?

Mentions use the permalink base url

### Your phone model

_No response_

### Operating system version

_No response_

### Application version and app store

_No response_

### Homeserver

_No response_

### Will you send logs?

No

### PR DESCRIPTION
**Pull request by aringenbach**
## Type of change

- [ ] Feature
- [x] Bugfix
- [ ] Technical
- [ ] Other :

## Content

Mentions permalinks are now based on the client defined permalink base url if available rather than using matrix.to (default).

## Motivation and context

Fixes #5521 

## Tests

- Step 1: Define clientPermalinkBaseUrl in MatrixConfiguration (don't forget to add it to permalink_supported_hosts as well)
- Step 2: Test communication with another client with the same configuration and the usability of created permalinks (ideally with iOS and/or Web)

## Tested devices

- [ ] Physical
- [x] Emulator
- OS version(s): 12

## Checklist

- [ ] Changes has been tested on an Android device or Android emulator with API 21
- [ ] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#accessibility
- [x] Pull request is based on the develop branch
- [x] Pull request includes a new file under ./changelog.d. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#changelog
- [ ] Pull request includes screenshots or videos if containing UI changes
- [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [x] You've made a self review of your PR
- [ ] If you have modified the screen flow, or added new screens to the application, you have updated the test [UiAllScreensSanityTest.allScreensTest()](https://github.com/vector-im/element-android/blob/main/vector/src/androidTest/java/im/vector/app/ui/UiAllScreensSanityTest.kt#L73)

### CODE REVIEW

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/permalinks/PermalinkFactory.kt [hunk 1]
```diff
@@ -105,6 +105,28 @@ internal class PermalinkFactory @Inject constructor(
                 ?.substringBeforeLast("?")
     }
 
+    fun createHtmlMentionSpanTemplate(forceMatrixTo: Boolean): String {
```
Comment (ariskotsomitopoulos) [inline matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/permalinks/PermalinkFactory.kt:108]: I would combine `createMdMentionSpanTemplate` and `createHtmlMentionSpanTemplate` and pass `MENTION_SPAN_TO_HTML_TEMPLATE_BEGIN` or  `MENTION_SPAN_TO_MD_TEMPLATE_BEGIN`  as parameter to avoid code duplication.

**Review by ariskotsomitopoulos — APPROVED** [review]
It seems fine to me, I added some comments

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/permalinks/PermalinkFactory.kt (hunk 1 above)
Comment (aringenbach) [reply matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/permalinks/PermalinkFactory.kt]: Fair point. I actually made an enum at the interface level so it's not bind to what's in the factory :)

Comment (ariskotsomitopoulos) [reply matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/permalinks/PermalinkFactory.kt]: Nice!
