### PR TITLE
Fix crpyto store migration from RiotX.

### LINKED ISSUE #2252: Messages encrypted with no way to decrypt after SDK update from 0.18 to 1.0.0
**Describe the bug**
We updated from SDK 0.18 to 1.0.0 and ran into an IllegalArgumentException thrown by getLastAuthenticatedSession. We resolve this by applying the try-catch block and doing so creates a new session. As a result of that Messages show up as encrypted because the app's session has changed during the SDK update. Users do not have a way to set their Connect key in 0.18. 

**To Reproduce**
1. Upgrade SDK from 0.18 to 1.0.0 
2. Run the build, you'll run into a crash - IllegalArgumentException thrown by getLastAuthenticatedSession method.
3. Fix crash by applying the try-catch block
4. Build and run - See Error - older messages will be coming up as "encrypted"

**Expected behavior**
The session should not change upon SDK update

**Smartphone (please complete the following information):**
 - Device: [all Android devices]
 - OS: [all Android versions]

**Additional context**
 - App version and store [e.g. 0.18 to 1.0.0]
 - LOGS:

java.lang.IllegalArgumentException: Field already exists in 'IncomingRoomKeyRequestEntity': requestBodyAlgorithm
at io.realm.MutableRealmObjectSchema.checkFieldNameIsAvailable(MutableRealmObjectSchema.java:369)
at io.realm.MutableRealmObjectSchema.checkNewFieldName(MutableRealmObjectSchema.java:364)
at io.realm.MutableRealmObjectSchema.addField(MutableRealmObjectSchema.java:108)
at im.vector.matrix.android.internal.crypto.store.db.RealmCryptoStoreMigration.migrateTo2Legacy(RealmCryptoStoreMigration.kt:92)
at im.vector.matrix.android.internal.crypto.store.db.RealmCryptoStoreMigration.migrate(RealmCryptoStoreMigration.kt:64)
at io.realm.BaseRealm$6.onMigrationNeeded(BaseRealm.java:782)
at io.realm.internal.OsSharedRealm.runMigrationCallback(OsSharedRealm.java:533)
at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)
at io.realm.internal.OsSharedRealm.(OsSharedRealm.java:171)
at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:241)
at io.realm.BaseRealm.(BaseRealm.java:136)
at io.realm.BaseRealm.(BaseRealm.java:103)
at io.realm.Realm.(Realm.java:163)
at io.realm.Realm.createInstance(Realm.java:499)
at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:360)
at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:290)
at io.realm.Realm.getInstance(Realm.java:428)
at im.vector.matrix.android.internal.crypto.store.db.HelperKt.doRealmTransaction(Helper.kt:61)
at im.vector.matrix.android.internal.crypto.store.db.RealmCryptoStore.(RealmCryptoStore.kt:135)
at im.vector.matrix.android.internal.crypto.store.db.RealmCryptoStore_Factory.newInstance(RealmCryptoStore_Factory.java:43)
at im.vector.matrix.android.internal.crypto.store.db.RealmCryptoStore_Factory.get(RealmCryptoStore_Factory.java:31)
at im.vector.matrix.android.internal.crypto.store.db.RealmCryptoStore_Factory.get(RealmCryptoStore_Factory.java:10)
at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
at im.vector.matrix.android.internal.crypto.DefaultCryptoService_Factory.get(DefaultCryptoService_Factory.java:185)
at im.vector.matrix.android.internal.crypto.DefaultCryptoService_Factory.get(DefaultCryptoService_Factory.java:34)
at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
at dagger.internal.DelegateFactory.get(DelegateFactory.java:36)
at im.vector.matrix.android.internal.session.room.EventRelationsAggregationProcessor_Factory.get(EventRelationsAggregationProcessor_Factory.java:25)
at im.vector.matrix.android.internal.session.room.EventRelationsAggregationProcessor_Factory.get(EventRelationsAggregationProcessor_Factory.java:8)
at dagger.internal.SetFactory.get(SetFactory.java:126)
at dagger.internal.SetFactory.get(SetFactory.java:37)
at im.vector.matrix.android.internal.database.EventInsertLiveObserver_Factory.get(EventInsertLiveObserver_Factory.java:32)
at im.vector.matrix.android.internal.database.EventInsertLiveObserver_Factory.get(EventInsertLiveObserver_Factory.java:11)
at dagger.internal.SetFactory.get(SetFactory.java:126)
at dagger.internal.SetFactory.get(SetFactory.java:37)
at im.vector.matrix.android.internal.session.DefaultSession_Factory.get(DefaultSession_Factory.java:215)
at im.vector.matrix.android.internal.session.DefaultSession_Factory.get(DefaultSession_Factory.java:48)
at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
at im.vector.matrix.android.internal.session.DaggerSessionComponent.session(DaggerSessionComponent.java:1593)
at im.vector.matrix.android.internal.SessionManager.getOrCreateSession(SessionManager.kt:42)
at im.vector.matrix.android.internal.auth.DefaultAuthenticationService.getLastAuthenticatedSession(DefaultAuthenticationService.kt:87)

### PR DESCRIPTION
**Pull request by onurays**
Fixes #2252

### CODE REVIEW

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/store/db/RealmCryptoStoreMigration.kt [hunk 1]
```diff
@@ -57,6 +58,29 @@ internal class RealmCryptoStoreMigration @Inject constructor(private val crossSi
...
+        }
+        return this
+    }
+
+    private fun RealmObjectSchema.setRequiredIfNotAlready(fieldName: String, isRequired: Boolean): RealmObjectSchema {
+        if (isRequired && !isRequired(fieldName)) {
+            setRequired(fieldName, true)
+        } else if (!isRequired && isRequired(fieldName)) {
+            setRequired(fieldName, false)
+        }
```
Comment (bmarty) [inline matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/store/db/RealmCryptoStoreMigration.kt:80]: Could be simplified by
`if (isRequired != isRequired(fieldName) { setRequired(filedName, isRequired) }`

**Review by bmarty — APPROVED** [review]
LGTM, one small remark, but it can stay like that. Thanks!
Will be merged after the release

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/store/db/RealmCryptoStoreMigration.kt (hunk 1 above)
Comment (onurays) [reply matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/store/db/RealmCryptoStoreMigration.kt:78]: Nice, done.
