### PR TITLE
Start DM - Fix glitch in the room list

### LINKED ISSUE #7121: [Start DM] The local room temporary appears in the room list
### Steps to reproduce

1. Start creating a DM after the first message
2. Go back to the room list...
2.a. ...after the DM creation
2.b. ...or by cancelling the DM creation
2.c ...or by relaunching the app
3. Then the local room is temporarily shown in the room list and automatically disappears

#### What did you expect?
The local room should not appear in the room list
#### What happened instead?
A glitch with the local room in the room list (clicking on it crashes the app)

### Your phone model

_No response_

### Operating system version

_No response_

### Application version and app store

_No response_

### Homeserver

_No response_

### Will you send logs?

No

### Are you willing to provide a PR?

Yes

### PR DESCRIPTION
**Pull request by Florian14**
## Type of change

- [ ] Feature
- [X] Bugfix
- [ ] Technical
- [ ] Other :

## Content

Fix a glitch when we go back to the room list from the DM creation screen

## Motivation and context

close #7121 

## Tests

- Start a DM creation with the start DM feature flag enabled
- Go back to the room list (after creating the DM, cancelling the flow or relaunching the app)
- The local room is not shown anymore in the room list

## Tested devices

- [ ] Physical
- [X] Emulator
- OS version(s):

## Checklist

- [ ] Changes has been tested on an Android device or Android emulator with API 21
- [ ] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#accessibility
- [X] Pull request is based on the develop branch
- [X] Pull request includes a new file under ./changelog.d. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#changelog
- [ ] Pull request includes screenshots or videos if containing UI changes
- [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [X] You've made a self review of your PR
- [ ] If you have modified the screen flow, or added new screens to the application, you have updated the test [UiAllScreensSanityTest.allScreensTest()](https://github.com/vector-im/element-android/blob/main/vector/src/androidTest/java/im/vector/app/ui/UiAllScreensSanityTest.kt#L73)

### CODE REVIEW

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/RoomSummaryQueryParams.kt [hunk 1]
```diff
@@ -94,6 +100,7 @@ data class RoomSummaryQueryParams(
      * [roomSummaryQueryParams] and [spaceSummaryQueryParams] can also be used to build an instance of [RoomSummaryQueryParams].
      */
     class Builder {
+        var roomId: QueryStringValue = QueryStringValue.NotContains(RoomLocalEcho.PREFIX)
```
Comment (bmarty) [inline matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/RoomSummaryQueryParams.kt:103]: I am wondering if we could have a roomId which contains `!local.`, but after checking [in the doc](https://spec.matrix.org/v1.3/appendices/#identifier-grammar), this is not possible, so we are good.

File: vector/src/main/java/im/vector/app/features/home/room/list/RoomListViewModel.kt [hunk 2]
```diff
@@ -181,7 +173,7 @@ class RoomListViewModel @AssistedInject constructor(
         return session.getRoom(roomId)?.stateService()?.isPublic().orFalse()
     }
 
-    fun deleteLocalRooms(roomsIds: Set<String>) {
+    fun deleteLocalRooms(roomsIds: List<String>) {
```
Comment (bmarty) [inline vector/src/main/java/im/vector/app/features/home/room/list/RoomListViewModel.kt:176]: Using `Iterable` could help to not depend on the implementation

```suggestion
    fun deleteLocalRooms(roomsIds: Iterable<String>) {
```

**Review by bmarty — APPROVED** [review]
LGTM, some minor remarks.

File: vector/src/main/java/im/vector/app/features/home/room/list/RoomListViewModel.kt (hunk 2 above)
Comment (Florian14) [reply vector/src/main/java/im/vector/app/features/home/room/list/RoomListViewModel.kt]: Done https://github.com/vector-im/element-android/pull/7123/commits/6c9ae331e324edc20dd6d9bcf7c64db20b41c46c
