### PR TITLE
Hide deactivate account section in case of account managed externally.

### LINKED ISSUE #8619: EA: The app should hide account deactivation in OIDC-aware mode
In a native OIDC environment, account deactivation does not work anymore via `/account/deactivate`. For this reason, the feature should be hidden in the UI according to [MSC2964](https://github.com/sandhose/matrix-doc/blob/msc/sandhose/oauth2-profile/proposals/2964-oauth2-profile.md#removal-of-endpoints).

Screenshot from Web to make this more clear:

image

@bmarty @hughns

### PR DESCRIPTION
**Pull request by bmarty**
## Type of change

- [ ] Feature
- [ ] Bugfix
- [ ] Technical
- [x] Other : #8619 

## Content

Hide deactivate account setting if account is manged externally.

## Motivation and context

Closes #8619

## Tests

- connect to a matrix.org account. Observe that you can deactivate the account from the app (general settings).
- connect to a element.io account. Observe that you cannot deactivate the account from the app (general settings).

## Tested devices

- [ ] Physical
- [x] Emulator
- OS version(s):

## Checklist

- [ ] Changes has been tested on an Android device or Android emulator with API 21
- [ ] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#accessibility
- [ ] Pull request is based on the develop branch
- [ ] Pull request includes a new file under ./changelog.d. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#changelog
- [ ] Pull request includes screenshots or videos if containing UI changes
- [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [ ] You've made a self review of your PR
- [ ] If you have modified the screen flow, or added new screens to the application, you have updated the test [UiAllScreensSanityTest.allScreensTest()](https://github.com/vector-im/element-android/blob/main/vector/src/androidTest/java/im/vector/app/ui/UiAllScreensSanityTest.kt#L73)

### CODE REVIEW

File: vector/src/main/java/im/vector/app/features/settings/VectorSettingsGeneralFragment.kt [hunk 1]
```diff
@@ -322,6 +326,8 @@ class VectorSettingsGeneralFragment :
 
             false
         }
+        // Account deactivation is visible only if account is not managed by an external URL.
```
Comment (hughns) [inline vector/src/main/java/im/vector/app/features/settings/VectorSettingsGeneralFragment.kt:329]: This isn't quite right:

Account deactivation is visible only if the homeserver is not using MSC3861 delegated auth.

This is because the external account management URL field `account` is optional in [MSC2965](https://github.com/sandhose/matrix-doc/blob/msc/sandhose/oidc-discovery/proposals/2965-oidc-discovery.md#proposal)

Whether a homeserver is using MSC3861 can be determined by look at whether there is a `m.authentication` (or `org.matrix.msc2965.authentication` whilst in MSC process) entry in the `.well-known/matrix/client` entry.

I think a new a new boolean field on `HomeServerCapabilities` something like `delegatedOidcAuth` would make sense.

**Review by hughns — CHANGES_REQUESTED** [review]

File: vector/src/main/java/im/vector/app/features/settings/VectorSettingsGeneralFragment.kt (hunk 1 above)
Comment (hughns) [reply vector/src/main/java/im/vector/app/features/settings/VectorSettingsGeneralFragment.kt:329]: Yes, that is correct. 👍

Comment (bmarty) [reply vector/src/main/java/im/vector/app/features/settings/VectorSettingsGeneralFragment.kt:329]: OK, I will wait for #8620 to be merged, since I will need code that I have added there, to resume the work on this PR (after a rebase).

**Review by hughns — APPROVED** [review]
I've checked this locally and looks good.
