### PR TITLE
`Home` always showing all rooms

### LINKED ISSUE #6665: `Show all rooms in Home` preference has no effect
### Steps to reproduce

1. Have rooms in spaces
2. In settings -> preferences disable `Show all rooms in Home`
3. Open the home space, expect to NOT see the rooms from other spaces

#### What did you expect?
For rooms within other spaces to be filtered out from home when the preference is disabled

#### What happened instead?

Element android 
| PREFERENCE | SPACE | ROOM LIST | OTHER SPACE |
| --- | --- | --- | --- |
Screenshot_20220728_095605|Screenshot_20220728_095537|Screenshot_20220728_095522|Screenshot_20220728_095831

### Your phone model

_No response_

### Operating system version

_No response_

### Application version and app store

_No response_

### Homeserver

_No response_

### Will you send logs?

No

### Are you willing to provide a PR?

Yes

### PR DESCRIPTION
**Pull request by ouchadam**
## Type of change

- [ ] Feature
- [x] Bugfix
- [ ] Technical
- [ ] Other :

## Content

- Updates the `toActiveSpaceOrOrphanRooms` usages to avoid the nullsafe fallback, the extension already handles the null case for us (this is the fix!)
- Replaces the nullable `SpaceFilter` in favour of a dedicated `NoFilter` type, should help address the ambiguity of the different states 

## Motivation and context

Fixes #6665 

## Screenshots / GIFs

| BEFORE | AFTER | 
| --- | --- | 
|before-show-rooms|after-rooms-in-home

## Tests

- Have rooms across spaces
- Notice Home is always showing all rooms
- Notice the `Show all rooms in Home` preference has no effect

## Tested devices

- [x] Physical
- [ ] Emulator
- OS version(s): 28

### CODE REVIEW

File: vector/src/main/java/im/vector/app/features/home/UnreadMessagesSharedViewModel.kt [hunk 1]
```diff
@@ -144,7 +144,7 @@ class UnreadMessagesSharedViewModel @AssistedInject constructor(
                         this.memberships = listOf(Membership.JOIN)
                         this.spaceFilter = SpaceFilter.OrphanRooms.takeIf {
                             !vectorPreferences.prefSpacesShowAllRoomInHome()
-                        }
+                        } ?: SpaceFilter.NoFilter
```
Comment (bmarty) [inline vector/src/main/java/im/vector/app/features/home/UnreadMessagesSharedViewModel.kt:147]: In this case I think a if/else would be clearer:
```kotlin
if (vectorPreferences.prefSpacesShowAllRoomInHome()) {
    SpaceFilter.NoFilter
} else {
    SpaceFilter.OrphanRooms
}
```

File: vector/src/main/java/im/vector/app/features/spaces/SpaceListViewModel.kt [hunk 2]
```diff
@@ -100,7 +100,7 @@ class SpaceListViewModel @AssistedInject constructor(
                     this.memberships = listOf(Membership.JOIN)
                     this.spaceFilter = SpaceFilter.OrphanRooms.takeIf {
                         !vectorPreferences.prefSpacesShowAllRoomInHome()
-                    }
+                    } ?: SpaceFilter.NoFilter
```
Comment (bmarty) [inline vector/src/main/java/im/vector/app/features/spaces/SpaceListViewModel.kt:103]: Same remark

File: vector/src/main/java/im/vector/app/features/spaces/SpaceListViewModel.kt [hunk 3]
```diff
@@ -117,7 +117,7 @@ class SpaceListViewModel @AssistedInject constructor(
                                 this.memberships = listOf(Membership.JOIN)
                                 this.spaceFilter = SpaceFilter.OrphanRooms.takeIf {
                                     !vectorPreferences.prefSpacesShowAllRoomInHome()
-                                }
+                                } ?: SpaceFilter.NoFilter
```
Comment (bmarty) [inline vector/src/main/java/im/vector/app/features/spaces/SpaceListViewModel.kt:120]: same remark

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/RoomSummaryQueryParams.kt [hunk 4]
```diff
@@ -86,7 +86,7 @@ data class RoomSummaryQueryParams(
         /**
          * Used to filter room using the current space.
          */
-        val spaceFilter: SpaceFilter?,
+        val spaceFilter: SpaceFilter,
```
Comment (bmarty) [inline matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/RoomSummaryQueryParams.kt:89]: Maybe mention this API change in a file `6666.sdk`

**Review by bmarty — APPROVED** [review]
LGTM, thanks!

File: vector/src/main/java/im/vector/app/features/home/UnreadMessagesSharedViewModel.kt (hunk 1 above)
Comment (ouchadam) [reply vector/src/main/java/im/vector/app/features/home/UnreadMessagesSharedViewModel.kt:147]: agreed, will update :+1:

Comment (ouchadam) [reply vector/src/main/java/im/vector/app/features/home/UnreadMessagesSharedViewModel.kt]: https://github.com/vector-im/element-android/pull/6666/commits/09d840506e8b3e8e074608b7c443778b90120c77

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/RoomSummaryQueryParams.kt (hunk 4 above)
Comment (ouchadam) [reply matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/RoomSummaryQueryParams.kt:89]: https://github.com/vector-im/element-android/pull/6666/commits/e4640f14d24529ba0efe1e025d09d37714f5a712

File: vector/src/main/java/im/vector/app/features/home/room/list/home/HomeRoomListViewModel.kt [hunk 5]
```diff
@@ -106,13 +106,8 @@ class HomeRoomListViewModel @AssistedInject constructor(
                 }
                 .onEach { selectedSpaceOption ->
                     val selectedSpace = selectedSpaceOption.orNull()
-                    val strategy = if (!vectorPreferences.prefSpacesShowAllRoomInHome()) {
```
Comment (ouchadam) [inline vector/src/main/java/im/vector/app/features/home/room/list/home/HomeRoomListViewModel.kt:109]: cc @fedrunov this condition looked inverted and has been updated to match the usages in other screens

```
when {
  vectorPreferences.prefSpacesShowAllRoomInHome() -> selectedSpaceId.toActiveSpaceOrNoFilter()
  else -> selectedSpaceId.toActiveSpaceOrOrphanRooms()
}
```

File: vector/src/main/java/im/vector/app/features/spaces/SpaceListViewModel.kt [hunk 6]
```diff
@@ -134,6 +130,11 @@ class SpaceListViewModel @AssistedInject constructor(
                 .launchIn(viewModelScope)
     }
 
+    private fun roomsInSpaceFilter() = when {
```
Comment (bmarty) [inline vector/src/main/java/im/vector/app/features/spaces/SpaceListViewModel.kt:133]: Please do not change it now, but the `fun` name is a bit strange to me.
Maybe something like `getSpaceFilter()` would be better.
On the fund, I do not really get why we have such filter here, since IIUC this ViewModel is used by the screen which displays only Spaces. So having orphans rooms here is strange to me.

**Review by bmarty — APPROVED** [review]
LGTM, thanks for the update.

File: vector/src/main/java/im/vector/app/features/spaces/SpaceListViewModel.kt (hunk 6 above)
Comment (bmarty) [reply vector/src/main/java/im/vector/app/features/spaces/SpaceListViewModel.kt:133]: Ah, OK, it's to update the notification count. Please ignore me!

**Comment by ouchadam** [comment]
going to skip waiting for the instrumentation tests to complete so that the RC process can start
