### PR TITLE
FTUE - Crash fixes

### LINKED ISSUE #6855: App Crashes On Email Verification (Sign Up)
During a community testing session we found that during sign up that upon verifying your email, when reaching the login captcha fragment, the app crashes.

Rageshake:
https://github.com/matrix-org/element-android-rageshakes/issues/41896

I tried reproducing this issue myself (on matrix.org) but to no avail. It's possible that this is dependent on the homeserver.

What this meant for the user however is they could not sign up at all

### LINKED ISSUE #6860: Crash when returning to app after closing during email verification
### Steps to reproduce

1. Start the account creation process
2. When asked to confirm the email, force close the app
3. Relaunch the app and notice the email verification screen has opened
4. Continue the account creation process by clicking the link in the email
5. Notice the app crashes 

#### What did you expect?
If the app has been force stopped or crashes during account creation we should reset the flow back to the beginning as it means we've lost track of all the onboarding previous steps. The app is able to correctly restore the registration when the system uses its restoration mechanism (task switching) 

#### What happened instead?
The app shortcuts to the email verification screen without the data from the previous steps, causing the continuation of the account creation to crash due to missing information

https://play.google.com/console/u/0/developers/{redacted}/app/{redacted}/vitals/crashes/f5810fcdfd8bccf4e8c6ec5970ff51ad/details?installedFrom=PLAY_STORE&days=30&clustering=NEW

```
Thread: main, Exception: java.lang.IllegalStateException: missing url of homeserver
```

```
Exception java.lang.IllegalStateException:
  at im.vector.app.features.onboarding.ftueauth.CaptchaWebview.setupWebView (CaptchaWebview.kt:9)
  at im.vector.app.features.onboarding.ftueauth.FtueAuthCaptchaFragment.updateWithState (FtueAuthCaptchaFragment.kt:2)
  at im.vector.app.features.onboarding.ftueauth.AbstractFtueAuthFragment$invalidate$1.invoke (AbstractFtueAuthFragment.kt:3)
  at im.vector.app.features.onboarding.ftueauth.AbstractFtueAuthFragment$invalidate$1.invoke (AbstractFtueAuthFragment.kt:1)
  at androidx.biometric.R$layout.withState
  at im.vector.app.features.onboarding.ftueauth.AbstractFtueAuthFragment.invalidate (AbstractFtueAuthFragment.kt:1)
  at com.airbnb.mvrx.MavericksViewKt$$ExternalSyntheticLambda0.handleMessage (R8$$SyntheticClass:4)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:201)
  at android.app.ActivityThread.main (ActivityThread.java:6861)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:547)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:873)
```

### Your phone model

_No response_

### Operating system version

_No response_

### Application version and app store

1.4.32

### Homeserver

_No response_

### Will you send logs?

No

### Are you willing to provide a PR?

Yes

### LINKED ISSUE #6861: Crash - IllegalStateException: Can not perform this action after onSaveInstanceState
```
Exception java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
  at androidx.fragment.app.FragmentManager.enqueueAction (FragmentManager.java:6)
  at androidx.fragment.app.BackStackRecord.commitInternal (BackStackRecord.java:14)
  at androidx.fragment.app.BackStackRecord.commit (BackStackRecord.java:1)
  at im.vector.app.core.extensions.ActivityKt.addFragmentToBackstack$default (Activity.kt:7)
  at im.vector.app.features.onboarding.ftueauth.FtueAuthVariant.addRegistrationStageFragmentToBackstack (FtueAuthVariant.kt:4)
  at im.vector.app.features.onboarding.ftueauth.FtueAuthVariant.addRegistrationStageFragmentToBackstack$default (FtueAuthVariant.kt:1)
  at im.vector.app.features.onboarding.ftueauth.FtueAuthVariant.onStartCombinedLogin (FtueAuthVariant.kt:1)
  at im.vector.app.features.onboarding.ftueauth.FtueAuthVariant.handleOnboardingViewEvents (FtueAuthVariant.kt:67)
  at im.vector.app.features.onboarding.ftueauth.FtueAuthVariant.access$handleOnboardingViewEvents (FtueAuthVariant.kt:1)
  at im.vector.app.features.onboarding.ftueauth.FtueAuthVariant$initUiAndData$1$2.invoke (FtueAuthVariant.kt:2)
  at im.vector.app.features.onboarding.ftueauth.FtueAuthVariant$initUiAndData$1$2.invoke (FtueAuthVariant.kt:1)
  at im.vector.app.core.platform.VectorBaseActivity$observeViewEvents$1.invokeSuspend (VectorBaseActivity.kt:3)
  at im.vector.app.core.platform.VectorBaseActivity$observeViewEvents$1.invoke
  at im.vector.app.core.platform.VectorBaseActivity$observeViewEvents$1.invoke
  at kotlinx.coroutines.flow.FlowKt__TransformKt$onEach$$inlined$unsafeTransform$1$2.emit (Emitters.kt:6)
  at kotlinx.coroutines.flow.SharedFlowImpl.collect$suspendImpl (SharedFlow.kt:13)
  at kotlinx.coroutines.flow.SharedFlowImpl$collect$1.invokeSuspend
  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith (ContinuationImpl.kt:3)
  at kotlinx.coroutines.DispatchedTaskKt.resume (DispatchedTask.kt:10)
  at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume (CancellableContinuationImpl.kt:15)
  at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl (CancellableContinuationImpl.kt:6)
  at kotlinx.coroutines.CancellableContinuationImpl.resumeWith (CancellableContinuationImpl.kt:4)
  at kotlinx.coroutines.flow.SharedFlowImpl.tryEmit (SharedFlow.kt:6)
  at im.vector.app.features.onboarding.OnboardingViewModel.onHomeServerSelected (OnboardingViewModel.kt:11)
  at im.vector.app.features.onboarding.OnboardingViewModel.access$onHomeServerSelected (OnboardingViewModel.kt:1)
  at im.vector.app.features.onboarding.OnboardingViewModel$onHomeServerSelected$1.invokeSuspend
  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith (ContinuationImpl.kt:3)
  at kotlinx.coroutines.DispatchedTask.run (DispatchedTask.kt:18)
  at android.os.Handler.handleCallback (Handler.java:938)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loop (Looper.java:236)
  at android.app.ActivityThread.main (ActivityThread.java:8107)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:656)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:967)
```

Affects both `onStartCombinedLogin` and `openStartCombinedRegister` due to the fragment transactions occurring asynchronously.

https://play.google.com/console/u/0/developers/{redacted}/app/{redacted}/vitals/crashes/3ff2f92ea7f32ac71458ed0e4bacfe02/details?installedFrom=PLAY_STORE&days=30&clustering=NEW&versionCode=40104322%2C40104321

https://play.google.com/console/u/0/developers/{redacted}/app/{redacted}/vitals/crashes/b46cbf61a299c3fe3ea1f997653d75cb/details?installedFrom=PLAY_STORE&days=30&clustering=NEW&versionCode=40104322%2C40104321

### PR DESCRIPTION
**Pull request by ouchadam**
## Type of change

- [ ] Feature
- [x] Bugfix
- [ ] Technical
- [ ] Other :

## Content

- Removes the ability to continue the account creation process after the app has been destroyed. This was not taking into account the missing data from the previous onboarding steps, causing the `OnboardingViewState` to be in an invalid empty state. Fixes #6860
- Replaces the captcha `WebView` xml declaration with a `ViewStub` which try/catches the inflation. Allows us to catch the missing webview crash and provide an error dialog with information about the error. Fixes #6855 
- Allows the initial login and registration fragment transactions to have _state loss_, as these fragments are the entry points the UX damage is minimal and will simply require the user pressing the `already have an account` or `use case selection` buttons again. Fixes #6861

## Motivation and context

- #6860 Crash when attempting to continue account registration after the app has been killed/force stopped
- #6855 Crash when attempting to show the captcha webview on a device that no webview installed
- #6861 Crash when leaving the app whilst loading the login or registration page

#### WebView disabled
*animations are disabled

|Before|After|
|-|-|
|before-webview-disabled|disable-webview|

## Tests

- See issue https://github.com/vector-im/element-android/issues/6860

----

- #6861 Unable to reproduce locally

----

- #6855
- Disable the system webview and chrome (or other browsers) via the system application settings
- Attempt to create an account
- Notice the app crashes when showing the captcha step.

## Tested devices

- [x] Physical
- [x] Emulator
- OS version(s): 28, 31

### CODE REVIEW

File: vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthCaptchaFragment.kt [hunk 1]
```diff
@@ -40,22 +47,71 @@ class FtueAuthCaptchaFragment @Inject constructor(
...
             isWebViewLoaded = true
         }
     }
 }
+
+private fun ViewStub.inflateWebView(onError: (Throwable) -> Unit) {
+    try {
+        inflate()
+    } catch (e: Exception) {
+        val isMissingWebView = e.crawlCausesFor { it.message?.contains("MissingWebViewPackageException").orFalse() }
```
Comment (ouchadam) [inline vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthCaptchaFragment.kt:96]: we have to crawl through the exception causes to find the missing webview package exception, it's a bit hacky~

File: vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthCaptchaFragment.kt [hunk 2]
```diff
@@ -40,22 +47,71 @@ class FtueAuthCaptchaFragment @Inject constructor(
...
+        }
+    }
+
+    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
+        super.onViewCreated(view, savedInstanceState)
+        inflateWebViewOrShowError()
+    }
+
+    private fun inflateWebViewOrShowError() {
+        views.loginCaptchaWebViewStub.inflateWebView(onError = {
```
Comment (ouchadam) [inline vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthCaptchaFragment.kt:67]: using the `ViewStub` and handling the inflation error is the fix for #6855

File: vector/src/main/java/im/vector/app/features/onboarding/OnboardingViewModel.kt [hunk 3]
```diff
@@ -492,17 +489,6 @@ class OnboardingViewModel @AssistedInject constructor(
 
     private fun handleInitWith(action: OnboardingAction.InitWith) {
         loginConfig = action.loginConfig
-        // If there is a pending email validation continue on this step
-        try {
```
Comment (ouchadam) [inline vector/src/main/java/im/vector/app/features/onboarding/OnboardingViewModel.kt:496]: Removing the attempt to fast forward the onboarding state to the _wait for email verification stage_ when the app has been killed and relaunched is the fix for #6860 

The `OnboardingViewModel` and `OnboardingViewState` already support and are restored by the system restoration process. If the process has been destroyed we need to accumulate the previous view states again otherwise we end up with invalid state.

File: vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthCaptchaFragment.kt [hunk 4]
```diff
@@ -40,22 +47,71 @@ class FtueAuthCaptchaFragment @Inject constructor(
...
+    return when {
+        this == null -> false
+        else -> {
+            when (predicate(this)) {
+                true -> true
+                else -> this.cause.crawlCausesFor(predicate)
+            }
+        }
+    }
+}
```
Comment (bmarty) [inline vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthCaptchaFragment.kt:115]: Could be rewritten to this compact, but maybe less clear:

```kotlin
private fun Throwable.crawlCausesFor(predicate: (Throwable) -> Boolean): Boolean {
    return predicate(this) || cause?.crawlCausesFor(predicate) ?: false
}
```

Also, maybe move this extension to a dedicated file for Throwable extensions?

Comment (ouchadam) [reply vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthCaptchaFragment.kt:115]: will extract :+1: 

as the function is recursive I'd lean towards making the exit conditions as clear as possible, having the recursive call the last line allows us to opt into the tailrec optimisations (although it hasn't been used here since the crash stack is fairly small)

File: vector/src/main/java/im/vector/app/core/extensions/Throwable.kt [hunk 5]
```diff
@@ -0,0 +1,34 @@
...
+ * Unless required by applicable law or agreed to in writing, software
+ * distributed under the License is distributed on an "AS IS" BASIS,
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+package im.vector.app.core.extensions
+
+/**
```
Comment (ElementBot) [inline vector/src/main/java/im/vector/app/core/extensions/Throwable.kt:19]: - :warning: The first sentence of this KDoc does not end with the correct punctuation.
