### PR TITLE
Timeline recycling crash

### LINKED ISSUE #4789: Crash - Emoji recycling attempting to use previous `TextFuture`
```
java.lang.IllegalArgumentException: 
  at android.widget.TextView.setText (TextView.java:6253)
  at android.widget.TextView.setText (TextView.java:6171)
  at android.widget.TextView.setText (TextView.java:6123)
  at androidx.core.widget.TextViewCompat.setPrecomputedText (TextViewCompat.java:4)
  at androidx.appcompat.widget.AppCompatTextView.consumeTextFutureAndSetBlocking (AppCompatTextView.java:3)
  at androidx.appcompat.widget.AppCompatTextView.getText (AppCompatTextView.java:1)
  at androidx.emoji2.viewsintegration.EmojiInputFilter.filter (EmojiInputFilter.java:4)
  at android.widget.TextView.setText (TextView.java:6207)
  at android.widget.TextView.setText (TextView.java:6171)
  at android.widget.TextView.setText (TextView.java:6123)
  at im.vector.app.features.home.room.detail.timeline.item.MessageTextItem.bind (MessageTextItem.kt:44)
  at im.vector.app.features.home.room.detail.timeline.item.MessageTextItem.bind (MessageTextItem.kt:6)
  at com.airbnb.epoxy.BaseEpoxyAdapter.onBindViewHolder (BaseEpoxyAdapter.java:25)
  at com.airbnb.epoxy.BaseEpoxyAdapter.onBindViewHolder (BaseEpoxyAdapter.java:3)
  at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder (RecyclerView.java:9)
  at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline (RecyclerView.java:7)
  at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline (RecyclerView.java:131)
  at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition (RecyclerView.java:1)
  at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next (LinearLayoutManager.java:8)
  at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk (LinearLayoutManager.java:1)
  at androidx.recyclerview.widget.LinearLayoutManager.fill (LinearLayoutManager.java:12)
  at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren (LinearLayoutManager.java:50)
  at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2 (RecyclerView.java:12)
  at androidx.recyclerview.widget.RecyclerView.dispatchLayout (RecyclerView.java:15)
  at androidx.recyclerview.widget.RecyclerView.onLayout (RecyclerView.java:3)
```

| Occurrences (30 days) | Total Occurrences | Impacted users (lifetime) |
| --- | --- | --- |
| 44 | 119 | 83 |

https://play.google.com/console/u/0/developers/{redacted}/app/{redacted}/vitals/crashes/ecfe9aba/details?versionCode=40103122%2C40103121%2C40103124%2C40103123

### PR DESCRIPTION
**Pull request by ouchadam**
Tentatively fixes #4789 Timeline crashes when quickly scrolling or restoring state.

I was unable to reproduce this crash locally, the stack trace looks to be the same as when a `TextView` is modified after setting a `TextFuture`

```
Thread: main, Exception: java.lang.IllegalArgumentException: PrecomputedText's Parameters don't match the parameters of this TextView.
    at android.widget.TextView.setText(TextView.java:6206)
    at android.widget.TextView.setText(TextView.java:6124)
    at android.widget.TextView.setText(TextView.java:6076)
    at androidx.core.widget.TextViewCompat.setPrecomputedText(TextViewCompat.java:907)
    at androidx.appcompat.widget.AppCompatTextView.consumeTextFutureAndSetBlocking(AppCompatTextView.java:542)
    at androidx.appcompat.widget.AppCompatTextView.getText(AppCompatTextView.java:551)
    at androidx.emoji2.viewsintegration.EmojiInputFilter.filter(EmojiInputFilter.java:64)
    at android.widget.TextView.setText(TextView.java:6160)
    at android.widget.TextView.setText(TextView.java:6124)
    at android.widget.TextView.setText(TextView.java:6076)
```

My theory is that `RecyclerView` is recycling `TextViews` with non consumed futures which causes them to throw when the `TextView` options are rebound. This PR aims to solve the issue by resetting any present futures before calling `setText` which will allow `AppCompatTextView.consumeTextFutureAndSetBlocking` to be skipped if the view is rebound with `setText` directly (such is the case when emojis are present)

### CODE REVIEW

File: vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/MessageTextItem.kt [hunk 1]
```diff
@@ -87,24 +87,22 @@ abstract class MessageTextItem : AbsMessageItem<MessageTextItem.Holder>() {
...
+    }
+
+    private fun AppCompatTextView.setTextWithEmojiSupport(message: CharSequence, bindingOptions: BindingOptions?) {
         if (bindingOptions?.canUseTextFuture.orFalse()) {
-            holder.messageView.setTextFuture(textFuture)
+            val textFuture = PrecomputedTextCompat.getTextFuture(message, TextViewCompat.getTextMetricsParams(this), null)
+            setTextFuture(textFuture)
         } else {
-            holder.messageView.text = if (bindingOptions?.preventMutation.orFalse()) {
+            setTextFuture(null)
```
Comment (ouchadam) [inline vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/MessageTextItem.kt:104]: this line is the potential fix

**Review by ganfra — APPROVED** [review]
LGTM, will see if we have still the crash after!

File: vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/MessageTextItem.kt [hunk 2]
```diff
@@ -87,24 +87,22 @@ abstract class MessageTextItem : AbsMessageItem<MessageTextItem.Holder>() {
...
-        } else {
-            null
-        }
         super.bind(holder)
         holder.messageView.movementMethod = movementMethod
         renderSendState(holder.messageView, holder.messageView)
         holder.messageView.onClick(attributes.itemClickListener)
         holder.messageView.onLongClickIgnoringLinks(attributes.itemLongClickListener)
 
+        message?.let { holder.messageView.setTextWithEmojiSupport(it, bindingOptions) }
```
Comment (bmarty) [inline vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/MessageTextItem.kt:96]: I guess that `message` should never be null, but the change is not strictly equivalent to what we had before: `message ?: ""`.

Maybe continue to fallback to empty string, to ensure that the text is always updated, or change `message` to a `lateinit CharSequence`

(if message is null, the TextView content will not be reset and will display the previous bound value)

**Review by bmarty — CHANGES_REQUESTED** [review]

File: vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/MessageTextItem.kt (hunk 2 above)
Comment (ouchadam) [reply vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/MessageTextItem.kt]: ah good catch, resetting to null seems safer, I don't know the epoxy lifecycle well enough to trust using a late init 

b5ce8dcb3219edb11d7a5055759e3124fa8894fe

File: vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/MessageTextItem.kt [hunk 3]
```diff
@@ -92,27 +91,22 @@ abstract class MessageTextItem : AbsMessageItem<MessageTextItem.Holder>() {
...
         }
-        val textFuture = if (bindingOptions?.canUseTextFuture.orFalse()) {
-            PrecomputedTextCompat.getTextFuture(
-                    message?.charSequence ?: "",
-                    TextViewCompat.getTextMetricsParams(holder.messageView),
-                    null)
-        } else {
-            null
-        }
-        markwonPlugins?.forEach { plugin -> plugin.beforeSetText(holder.messageView, message?.charSequence as Spanned) }
```
Comment (bmarty) [inline vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/MessageTextItem.kt:103]: This line (`markwonPlugins...`) has been removed by mistake during the merge I guess

File: vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/MessageTextItem.kt [hunk 4]
```diff
@@ -92,27 +91,22 @@ abstract class MessageTextItem : AbsMessageItem<MessageTextItem.Holder>() {
                 it.bind(holder.messageView)
             }
         }
-        val textFuture = if (bindingOptions?.canUseTextFuture.orFalse()) {
```
Comment (bmarty) [inline vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/MessageTextItem.kt:95]: I am wondering why we coputed that before the next line... Maybe there were a good reason, I do not remember

**Review by bmarty — CHANGES_REQUESTED** [review]

File: vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/MessageTextItem.kt (hunk 3 above)
Comment (ouchadam) [reply vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/MessageTextItem.kt:103]: ah :facepalm: I got confused by https://github.com/vector-im/element-android/pull/4790/files#diff-473563ebe7dac7363901c094cc094bb438921f76a16bf13a020eefbff15d0c24R100 didn't realise there were two

Comment (bmarty) [reply vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/MessageTextItem.kt:103]: There are 2 different method `beforeSetText` and a `afterSetText`, I have no idea what they are doing TBH

Comment (ouchadam) [inline vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/MessageTextItem.kt:103]: also noticed `message?.charSequence as Spanned` will throw if the message is null, will wrap with a `.let`

Comment (ouchadam) [reply vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/MessageTextItem.kt:103]: https://github.com/vector-im/element-android/pull/4790/commits/22bab47dad9072787326ae11a8587138df134c5f

Comment (bmarty) [reply vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/MessageTextItem.kt:103]: Yes, I'm pretty sure `message` cannot be null but you are right, better safe than sorry.

**Review by bmarty — APPROVED** [review]
