### PR TITLE
Feature/fix poll reply

### LINKED ISSUE #1004: Replies to poll appears in timeline as unsupported events during sending
image

image

Event has a relates_to with the type "m.response"

### LINKED ISSUE #1246: JSON for verification events leaks in to the room list
It's ugly that the message previews in the room list show italicised JSON for verification events - surely it should show the most recent m.room.message or possibly m.call.* rather than any old event?

### PR DESCRIPTION
**Pull request by BillCarsonFr**
Fixes #1246
 - JSON for verification events leaks in to the room list ()

Fixes #1004
 - Replies to poll appears in timeline as unsupported events during sending 

Looks like there was a desync between the timeline filter and the sendingEvent/InMemory filter
Also bus event for local echo creation could add local echos that was never removed (no synced event as they were filtered out)

+ Fixed a bug on poll reply not taken into account: Currently aggregation don't support relation put on a sending event (e.g edit a sending event, reply to a sending event); there was no guard against that for poll buttons, added now

### CODE REVIEW

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/DefaultTimeline.kt [hunk 1]
```diff
@@ -316,12 +316,15 @@ internal class DefaultTimeline(
...
     fun onLocalEchoCreated(onLocalEchoCreated: OnLocalEchoCreated) {
         if (isLive && onLocalEchoCreated.roomId == roomId) {
-            listeners.forEach {
-                it.onNewTimelineEvents(listOf(onLocalEchoCreated.timelineEvent.eventId))
+            // do not add events that would have been filtered
+            if (listOf(onLocalEchoCreated.timelineEvent).filterEventsWithSettings().isNotEmpty()) {
+                listeners.forEach {
+                    it.onNewTimelineEvents(listOf(onLocalEchoCreated.timelineEvent.eventId))
+                }
+                Timber.v("On local echo created: $onLocalEchoCreated")
```
Comment (bmarty) [inline matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/DefaultTimeline.kt:324]: Please be careful, it leaks the content of the event to the logs

File: vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailViewModel.kt [hunk 2]
```diff
@@ -1194,6 +1195,8 @@ class RoomDetailViewModel @AssistedInject constructor(
     }
 
     private fun handleReplyToOptions(action: RoomDetailAction.ReplyToOptions) {
+        // Do not allow to reply to unsent local echo
+        if (LocalEcho.isLocalEchoId(action.eventId)) return
```
Comment (bmarty) [inline vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailViewModel.kt:1199]: Buttons should be disabled, and I do not think it is the case.

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/DefaultTimeline.kt (hunk 1 above)
Comment (bmarty) [reply matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/DefaultTimeline.kt]: I handle it
