### PR TITLE
Fixes new device detections banner problems

### LINKED ISSUE #8353: Got asked twice about verification
### Steps to reproduce

- Have the Android App open
- Sign in with Element Web to the same account
- Tap the verification banner on Android
- Verification starts, scan QR Code, finish verification

#### What did you expect?

Verification done

#### What happened instead?

Verification banner is displayed again

### Your phone model

_No response_

### Operating system version

_No response_

### Application version and app store

1.5.30

### Homeserver

_No response_

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

### PR DESCRIPTION
**Pull request by BillCarsonFr**
## Type of change

- [ ] Feature
- [x] Bugfix
- [ ] Technical
- [ ] Other :

## Content

Fixes several problems with "new login, was this you", "You have unverified session" banners.

For rust flavor:
- A missing binding for device first time seen was causing the "new login" banner to not show up. Depends on this [rust sdk PR](https://github.com/matrix-org/matrix-rust-sdk/pull/2055)

Other problems:
- After tapping the "new login" banner to start the verification a "you have unverified session" banner was poping up under the verification bottomsheet and was not removed
- Under some conditions the "new login" banner was not dismissed after the device was verified, causing some users to click twice and perform 2 verifications. Fixes #8353
 

## Screenshots / GIFs

Before:

[unwanted_you_have_unverified.webm](https://github.com/vector-im/element-android/assets/9841565/8c8278c6-9d0b-40c5-8661-fe57279a2fa9)

After:

[after.webm](https://github.com/vector-im/element-android/assets/9841565/32a2c425-8758-42f2-b423-38160b1a6970)

## Tests

- Step 1
- Step 2
- Step ...

## Tested devices

- [ ] Physical
- [ ] Emulator
- OS version(s):

## Checklist

- [ ] Changes has been tested on an Android device or Android emulator with API 21
- [ ] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#accessibility
- [ ] Pull request is based on the develop branch
- [ ] Pull request includes a new file under ./changelog.d. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#changelog
- [ ] Pull request includes screenshots or videos if containing UI changes
- [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [ ] You've made a self review of your PR
- [ ] If you have modified the screen flow, or added new screens to the application, you have updated the test [UiAllScreensSanityTest.allScreensTest()](https://github.com/vector-im/element-android/blob/main/vector/src/androidTest/java/im/vector/app/ui/UiAllScreensSanityTest.kt#L73)

### CODE REVIEW

File: vector/src/main/java/im/vector/app/features/crypto/verification/self/SelfVerificationBottomSheet.kt [hunk 1]
```diff
@@ -229,6 +229,9 @@ class SelfVerificationBottomSheet : VectorBaseBottomSheetDialogFragment<BottomSh
     }
 
     companion object {
+
+        val TAG: String = "VERIF"
```
Comment (ElementBot) [inline vector/src/main/java/im/vector/app/features/crypto/verification/self/SelfVerificationBottomSheet.kt:233]: - :warning: TAG can be a `const val`.

Comment (ElementBot) [inline vector/src/main/java/im/vector/app/features/crypto/verification/self/SelfVerificationBottomSheet.kt:233]: - :warning: TAG can be a `const val`.

Comment (ElementBot) [inline vector/src/main/java/im/vector/app/features/crypto/verification/self/SelfVerificationBottomSheet.kt:233]: - :warning: TAG can be a `const val`.

**Review by bmarty — APPROVED** [review]
LGTM (static review)
