### PR TITLE
E2ee dos not hinder verification

### LINKED ISSUE #6723: Can't verify user when option to send keys to verified devices only is selected
### Steps to reproduce

1. Go to Settings > Security & Privacy 
3. Enable 'Encrypt to verified devices only'
4. Go back to a DM with one of your contact, click on his profile
5. Tap on verify.

#### What did you expect?

That you initiate a verification process.

#### What happened instead?

It's failing because the recipient won't be able to decrypt the verification request
image

So it's quite annoying, I enabled 'Encrypt to verified devices only' and I have unverified users in a room. So you would think that verify them will fix the issue, but you can't

### Your phone model

_No response_

### Operating system version

_No response_

### Application version and app store

1.4.32

### Homeserver

local synapse

### Will you send logs?

No

### Are you willing to provide a PR?

Yes

### PR DESCRIPTION
**Pull request by BillCarsonFr**
## Type of change

- [ ] Feature
- [x] Bugfix
- [ ] Technical
- [ ] Other :

## Content

Fixes #6723 
Verification events sent in e2ee rooms should bypass the encrypt to verified devices only option. If not it renders verification impossible.

## Motivation and context
As per spec:

> When using in-room messages and the room has encryption enabled, clients should ensure that encryption does not hinder the verification. For example, if the verification messages are encrypted, clients must ensure that all the recipient’s unverified devices receive the keys necessary to decrypt the messages, even if they would normally not be given the keys to decrypt messages in the room. Alternatively, verification messages may be sent unencrypted, though this is not encouraged.

## Tests

- Step 1
- Step 2
- Step ...

## Tested devices

- [ ] Physical
- [x] Emulator
- OS version(s):

## Checklist

- [x] Changes has been tested on an Android device or Android emulator with API 21
- [ ] UI change has been tested on both light and dark themes
- [x] Accessibility has been taken into account. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#accessibility
- [x] Pull request is based on the develop branch
- [ ] Pull request includes a new file under ./changelog.d. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#changelog
- [x] Pull request includes screenshots or videos if containing UI changes
- [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [x] You've made a self review of your PR
- [ ] If you have modified the screen flow, or added new screens to the application, you have updated the test [UiAllScreensSanityTest.allScreensTest()](https://github.com/vector-im/element-android/blob/main/vector/src/androidTest/java/im/vector/app/ui/UiAllScreensSanityTest.kt#L73)

### CODE REVIEW

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/algorithms/megolm/MXMegolmEncryption.kt [hunk 1]
```diff
@@ -417,7 +435,7 @@ internal class MXMegolmEncryption(
      *
      * @param userIds the user ids whose devices must be checked.
      */
-    private suspend fun getDevicesInRoom(userIds: List<String>): DeviceInRoomInfo {
+    private suspend fun getDevicesInRoom(userIds: List<String>, forceDistributeToUnverified: Boolean = false): DeviceInRoomInfo {
```
Comment (ElementBot) [inline matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/algorithms/megolm/MXMegolmEncryption.kt:438]: - :warning: Documentation of getDevicesInRoom is outdated

**Review by Florian14 — APPROVED** [review]
LGTM
