### PR TITLE
Fix sending multiple invites to a room reaching only one or two people

### LINKED ISSUE #6109: Sending multiple invites to a room only works partially
### Steps to reproduce

1. Create a room or get into a room where you can invite people.
2. Invite several people (at least 3 or 4).

#### What did you expect?

Everyone should be invited to the room.

#### What happened instead?

Only the first 1 or 2 people actually get invited.

### Your phone model

Emulator

### Operating system version

Android 12

### Application version and app store

1.4.18

### Homeserver

matrix.org

### Will you send logs?

No

### PR DESCRIPTION
**Pull request by jmartinesp**
## Type of change

- [ ] Feature
- [x] Bugfix
- [ ] Technical
- [ ] Other :

## Content

Fixes #6109. Based on the work of @bmarty on #6107.

Prevents early cancelation of the coroutine scope used to send the invites.

## Motivation and context

When inviting several people to a room, only the first couple of users were actually invited. The `InviteUsersToRoomActivity` was being finished ahead of time, cancelling the `viewModelScope` used to send the invite requests, and this prevented the rest of the users from being invited. This was caused by an `onEach` statement being used as `onCompletion`.

## Tests

- Create a room or open a room where you can invite other users.
- Invite several users, at least 3 or 4.

## Tested devices

- [ ] Physical
- [x] Emulator
- OS version(s): 12.

## Checklist

- [ ] Changes has been tested on an Android device or Android emulator with API 21
- [ ] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#accessibility
- [x] Pull request is based on the develop branch
- [x] Pull request includes a new file under ./changelog.d. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#changelog
- [ ] Pull request includes screenshots or videos if containing UI changes
- [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [x] You've made a self review of your PR
- [ ] If you have modified the screen flow, or added new screens to the application, you have updated the test [UiAllScreensSanityTest.allScreensTest()](https://github.com/vector-im/element-android/blob/main/vector/src/androidTest/java/im/vector/app/ui/UiAllScreensSanityTest.kt#L73)

### CODE REVIEW

File: vector/src/main/java/im/vector/app/features/invite/InviteUsersToRoomViewModel.kt [hunk 1]
```diff
@@ -63,11 +65,9 @@ class InviteUsersToRoomViewModel @AssistedInject constructor(
                             is PendingSelection.UserPendingSelection     -> room.membershipService().invite(user.user.userId, null)
                             is PendingSelection.ThreePidPendingSelection -> room.membershipService().invite3pid(user.threePid)
                         }
-                    }
-                    .catch { cause ->
-                        _viewEvents.post(InviteUsersToRoomViewEvents.Failure(cause))
-                    }
-                    .collect {
+                    }.onCompletion { error ->
```
Comment (jmartinesp) [inline vector/src/main/java/im/vector/app/features/invite/InviteUsersToRoomViewModel.kt:68]: It seems like ordering here is very important. If we use `catch` before `onCompletion`,  the possible error value that `onCompletion` can receive will always be null and we won't be able to distinguish between successful and unsuccessful results.

File: vector/src/main/java/im/vector/app/features/invite/InviteUsersToRoomViewModel.kt [hunk 2]
```diff
@@ -87,6 +87,9 @@ class InviteUsersToRoomViewModel @AssistedInject constructor(
                         }
                         _viewEvents.post(InviteUsersToRoomViewEvents.Success(successMessage))
                     }
+                    .catch { cause ->
+                        _viewEvents.post(InviteUsersToRoomViewEvents.Failure(cause))
+                    }.collect()
```
Comment (bmarty) [inline vector/src/main/java/im/vector/app/features/invite/InviteUsersToRoomViewModel.kt:92]: The other change in #6107 was to replace this by `.launchIn(viewModelScope)` and remove the first line `viewModelScope.launch {`. Did you see it? Maybe it was not working as expected?

File: vector/src/main/java/im/vector/app/features/invite/InviteUsersToRoomViewModel.kt (hunk 1 above)
Comment (bmarty) [reply vector/src/main/java/im/vector/app/features/invite/InviteUsersToRoomViewModel.kt:68]: Good to know, thanks!

File: vector/src/main/java/im/vector/app/features/invite/InviteUsersToRoomViewModel.kt (hunk 2 above)
Comment (jmartinesp) [reply vector/src/main/java/im/vector/app/features/invite/InviteUsersToRoomViewModel.kt]: I reverted that while trying some alternatives using `.collect()` and I forgot to set back the `.launchIn(...)` call. It should be fixed now.

**Review by bmarty — APPROVED** [review]
