### PR TITLE
Editing: default to `MessageContent.body` when no `formattedBody` is present

### LINKED ISSUE #7574: WYSIWYG composer some times not show edited text
### Steps to reproduce

1. select previous writed message in room
2. select "edit message"
3. in WYSIWYG composer not see edited text

This is reproduce some times (time to time).

Screenshot_2022-11-13-14-36-32-26_759d22c01f61b30a3a2e41e7176310a8

#### What did you expect?
If user select "edit message" - edited message always must copy in compose

#### What happened instead?
Text not alwasy copy to compose

### Your phone model

OnePluse 8t

### Operating system version

Android 12

### Application version and app store

element andrid 1.5.7

### Homeserver

synapse 1.50.2+buster1

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

### PR DESCRIPTION
**Pull request by jmartinesp**
## Type of change

- [ ] Feature
- [x] Bugfix: SDK
- [ ] Technical
- [ ] Other :

## Content

When user wants to edit a message in the RTE and no `formattedBody` is present, just default to the `body` property instead.

## Motivation and context

FIxes #7574 .

## Tests

- Make sure RTE is disabled in Labs (it's disabled by default). Markdown conversion should be disabled too.
- Write a message using the default editor, in plain text.
- Enable RTE in Labs.
- Edit the message using the RTE. The contents of the message should be in the editor now.

## Tested devices

- [ ] Physical
- [X] Emulator
- OS version(s): 13

## Checklist

- [ ] Changes has been tested on an Android device or Android emulator with API 21
- [ ] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#accessibility
- [x] Pull request is based on the develop branch
- [x] Pull request includes a new file under ./changelog.d. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#changelog
- [ ] Pull request includes screenshots or videos if containing UI changes
- [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [x] You've made a self review of your PR
- [ ] If you have modified the screen flow, or added new screens to the application, you have updated the test [UiAllScreensSanityTest.allScreensTest()](https://github.com/vector-im/element-android/blob/main/vector/src/androidTest/java/im/vector/app/ui/UiAllScreensSanityTest.kt#L73)

### CODE REVIEW

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/timeline/TimelineEvent.kt [hunk 1]
```diff
@@ -184,7 +184,7 @@ fun TimelineEvent.isRootThread(): Boolean {
 fun TimelineEvent.getTextEditableContent(formatted: Boolean): String {
```
Comment (mnaturel) [inline matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/timeline/TimelineEvent.kt:184]: I struggle to understand the purpose of the `formatted` parameter.
Is it a necessary parameter, could we write?
`val lastContentBody = (lastMessageContent as? MessageContentWithFormattedBody)?.formattedBody ?: lastMessageContent?.body.orEmpty()`

If necessary, could you add some KDoc about it?

Comment (mnaturel) [reply matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/timeline/TimelineEvent.kt:184]: Okay I see. Thanks for explaining!

**Review by mnaturel — APPROVED** [review]
LGTM.
