### PR TITLE
Sync: fix initial sync retry

### LINKED ISSUE #2632: Initial sync is not retried correctly when there is some network error.
SyncService should be reschedule asap when there is a timeout exception and/or during initial sync.

### PR DESCRIPTION
**Pull request by ganfra**
Fixes #2632

### CODE REVIEW

File: vector/src/main/java/im/vector/app/core/services/VectorSyncService.kt [hunk 1]
```diff
@@ -93,12 +89,12 @@ class VectorSyncService : SyncService() {
...
 
     override fun onRescheduleAsked(sessionId: String, isInitialSync: Boolean, timeout: Int, delay: Int) {
-        reschedule(sessionId, timeout, delay)
+        rescheduleSyncService(sessionId, timeout, delay)
     }
 
     override fun onNetworkError(sessionId: String, isInitialSync: Boolean, timeout: Int, delay: Int) {
         Timber.d("## Sync: A network error occured during sync")
-        val uploadWorkRequest: WorkRequest =
+        val rescheduleSyncWorkRequest: WorkRequest =
```
Comment (bmarty) [inline vector/src/main/java/im/vector/app/core/services/VectorSyncService.kt:97]: thx :)

**Review by bmarty — APPROVED** [review]
LGTM, maybe @BillCarsonFr could have a look too

**Review by BillCarsonFr — APPROVED** [review]
LGTM
