### PR TITLE
Show mxto bottom sheet when tapping invite notification

### LINKED ISSUE #4043: Spaces invitation system notifications don't take me to the join space toast
### Steps to reproduce

1. Be logged into your account on your Android phone
2. Receive system notification (e.g. from email invite to your registered address)
 -> See the notification pop-up
3. Click the notification
 -> App opens on previous view, not showing notification

### What did you expect?
Join space toast

### What happened?
Previous view of the app

https://photos.app.goo.gl/KNbAKmPJZiCAvrhKA

### Your phone model

_No response_

### Operating system version

_No response_

### Application version and app store

Spaces release test version

### Homeserver

_No response_

### Have you submitted a rageshake?

No

### PR DESCRIPTION
**Pull request by BillCarsonFr**
Fixes #4043 

Tapping on a space invite notification, was only opening the app in the home screen.
Was acceptable for rooms as the invite would show up on top of the roomlist.

But now with spaces we need to do more (the space invite will only appear in the left drawer).
So with this PR, on notification tap a bottomsheet will appear with preview and join button:
image

Will work also for rooms

### CODE REVIEW

File: vector/src/main/java/im/vector/app/features/home/HomeActivity.kt [hunk 1]
```diff
@@ -422,9 +428,17 @@ class HomeActivity :
 
     override fun onNewIntent(intent: Intent?) {
         super.onNewIntent(intent)
-        if (intent?.getParcelableExtra<HomeActivityArgs>(MvRx.KEY_ARG)?.clearNotification == true) {
+        val parcelableExtra = intent?.getParcelableExtra<HomeActivityArgs>(MvRx.KEY_ARG)
+        if (parcelableExtra?.clearNotification == true) {
             notificationDrawerManager.clearAllEvents()
         }
+        if (parcelableExtra?.inviteNotificationRoomId != null) {
+            activeSessionHolder.getSafeActiveSession()
```
Comment (ouchadam) [inline vector/src/main/java/im/vector/app/features/home/HomeActivity.kt:436]: out interest, is there a convention around formatting/autoformatter? I notice this call has the chain across new lines but the [other](https://github.com/vector-im/element-android/pull/4044/files#diff-a44e22f42d574ac91aeeec4eb708fa7a9e054daa34e234da5ff92bf06d17fa5eR234) is on one line

File: vector/src/main/java/im/vector/app/features/home/HomeActivity.kt [hunk 2]
```diff
@@ -229,6 +230,11 @@ class HomeActivity :
         if (args?.clearNotification == true) {
             notificationDrawerManager.clearAllEvents()
         }
+        if (args?.inviteNotificationRoomId != null) {
+            activeSessionHolder.getSafeActiveSession()?.permalinkService()?.createPermalink(args.inviteNotificationRoomId)?.let {
```
Comment (ouchadam) [inline vector/src/main/java/im/vector/app/features/home/HomeActivity.kt:234]: what happens if the session isn't ready, is it something we need to worry about?

Comment (BillCarsonFr) [reply vector/src/main/java/im/vector/app/features/home/HomeActivity.kt:234]: It would be ready (done early in the application). Active session is optional because you might not be yet logged in, and the injection is done via dagger. I should have done this via view model TBH (there i'd have the session)

File: vector/src/main/java/im/vector/app/features/home/HomeActivity.kt (hunk 1 above)
Comment (BillCarsonFr) [reply vector/src/main/java/im/vector/app/features/home/HomeActivity.kt:436]: Formating rules files are in .idea/codeStyles/, you can read https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md  for all details

**Review by ouchadam — APPROVED** [review]

File: vector/src/main/java/im/vector/app/features/home/HomeActivity.kt (hunk 1 above)
Comment (ouchadam) [reply vector/src/main/java/im/vector/app/features/home/HomeActivity.kt:436]: ah perfect, thanks!

Comment (BillCarsonFr) [reply vector/src/main/java/im/vector/app/features/home/HomeActivity.kt:436]: @ouchadam sorry wrong link https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md

**Review by bmarty — APPROVED** [review]
LGTM Thanks
