### PR TITLE
[Location Share] - Adding missing prefix "u=" for uncertainty in geo URI (PSF-945)

### LINKED ISSUE #6375: [Location Share] - Geo URI not corresponding to specifications
### Steps to reproduce

The geo URI specifications [RFC 5870](https://datatracker.ietf.org/doc/html/rfc5870) describes that uncertainty should be prefix with "u=".

The application does not send the uncertainty value with this prefix when sharing a location (static or live).

### Outcome

The code should be updated to conform with the specifications.

### Your phone model

_No response_

### Operating system version

_No response_

### Application version and app store

_No response_

### Homeserver

_No response_

### Will you send logs?

No

### Are you willing to provide a PR?

Yes

### PR DESCRIPTION
**Pull request by mnaturel**
## Type of change

- [ ] Feature
- [x] Bugfix
- [ ] Technical
- [ ] Other :

## Content

Adding a missing prefix "u=" for uncertainty value when building a geo uri.

## Motivation and context

Closes #6375 

## Tests

- Enable live location share flag in labs settings
- Share a static location (user or pinned) in a room
- Check the location is correctly shared
- Start a live location share in a room
- Check the live is correctly running in the room
- Stop the live
- Check the live is correctly ended

## Tested devices

- [ ] Physical
- [x] Emulator
- OS version(s): Android 11

## Checklist

- [ ] Changes has been tested on an Android device or Android emulator with API 21
- [ ] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#accessibility
- [x] Pull request is based on the develop branch
- [x] Pull request includes a new file under ./changelog.d. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#changelog
- [ ] Pull request includes screenshots or videos if containing UI changes
- [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [x] You've made a self review of your PR
- [ ] If you have modified the screen flow, or added new screens to the application, you have updated the test [UiAllScreensSanityTest.allScreensTest()](https://github.com/vector-im/element-android/blob/main/vector/src/androidTest/java/im/vector/app/ui/UiAllScreensSanityTest.kt#L73)

### CODE REVIEW

**Review by ouchadam — APPROVED** [review]

**Review by Claire1817 — APPROVED** [review]
LGTM :)

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/model/message/LocationInfo.kt [hunk 1]
```diff
@@ -22,7 +22,7 @@ import com.squareup.moshi.JsonClass
 @JsonClass(generateAdapter = true)
 data class LocationInfo(
         /**
-         * Required. RFC5870 formatted geo uri 'geo:latitude,longitude;uncertainty' like 'geo:40.05,29.24;30' representing this location.
+         * Required. RFC5870 formatted geo uri 'geo:latitude,longitude;uncertainty' like 'geo:40.05,29.24;u=30' representing this location.
```
Comment (bmarty) [inline matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/model/message/LocationInfo.kt:25]: I would update also the pseudo code to

```suggestion
         * Required. RFC5870 formatted geo uri 'geo:latitude,longitude;u=uncertainty' like 'geo:40.05,29.24;u=30' representing this location.
```

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/model/message/MessageLocationContent.kt [hunk 2]
```diff
@@ -35,7 +35,7 @@ data class MessageLocationContent(
         @Json(name = "body") override val body: String,
 
         /**
-         * Required. RFC5870 formatted geo uri 'geo:latitude,longitude;uncertainty' like 'geo:40.05,29.24;30' representing this location.
+         * Required. RFC5870 formatted geo uri 'geo:latitude,longitude;uncertainty' like 'geo:40.05,29.24;u=30' representing this location.
```
Comment (bmarty) [inline matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/model/message/MessageLocationContent.kt:38]: same remark

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/LocalEchoEventFactory.kt [hunk 3]
```diff
@@ -708,7 +708,7 @@ internal class LocalEchoEventFactory @Inject constructor(
     }
 
     /**
-     * Returns RFC5870 formatted geo uri 'geo:latitude,longitude;uncertainty' like 'geo:40.05,29.24;30'
+     * Returns RFC5870 formatted geo uri 'geo:latitude,longitude;u=uncertainty' like 'geo:40.05,29.24;u=30'
```
Comment (bmarty) [inline matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/LocalEchoEventFactory.kt:711]: it's done here!

File: vector/src/test/java/im/vector/app/features/location/LocationDataTest.kt [hunk 4]
```diff
@@ -28,19 +28,22 @@ import org.matrix.android.sdk.api.session.room.model.message.MessageLocationCont
...
                 LocationData(latitude = 12.34, longitude = 56.78, uncertainty = null)
         // Space are ignored (trim)
-        parseGeo("geo: 12.34,56.78;13.56") shouldBeEqualTo
+        parseGeo("geo: 12.34,56.78;u=13.56") shouldBeEqualTo
+                LocationData(latitude = 12.34, longitude = 56.78, uncertainty = 13.56)
+        parseGeo("geo:12.34,56.78; u=13.56") shouldBeEqualTo
                 LocationData(latitude = 12.34, longitude = 56.78, uncertainty = 13.56)
-        parseGeo("geo:12.34,56.78; 13.56") shouldBeEqualTo
+        // missing "u=" for uncertainty is ignored
+        parseGeo("geo:12.34,56.78;13.56") shouldBeEqualTo
```
Comment (bmarty) [inline vector/src/test/java/im/vector/app/features/location/LocationDataTest.kt:46]: I would have create a dedicated test for this case, since this is not a fully valid case. (but we are already testing invalid uncertainty here :/)

File: vector/src/test/java/im/vector/app/features/location/LocationDataTest.kt [hunk 5]
```diff
@@ -77,7 +80,7 @@ class LocationDataTest {
 
     @Test
     fun unstablePrefixTest() {
-        val geoUri = "geo :12.34,56.78;13.56"
+        val geoUri = "geo :12.34,56.78;u=13.56"
```
Comment (bmarty) [inline vector/src/test/java/im/vector/app/features/location/LocationDataTest.kt:83]: I think there is a (not new) problem here; the line should be

```suggestion
        val geoUri = "geo:12.34,56.78;u=13.56"
```

This is not a big deal since we are comparing the string. But just for clarity. Or even just use some mockk data like

```kotlin
        val geoUri = "theGeoUri"
```

**Review by bmarty — COMMENTED** [review]
My 2 cents

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/model/message/LocationInfo.kt (hunk 1 above)
Comment (mnaturel) [reply matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/model/message/LocationInfo.kt]: Thanks, it seems I missed some comment updates. Fixed in [5fa3b3f](https://github.com/vector-im/element-android/pull/6376/commits/5fa3b3f16862b1f4b43e6f017faa372b5fd29ed7)

File: vector/src/test/java/im/vector/app/features/location/LocationDataTest.kt (hunk 5 above)
Comment (mnaturel) [reply vector/src/test/java/im/vector/app/features/location/LocationDataTest.kt]: You are right. I change the value of the uri to not use the pattern as it is not mandatory to have it for the purpose of this test. See: [1df71d3](https://github.com/vector-im/element-android/pull/6376/commits/1df71d31e20afff89d844737d140ec6426b98e1c)

File: vector/src/test/java/im/vector/app/features/location/LocationDataTest.kt (hunk 4 above)
Comment (bmarty) [reply vector/src/test/java/im/vector/app/features/location/LocationDataTest.kt:50]: Thanks!

**Comment by bmarty** [comment]
Thanks for the latest update @mnaturel !
