### PR TITLE
[Location Share] Render fallback UI when map fails to load (PSG-607)

### LINKED ISSUE #6711: [Location Share] Render fallback UI when map fails to load
#### What would you like to do?
Show a specific error when map fails to load.

#### Why would you like to do it?
In some cases (e.g. the home server is not configured well for map style url), the maps may fail to load.

#### How would you like to achieve it?
Add a listener on map loading error.
For UI, see https://www.figma.com/file/uthEK6xuo9hSQRdWvPAre5/Location-Sharing?node-id=2302%3A64561

### Have you considered any alternatives?

_No response_

### Additional context

_No response_

### Are you willing to provide a PR?

Yes

### PR DESCRIPTION
**Pull request by mnaturel**
## Type of change

- [x] Feature
- [ ] Bugfix
- [ ] Technical
- [ ] Other :

## Content

Introducing a custom view to be displayed when a map fails to load.

## Motivation and context

Closes #6711 

## Tests

In order to fake errors, the easiest way is to edit `UrlMapProvider` by providing a wrong map api key.

- Start a live location share or share static location

## Tested devices

- [ ] Physical
- [x] Emulator
- OS version(s): Android 11

## Checklist

- [ ] Changes has been tested on an Android device or Android emulator with API 21
- [x] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#accessibility
- [x] Pull request is based on the develop branch
- [x] Pull request includes a new file under ./changelog.d. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#changelog
- [x] Pull request includes screenshots or videos if containing UI changes
- [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [x] You've made a self review of your PR
- [ ] If you have modified the screen flow, or added new screens to the application, you have updated the test [UiAllScreensSanityTest.allScreensTest()](https://github.com/vector-im/element-android/blob/main/vector/src/androidTest/java/im/vector/app/ui/UiAllScreensSanityTest.kt#L73)

### CODE REVIEW

File: vector/src/main/java/im/vector/app/features/location/LocationSharingViewModel.kt [hunk 1]
```diff
@@ -211,6 +212,10 @@ class LocationSharingViewModel @AssistedInject constructor(
         )
     }
 
+    private fun handleShowMapLoadingError() {
+        setState { copy(loadingMapHasFailed = true) }
+    }
+
```
Comment (Florian14) [inline vector/src/main/java/im/vector/app/features/location/LocationSharingViewModel.kt:218]: Do you confirm that if there is an error for any reason, the map will never be renderer with success later (so we should reset this field)?

File: vector/src/main/java/im/vector/app/features/location/live/map/LiveLocationMapViewFragment.kt [hunk 2]
```diff
@@ -141,6 +147,13 @@ class LiveLocationMapViewFragment @Inject constructor() : VectorBaseFragment<Fra
         }
     }
 
+    private fun listenMapLoadingError(mapView: MapView) {
+        this.mapView = mapView
```
Comment (Florian14) [inline vector/src/main/java/im/vector/app/features/location/live/map/LiveLocationMapViewFragment.kt:151]: I think it would make more sense to do it in setupMap

File: vector/src/main/java/im/vector/app/features/location/live/map/LiveLocationMapViewState.kt [hunk 3]
```diff
@@ -27,7 +27,8 @@ data class LiveLocationMapViewState(
         /**
          * Map to keep track of symbol ids associated to each user Id.
          */
-        val mapSymbolIds: Map<String, Long> = emptyMap()
+        val mapSymbolIds: Map<String, Long> = emptyMap(),
+        val loadingMapHasFailed: Boolean = false
```
Comment (Florian14) [inline vector/src/main/java/im/vector/app/features/location/live/map/LiveLocationMapViewState.kt:31]: maybe add a trailing comma

File: vector/src/main/java/im/vector/app/features/location/live/map/LiveLocationMapViewFragment.kt [hunk 4]
```diff
@@ -71,11 +71,13 @@ class LiveLocationMapViewFragment @Inject constructor() : VectorBaseFragment<Fra
     private val viewModel: LiveLocationMapViewModel by fragmentViewModel()
 
     private var mapboxMap: WeakReference<MapboxMap>? = null
+    private var mapView: MapView? = null
```
Comment (Florian14) [inline vector/src/main/java/im/vector/app/features/location/live/map/LiveLocationMapViewFragment.kt:74]: Why don't you use WeakReference for this one?

**Review by Florian14 — COMMENTED** [review]
Just some small feedback, the screenshots look great

File: vector/src/main/java/im/vector/app/features/location/live/map/LiveLocationMapViewFragment.kt (hunk 2 above)
Comment (mnaturel) [reply vector/src/main/java/im/vector/app/features/location/live/map/LiveLocationMapViewFragment.kt:151]: It is actually called in `setupMap()`: `(mapFragment.view as? MapView)?.let(::listenMapLoadingError)` but it can only be called inside the callback of `getMapAsync` to have access to the `MapView`. What was you suggestion?

Comment (Florian14) [reply vector/src/main/java/im/vector/app/features/location/live/map/LiveLocationMapViewFragment.kt:151]: Just to move it outside this function, I think it is more logical to store the map reference in the `setupMap` method instead of when listening to the map loading errors. (Even if it will not change the behaviour)

File: vector/src/main/java/im/vector/app/features/location/live/map/LiveLocationMapViewFragment.kt (hunk 4 above)
Comment (mnaturel) [reply vector/src/main/java/im/vector/app/features/location/live/map/LiveLocationMapViewFragment.kt:74]: In fact I am not a big fan of `WeakReference`, I prefer to explicitely dereferencing the value when needed. Like in this case, I reset the view to null in `onDestroyView`. Do you think I should switch to a `WeakReference`?

Comment (Florian14) [reply vector/src/main/java/im/vector/app/features/location/live/map/LiveLocationMapViewFragment.kt:74]: I don't have a big opinion on this, I was asking because I observed the use of the `WeakReference` in the other fragments

File: vector/src/main/java/im/vector/app/features/location/live/map/LiveLocationMapViewFragment.kt (hunk 2 above)
Comment (mnaturel) [reply vector/src/main/java/im/vector/app/features/location/live/map/LiveLocationMapViewFragment.kt:151]: Okay I see, thanks. I agree I will update it.

File: vector/src/main/java/im/vector/app/features/location/live/map/LiveLocationMapViewState.kt (hunk 3 above)
Comment (mnaturel) [reply vector/src/main/java/im/vector/app/features/location/live/map/LiveLocationMapViewState.kt]: Fixed. See [3954465](https://github.com/vector-im/element-android/pull/6712/commits/3954465aadc6e85d0da82828378ad0a68d9f210e)

File: vector/src/main/java/im/vector/app/features/location/live/map/LiveLocationMapViewFragment.kt (hunk 2 above)
Comment (mnaturel) [reply vector/src/main/java/im/vector/app/features/location/live/map/LiveLocationMapViewFragment.kt]: Updated see [3f7f724](https://github.com/vector-im/element-android/pull/6712/commits/3f7f72413815e5f8137641727ad1dc73afa0949c)

File: vector/src/main/java/im/vector/app/features/location/LocationSharingViewModel.kt (hunk 1 above)
Comment (mnaturel) [reply vector/src/main/java/im/vector/app/features/location/LocationSharingViewModel.kt:218]: Yes, I confirm. I checked and the error is triggered when calling `MapboxMap.setStyle()` and it is only called once in `onViewCreated` in the fragments with maps. I moved the setup from `onResume()` in `LiveLocationMapViewFragment`. See [3f7f724](https://github.com/vector-im/element-android/pull/6712/commits/3f7f72413815e5f8137641727ad1dc73afa0949c) It seems, it was done in `onResume()` previously to fix missing markers after rotating the device but I could not reproduce this issue after update.

**Review by Florian14 — APPROVED** [review]
LGTM considering your [answer](https://github.com/vector-im/element-android/pull/6712#discussion_r936796625)
