### PR TITLE
Change default power to invite in private space + setting

### LINKED ISSUE #3951: "Non-Admin" user able to invite others to Private Space (by default)
### Steps to reproduce

1. User A: Created Private Space
2. Invited User B to Private Space

3. User B accepted invite to Private Space
2. User B able to invite other users to Private Space

### What did you expect?

Expected User B to *not* have permission access to invite others to Space.
Would expect User A to explicitly grant higher levels of access to User B (or all) in order for User B to invite others to Private Space.

### What happened?

User B was able to invite others to Space by default

### Your phone model

_No response_

### Operating system version

_No response_

### Application version and app store

https://buildkite.com/organizations/matrix-dot-org/pipelines/element-android/builds/3224/jobs/a1fe572d-8a7b-4406-8a0f-37f4c9ff4787/artifacts/30990f61-8f7d-4dc6-af1e-340765110cc6

### Homeserver

_No response_

### Have you submitted a rageshake?

No

### PR DESCRIPTION
**Pull request by BillCarsonFr**
Fixes #3951 

Change default power level to invite in private room to 50 (Moderator)

Also adding settings UX to change it 
image

### CODE REVIEW

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/space/DefaultSpaceService.kt [hunk 1]
```diff
@@ -77,7 +78,7 @@ internal class DefaultSpaceService @Inject constructor(
             if (isPublic) {
                 this.roomAliasName = roomAliasLocalPart
                 this.powerLevelContentOverride = (powerLevelContentOverride ?: PowerLevelsContent()).copy(
-                        invite = 0
+                        invite = if (isPublic) 0 else Role.Moderator.value
```
Comment (bmarty) [inline matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/space/DefaultSpaceService.kt:81]: Can you use `Role.Default.value` instead of `0`?

File: vector/src/main/java/im/vector/app/features/roomprofile/permissions/EditablePermission.kt [hunk 2]
```diff
@@ -70,7 +77,7 @@ sealed class EditablePermission(@StringRes val labelResId: Int) {
 
     class UpgradeTheRoom : EventTypeEditablePermission(
             EventType.STATE_ROOM_TOMBSTONE,
-            R.string.room_permissions_upgrade_the_room
+            R.string.room_permissions_upgrade_the_space
```
Comment (bmarty) [inline vector/src/main/java/im/vector/app/features/roomprofile/permissions/EditablePermission.kt:80]: I guess you wanted to write:
```kotlin
R.string.room_permissions_upgrade_the_room,
R.string.room_permissions_upgrade_the_space
```

File: vector/src/main/java/im/vector/app/features/spaces/create/CreateSpaceViewModelTask.kt [hunk 3]
```diff
@@ -60,13 +65,26 @@ class CreateSpaceViewModelTask @Inject constructor(
...
-                    params.spaceAlias
-            )
+            session.spaceService().createSpace(CreateSpaceParams().apply {
+                this.name = params.spaceName
+                this.topic = params.spaceTopic
+                this.avatarUri = params.spaceAvatar
+                if (params.isPublic) {
+                    this.roomAliasName = params.spaceAlias
+                    this.powerLevelContentOverride = (powerLevelContentOverride ?: PowerLevelsContent()).copy(
+                            invite = 0
```
Comment (bmarty) [inline vector/src/main/java/im/vector/app/features/spaces/create/CreateSpaceViewModelTask.kt:75]: `Role.Default.value`

File: vector/src/main/java/im/vector/app/features/spaces/create/CreateSpaceViewModelTask.kt [hunk 4]
```diff
@@ -60,13 +65,26 @@ class CreateSpaceViewModelTask @Inject constructor(
...
+                    )
+                    this.preset = CreateRoomPreset.PRESET_PUBLIC_CHAT
+                    this.historyVisibility = RoomHistoryVisibility.WORLD_READABLE
+                    this.guestAccess = GuestAccess.CanJoin
+                } else {
+                    this.preset = CreateRoomPreset.PRESET_PRIVATE_CHAT
+                    visibility = RoomDirectoryVisibility.PRIVATE
```
Comment (bmarty) [inline vector/src/main/java/im/vector/app/features/spaces/create/CreateSpaceViewModelTask.kt:82]: why this one does not have `this.`?

File: vector/src/main/java/im/vector/app/features/spaces/manage/SpaceManagedSharedAction.kt [hunk 5]
```diff
@@ -25,4 +25,5 @@ sealed class SpaceManagedSharedAction : VectorViewModelAction {
     object CreateRoom : SpaceManagedSharedAction()
     object ManageRooms : SpaceManagedSharedAction()
     object OpenSpaceAliasesSettings : SpaceManagedSharedAction()
+    object OpenRoomPermissionSettings : SpaceManagedSharedAction()
```
Comment (bmarty) [inline vector/src/main/java/im/vector/app/features/spaces/manage/SpaceManagedSharedAction.kt:28]: Maybe you have hesitated with `OpenSpacePermissionSettings`?

**Review by bmarty — CHANGES_REQUESTED** [review]
One small mistake, else LGTM

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/space/DefaultSpaceService.kt (hunk 1 above)
Comment (BillCarsonFr) [reply matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/space/DefaultSpaceService.kt:81]: Done

File: vector/src/main/java/im/vector/app/features/roomprofile/permissions/EditablePermission.kt (hunk 2 above)
Comment (BillCarsonFr) [reply vector/src/main/java/im/vector/app/features/roomprofile/permissions/EditablePermission.kt:80]: Thx, good catch

File: vector/src/main/java/im/vector/app/features/spaces/create/CreateSpaceViewModelTask.kt (hunk 4 above)
Comment (BillCarsonFr) [reply vector/src/main/java/im/vector/app/features/spaces/create/CreateSpaceViewModelTask.kt:82]: done

File: vector/src/main/java/im/vector/app/features/spaces/manage/SpaceManagedSharedAction.kt (hunk 5 above)
Comment (BillCarsonFr) [reply vector/src/main/java/im/vector/app/features/spaces/manage/SpaceManagedSharedAction.kt:28]: Done

**Review by bmarty — APPROVED** [review]
Thanks for the update
