### PR TITLE
Missing translations on "replyTo" messages (PSG-978)

### LINKED ISSUE #7555: Missing translations on "replyTo" messages
### Steps to reproduce

When rendering "replyTo" text messages in the timeline of a room, the text messages are in English and not translated in the language set in preferences.

#### What did you expect?
"ReplyTo" messages should be translated.

#### What happened instead?
"ReplyTo" messages are not translated.

To fix this, translation should happen on the app side (not in SDK side) when rendering "ReplyTo" messages.

### Your phone model

_No response_

### Operating system version

_No response_

### Application version and app store

_No response_

### Homeserver

_No response_

### Will you send logs?

No

### Are you willing to provide a PR?

Yes

### PR DESCRIPTION
**Pull request by mnaturel**
## Type of change

- [ ] Feature
- [x] Bugfix
- [ ] Technical
- [ ] Other :

## Content

Adding translations for "replyTo" events message on application side.
The description parameter exposed in SDK API for the start of a live location has also been removed to avoid introducing translated text in Matrix events.

## Motivation and context

Closes #7555 

## Tests

- Go to a room (encrypted or not)
- Send different type of messages
- Reply to these messages
- Check the replies are well rendered (right now they are not translated: we should wait for Weblate sync to see the changes)

## Tested devices

- [ ] Physical
- [x] Emulator
- OS version(s): Android 11

## Checklist

- [ ] Changes has been tested on an Android device or Android emulator with API 21
- [ ] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#accessibility
- [x] Pull request is based on the develop branch
- [x] Pull request includes a new file under ./changelog.d. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#changelog
- [x] Pull request includes screenshots or videos if containing UI changes
- [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [x] You've made a self review of your PR
- [ ] If you have modified the screen flow, or added new screens to the application, you have updated the test [UiAllScreensSanityTest.allScreensTest()](https://github.com/vector-im/element-android/blob/main/vector/src/androidTest/java/im/vector/app/ui/UiAllScreensSanityTest.kt#L73)

### CODE REVIEW

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/events/model/Event.kt [hunk 1]
```diff
@@ -443,7 +447,7 @@ fun Event.isInvitation(): Boolean = type == EventType.STATE_ROOM_MEMBER &&
         content?.toModel<RoomMemberContent>()?.membership == Membership.INVITE
 
 fun Event.getPollContent(): MessagePollContent? {
-    return content.toModel<MessagePollContent>()
+    return getDecryptedContent().toModel<MessagePollContent>()
```
Comment (mnaturel) [inline matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/events/model/Event.kt:450]: It seems to not work well in non encrypted room. When testing in a non encrypted room, I could not see the poll question in the `replyTo` message.

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/events/model/Event.kt [hunk 2]
```diff
@@ -228,11 +229,14 @@ data class Event(
...
             isReplyRenderedInThread() || isQuote() -> ContentUtils.extractUsefulTextFromReply(text)
             isFileMessage() -> "sent a file."
+            isVoiceMessage() -> "sent a voice message."
             isAudioMessage() -> "sent an audio file."
             isImageMessage() -> "sent an image."
             isVideoMessage() -> "sent a video."
-            isSticker() -> "sent a sticker"
+            isSticker() -> "sent a sticker."
             isPoll() -> getPollQuestion() ?: "created a poll."
+            isLiveLocation() -> "Live location."
```
Comment (Johennes) [inline matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/events/model/Event.kt:238]: This seems to be a noun whereas all the others are actions? Maybe this could be made similar to the message below?

File: vector/src/test/java/im/vector/app/features/home/room/detail/timeline/render/ProcessBodyOfReplyToEventUseCaseTest.kt [hunk 3]
```diff
@@ -0,0 +1,268 @@
...
+
+private const val A_ROOM_ID = "room-id"
+private const val AN_EVENT_ID = "event-id"
+private const val A_REPLY_TO_EVENT_MATRIX_FORMATTED_BODY =
+        "<mx-reply>" +
+                "<blockquote>" +
+                "<a href=\"matrixToLink\">In reply to</a> " +
+                "<a href=\"matrixToLink\">@user:matrix.org</a>" +
+                "<br />" +
+                "Message content" +
```
Comment (Johennes) [inline vector/src/test/java/im/vector/app/features/home/room/detail/timeline/render/ProcessBodyOfReplyToEventUseCaseTest.kt:52]: Maybe a stupid question but could a `<br/>` also occur inside of this content?

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/events/model/Event.kt (hunk 2 above)
Comment (mnaturel) [reply matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/events/model/Event.kt:238]: Yes, I know. I aligned the string to what we have on other platforms and what was required by the design team. If we want to change, we would need to discuss with design team and update other platforms as well.

File: vector/src/test/java/im/vector/app/features/home/room/detail/timeline/render/ProcessBodyOfReplyToEventUseCaseTest.kt (hunk 3 above)
Comment (mnaturel) [reply vector/src/test/java/im/vector/app/features/home/room/detail/timeline/render/ProcessBodyOfReplyToEventUseCaseTest.kt:52]: Hum I don't think so but just in case, I will update to look for the index of the first occurence of breaking line.

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/events/model/Event.kt (hunk 2 above)
Comment (Johennes) [reply matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/events/model/Event.kt:238]: Oh ok. In that case, let's leave it as is for now and not block your PR on this. Would you mind logging a short ticket about this in PSG-829? Then we can discuss whether or not to change this separately.

Comment (mnaturel) [reply matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/events/model/Event.kt:238]: Yes done.

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/events/model/Event.kt (hunk 1 above)
Comment (mnaturel) [reply matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/events/model/Event.kt]: We should use `getClearContent()` instead: fixed in [4a65e11](https://github.com/vector-im/element-android/pull/7566/commits/4a65e1153abcd25a8927340cc3f20c396c9d2ef1)

**Review by fedrunov — APPROVED** [review]
LGTM
