### PR TITLE
FTUE - Focus errors showing on wrong page

### LINKED ISSUE #6737: UserID error unexpectedly showing up during account creation
### Steps to reproduce

Edit server
1. In the account creation screen
3. Focus the username field
4. Tap `EDIT`
5. Notice the user id error

Back flow
1. In the account creation screen
3. Focus the username field
4. Press back to leave the screen
5. Notice the user id error popup

#### What did you expect?
No error to be displayed

#### What happened instead?
Errors were unexpectedly displayed

| EDIT SERVER | BACK FLOW |
| --- | --- |
before-user-id-server|before-user-id-exit

### Your phone model

_No response_

### Operating system version

_No response_

### Application version and app store

1.4.31

### Homeserver

_No response_

### Will you send logs?

No

### Are you willing to provide a PR?

No

### PR DESCRIPTION
**Pull request by ouchadam**
## Type of change

- [ ] Feature
- [x] Bugfix
- [ ] Technical
- [ ] Other :

## Content

- Ensures we only execute _lost focus_ checks whilst the screen is still in view
- Adds missing view ids to the input field edit text views 

## Motivation and context

Fixes #6737 

When the username field loses focus we're doing a user name availability check, however this check was also being triggered when navigating away from the page (such as pressing EDIT or back) causing the next page to display the availability result.

Fixed by only checking for availability whilst the username field is visible.

## Screenshots / GIFs

| BEFORE | AFTER |
| --- | --- |
before-empty-user|after-empty-user
before-username|after-username

## Tests

- Select the username field within account creation
- Tap `EDIT`
- Notice an empty user id error

## Tested devices

- [x] Physical
- [ ] Emulator
- OS version(s):

### CODE REVIEW

File: vector/src/main/java/im/vector/app/core/extensions/TextInputLayout.kt [hunk 1]
```diff
@@ -78,10 +78,15 @@ fun TextInputLayout.setOnImeDoneListener(action: () -> Unit) {
     }
 }
 
-fun TextInputLayout.setOnFocusLostListener(action: () -> Unit) {
+/**
+ * Set a listener for when the input has lost focus, such as moving to the another input field.
+ * The listener is only called when the view is in a resumed state to avoid triggers when exiting a screen.
+ */
+fun TextInputLayout.setOnFocusLostListener(lifecycleOwner: LifecycleOwner, action: () -> Unit) {
+    lifecycleOwner.lifecycle
```
Comment (Florian14) [inline vector/src/main/java/im/vector/app/core/extensions/TextInputLayout.kt:86]: not sure this line is necessary?

Comment (ouchadam) [reply vector/src/main/java/im/vector/app/core/extensions/TextInputLayout.kt]: https://github.com/vector-im/element-android/pull/6741/commits/b375dd14f781c076482c87fa81ebaa54d70db78c
