### PR TITLE
[Poll] Poll end event is not recognized (PSG-948 and PSG-949)

### LINKED ISSUE #7753: [Poll] Poll end event is not recognized
### Steps to reproduce

- Create a poll from Web client for example
- End the poll
- In the Android app, the poll stays in the opened status (still possible to vote) while it should display final result 

#### What did you expect?
When a poll is ended, UI should reflect this status.

#### What happened instead?
When a poll is ended, the poll stays opened.

### Your phone model

_No response_

### Operating system version

_No response_

### Application version and app store

_No response_

### Homeserver

_No response_

### Will you send logs?

No

### Are you willing to provide a PR?

Yes

### PR DESCRIPTION
**Pull request by mnaturel**
## Type of change

- [ ] Feature
- [x] Bugfix
- [ ] Technical
- [ ] Other :

## Content

Retrieve the related event id in poll end event using the dedicated `getRelationContent()` method to avoid misssing aggregation of this event.

## Motivation and context

Closes #7753 

## Tests

- Create a poll (open or closed) in a room from Web using account A
- Vote from web using account A
- Close the poll using account A
- Open the room from Android app using account B
- Check the poll is considered as ended and result is visible even if account B did not vote

## Tested devices

- [ ] Physical
- [x] Emulator
- OS version(s): Android 11

## Checklist

- [ ] Changes has been tested on an Android device or Android emulator with API 21
- [ ] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#accessibility
- [x] Pull request is based on the develop branch
- [x] Pull request includes a new file under ./changelog.d. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#changelog
- [ ] Pull request includes screenshots or videos if containing UI changes
- [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [x] You've made a self review of your PR
- [ ] If you have modified the screen flow, or added new screens to the application, you have updated the test [UiAllScreensSanityTest.allScreensTest()](https://github.com/vector-im/element-android/blob/main/vector/src/androidTest/java/im/vector/app/ui/UiAllScreensSanityTest.kt#L73)

### CODE REVIEW

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/aggregation/poll/DefaultPollAggregationProcessor.kt [hunk 1]
```diff
@@ -156,7 +156,7 @@ class DefaultPollAggregationProcessor @Inject constructor() : PollAggregationPro
     override fun handlePollEndEvent(session: Session, powerLevelsHelper: PowerLevelsHelper, realm: Realm, event: Event): Boolean {
         val content = event.getClearContent()?.toModel<MessageEndPollContent>() ?: return false
         val roomId = event.roomId ?: return false
-        val pollEventId = content.relatesTo?.eventId ?: return false
+        val pollEventId = (event.getRelationContent() ?: content.relatesTo)?.eventId ?: return false
```
Comment (fedrunov) [inline matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/aggregation/poll/DefaultPollAggregationProcessor.kt:159]: does `content.relatesTo` has any sense here? Won't it be returned from `event.getRelationContent()` if exists?

Comment (mnaturel) [reply matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/aggregation/poll/DefaultPollAggregationProcessor.kt:159]: Yes you are right. If `getRelationContent` returns null there is little chance `content.relatesTo` returns something. I will update.

Comment (mnaturel) [reply matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/aggregation/poll/DefaultPollAggregationProcessor.kt]: Updated here: [71df1e6](https://github.com/vector-im/element-android/pull/7757/commits/71df1e61d43782f7a181f267ab75e1f173dbbc0a)

**Review by fedrunov — APPROVED** [review]
