### PR TITLE
Determine availability of QR sign in from resolved homeserver

### LINKED ISSUE #7676: Race condition for sign in with QR preventing cross signing set up
### Steps to reproduce

1. Use a relatively slow homeserver or internet connection
2. Try and sign in with QR code

#### What did you expect?

Device to be signed in and have cross signing set up.

#### What happened instead?

An error was shown:

image

### Your phone model

_No response_

### Operating system version

_No response_

### Application version and app store

_No response_

### Homeserver

element.io

### Will you send logs?

Yes

### Are you willing to provide a PR?

Yes

### PR DESCRIPTION
**Pull request by hughns**
## Type of change

- [ ] Feature
- [x] Bugfix
- [ ] Technical
- [ ] Other :

## Content

Refactor of logic to determine whether sign in with QR is available so that it interacts with base URL resolved from well-known.

## Motivation and context

Previously the logic to determine if sign in with QR is supported was based on fetching the `versions`  directly from the actual user input of the homeserver.

However, this doesn't work when the user input needs to be resolved to a new base URL using well-known.

To demonstrate:

- enter `element.io` and no QR is offered
- enter `element.ems.host` and QR is offered

I've used the existing pattern from `SelectedHomeserverState`.

## Tests

- Tap `I already have an account`
- Press `Edit` next to homeserver
- Enter `element.io`
- Press `Next`
- The scan QR button should show

## Tested devices

- [ ] Physical
- [x] Emulator
- OS version(s):

## Checklist

- [ ] Changes has been tested on an Android device or Android emulator with API 21
- [ ] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#accessibility
- [x] Pull request is based on the develop branch
- [x] Pull request includes a new file under ./changelog.d. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#changelog
- [ ] Pull request includes screenshots or videos if containing UI changes
- [x] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [ ] You've made a self review of your PR
- [ ] If you have modified the screen flow, or added new screens to the application, you have updated the test [UiAllScreensSanityTest.allScreensTest()](https://github.com/vector-im/element-android/blob/main/vector/src/androidTest/java/im/vector/app/ui/UiAllScreensSanityTest.kt#L73)

Signed-off-by: Hugh Nimmo-Smith <hughns@element.io>

### CODE REVIEW

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/auth/AuthenticationService.kt [hunk 1]
```diff
@@ -125,12 +125,6 @@ interface AuthenticationService {
             deviceId: String? = null
     ): Session
 
-    /**
-     * @param homeServerConnectionConfig the information about the homeserver and other configuration
-     * Return true if qr code login is supported by the server, false otherwise.
-     */
-    suspend fun isQrLoginSupported(homeServerConnectionConfig: HomeServerConnectionConfig): Boolean
```
Comment (bmarty) [inline matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/auth/AuthenticationService.kt:132]: TBH, I am happy to see this API being removed :)

**Review by bmarty — APPROVED** [review]
LGTM, thanks!

**Comment by bmarty** [comment]
(the tests are not compiling, can you fix that please?)
