### PR TITLE
Avoid crashes from unknown exceptions on lockscreen key migration.

### LINKED ISSUE #6769: Crash - KeyStoreCrypto.ensureKey - RuntimeException
```
Exception java.lang.RuntimeException
```

```
Exception java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:666)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:967)
Caused by java.lang.reflect.InvocationTargetException:
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:656)
Caused by java.lang.reflect.InvocationTargetException:
  at java.lang.reflect.Method.invoke
  at com.airbnb.mvrx.MavericksFactory.create (MavericksFactory.kt:12)
  at androidx.lifecycle.ViewModelProvider$Factory$-CC.$default$create (ViewModelProvider.kt:2)
  at com.airbnb.mvrx.MavericksViewModelProvider.get$default (MavericksViewModelProvider.kt:39)
  at im.vector.app.features.pin.lockscreen.ui.LockScreenFragment$special$$inlined$fragmentViewModel$default$1.invoke (MavericksExtensions.kt:10)
  at im.vector.app.features.pin.lockscreen.ui.LockScreenFragment$special$$inlined$fragmentViewModel$default$1.invoke (MavericksExtensions.kt:1)
  at com.airbnb.mvrx.DefaultViewModelDelegateFactory$createLazyViewModel$1.invoke (ViewModelDelegateProvider.kt:2)
  at com.airbnb.mvrx.DefaultViewModelDelegateFactory$createLazyViewModel$1.invoke (ViewModelDelegateProvider.kt:1)
  at com.airbnb.mvrx.lifecycleAwareLazy.getValue (lifecycleAwareLazy.kt:5)
  at com.airbnb.mvrx.lifecycleAwareLazy$initializeWhenCreated$1.onCreate (lifecycleAwareLazy.kt:1)
  at androidx.lifecycle.FullLifecycleObserverAdapter.onStateChanged (FullLifecycleObserverAdapter.java:8)
  at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent (LifecycleRegistry.java:3)
  at androidx.lifecycle.LifecycleRegistry.sync (LifecycleRegistry.java:45)
  at androidx.lifecycle.LifecycleRegistry.moveToState (LifecycleRegistry.java:7)
  at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent (LifecycleRegistry.java:2)
  at androidx.fragment.app.Fragment.performCreate (Fragment.java:9)
  at androidx.fragment.app.FragmentStateManager.create (FragmentStateManager.java:5)
  at androidx.fragment.app.FragmentStateManager.moveToExpectedState (FragmentStateManager.java:28)
  at androidx.fragment.app.FragmentManager.executeOpsTogether (FragmentManager.java:122)
  at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute (FragmentManager.java:9)
  at androidx.fragment.app.FragmentManager.execPendingActions (FragmentManager.java:14)
  at androidx.fragment.app.FragmentManager.dispatchStateChange (FragmentManager.java:10)
  at androidx.fragment.app.FragmentActivity.onStart (FragmentActivity.java:12)
  at androidx.appcompat.app.AppCompatActivity.onStart (AppCompatActivity.java:1)
  at android.app.Instrumentation.callActivityOnStart (Instrumentation.java:1436)
  at android.app.Activity.performStart (Activity.java:8188)
  at android.app.ActivityThread.handleStartActivity (ActivityThread.java:3547)
  at android.app.servertransaction.TransactionExecutor.performLifecycleSequence (TransactionExecutor.java:221)
  at android.app.servertransaction.TransactionExecutor.cycleToPath (TransactionExecutor.java:201)
  at android.app.servertransaction.TransactionExecutor.executeLifecycleState (TransactionExecutor.java:173)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:97)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2135)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:236)
  at android.app.ActivityThread.main (ActivityThread.java:8059)
Caused by java.security.InvalidAlgorithmParameterException: java.lang.IllegalStateException: At least one biometric must be enrolled to create keys requiring user authentication for every use
  at android.security.keystore.AndroidKeyStoreKeyGeneratorSpi.engineInit (AndroidKeyStoreKeyGeneratorSpi.java:252)
  at android.security.keystore.AndroidKeyStoreKeyGeneratorSpi$AES.engineInit (AndroidKeyStoreKeyGeneratorSpi.java:53)
  at javax.crypto.KeyGenerator.init (KeyGenerator.java:519)
  at javax.crypto.KeyGenerator.init (KeyGenerator.java:502)
  at org.matrix.android.sdk.api.securestorage.SecretStoringUtils.getOrGenerateSymmetricKeyForAliasM (SecretStoringUtils.kt:13)
  at org.matrix.android.sdk.api.securestorage.SecretStoringUtils.ensureKey (SecretStoringUtils.kt:1)
  at im.vector.app.features.pin.lockscreen.crypto.KeyStoreCrypto.ensureKey (KeyStoreCrypto.kt:1)
  at im.vector.app.features.pin.lockscreen.crypto.migrations.SystemKeyV1Migrator.migrate (SystemKeyV1Migrator.kt:3)
  at im.vector.app.features.pin.lockscreen.crypto.LockScreenKeysMigrator.migrateIfNeeded (LockScreenKeysMigrator.kt:9)
  at im.vector.app.features.pin.lockscreen.ui.LockScreenViewModel$1.invokeSuspend (LockScreenViewModel.kt:2)
  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith (ContinuationImpl.kt:3)
  at kotlinx.coroutines.DispatchedTask.run (DispatchedTask.kt:18)
  at kotlinx.coroutines.EventLoopImplBase.processNextEvent (EventLoop.common.kt:21)
  at kotlinx.coroutines.BuildersKt.runBlocking
  at kotlinx.coroutines.BuildersKt.runBlocking$default
  at im.vector.app.features.pin.lockscreen.ui.LockScreenViewModel.<init> (LockScreenViewModel.kt:8)
  at im.vector.app.DaggerVectorApplication_HiltComponents_SingletonC$MavericksViewModelCImpl$SwitchingProvider$1.create (DaggerVectorApplication_HiltComponents_SingletonC.java:14)
  at im.vector.app.core.di.HiltMavericksViewModelFactory.create (HiltMavericksViewModelFactory.kt:6)
  at im.vector.app.features.pin.lockscreen.ui.LockScreenViewModel$Companion.create
  at im.vector.app.features.pin.lockscreen.ui.LockScreenViewModel$Companion.create (LockScreenViewModel.kt:1)
Caused by java.lang.IllegalStateException: At least one biometric must be enrolled to create keys requiring user authentication for every use
  at android.security.keystore.KeymasterUtils.addSids (KeymasterUtils.java:110)
  at android.security.keystore.KeymasterUtils.addUserAuthArgs (KeymasterUtils.java:174)
  at android.security.keystore.AndroidKeyStoreKeyGeneratorSpi.engineInit (AndroidKeyStoreKeyGeneratorSpi.java:250)

```

| Occurrences (30 days) | Total Occurrences | Impacted users (lifetime) |
| --- | --- | --- |
| 22 | 22 | 22 |

https://play.google.com/console/u/0/developers/{redacted}/app/{redacted}/vitals/crashes/0913c94c4eebbda4e0ff631ad29dabe6/details?installedFrom=PLAY_STORE&days=30&clustering=NEW&versionCode=40104312%2C40104311

### PR DESCRIPTION
**Pull request by jmartinesp**
## Type of change

- [ ] Feature
- [x] Bugfix
- [ ] Technical
- [ ] Other :

## Content

Fixes #6769 .

## Motivation and context

During lockscreen biometric key migrations, both `UserNotAuthenticatedException` and `KeyPermanentlyInvalidatedException` were caught, but there are many other possible exceptions that can be thrown. If any exceptions are thrown, we'll catch them, disable biometric authentication, then show pin code authentication.

## Tests

- Install a version < 1.4.31 (1.4.27 maybe?).
- Make sure you have biometric authentication enabled on your device.
- Enable biometric auth in Settings > Security and Privacy > Protect access. You'll need to enable pin code auth, then biometric one.
- Close the app.
- Disable biometric authentication on your *device* (delete all fingerprints, disable face unlock, etc.).
- Upgrade to this version and launch the app.

If the app doesn't crash, everything is fine. Biometric authentication should be disabled in this case too.

## Tested devices

- [x] Physical
- [ ] Emulator
- OS version(s): 12, 11.

## Checklist

- [ ] Changes has been tested on an Android device or Android emulator with API 21
- [ ] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#accessibility
- [x] Pull request is based on the develop branch
- [x] Pull request includes a new file under ./changelog.d. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#changelog
- [ ] Pull request includes screenshots or videos if containing UI changes
- [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [x] You've made a self review of your PR
- [ ] If you have modified the screen flow, or added new screens to the application, you have updated the test [UiAllScreensSanityTest.allScreensTest()](https://github.com/vector-im/element-android/blob/main/vector/src/androidTest/java/im/vector/app/ui/UiAllScreensSanityTest.kt#L73)

### CODE REVIEW

File: vector/src/main/java/im/vector/app/features/pin/lockscreen/crypto/migrations/MissingSystemKeyMigrator.kt [hunk 1]
```diff
@@ -41,14 +39,15 @@ class MissingSystemKeyMigrator @Inject constructor(
...
-                Timber.e("Could not automatically create biometric key because it was invalidated.", e)
-            } catch (e: UserNotAuthenticatedException) {
-                Timber.e("Could not automatically create biometric key because there are no enrolled biometric authenticators.", e)
+            val systemKeyStoreCrypto = keystoreCryptoFactory.provide(systemKeyAlias, true)
+            runCatching {
+                systemKeyStoreCrypto.ensureKey()
+            }.onFailure { e ->
+                Timber.e(e, "Could not automatically create biometric key. Biometric authentication will be disabled.")
+                systemKeyStoreCrypto.deleteKey()
+                vectorPreferences.setUseBiometricToUnlock(false)
```
Comment (ouchadam) [inline vector/src/main/java/im/vector/app/features/pin/lockscreen/crypto/migrations/MissingSystemKeyMigrator.kt:50]: does this mean we've fallen back to prompting for a pin?

Comment (jmartinesp) [reply vector/src/main/java/im/vector/app/features/pin/lockscreen/crypto/migrations/MissingSystemKeyMigrator.kt:50]: Yes. It's not a great solution, but I can see no alternative. If the migration fails, that's because the key is no longer valid and biometric auth won't work anyway even if the key exists.

**Review by ouchadam — APPROVED** [review]
:100: LGTM!
