### PR TITLE
Fix issues with matrix.to deep linking

### LINKED ISSUE #2349: Properly support matrix.to links on android app
Matrix.to links do not properly work for user links

-> It opens the RoomMember Profile, but there is no 'chat' button, just ignore
-> Seems that it only opens if the app was not already opened (does nothing..)

+ As per https://github.com/matrix-org/matrix.to/issues/165 we should probably support custom url scheme matrixto://

### PR DESCRIPTION
**Pull request by BillCarsonFr**
matrix.to deep linking had some issues:
 - Clicking a matrix.to link works only the first time
 - Could end up with two instances of the app 

Home activity implements navigation interceptor to display the matrix to bottom sheet

Fixes #2349

image

image

### CODE REVIEW

File: vector/src/main/java/im/vector/app/features/matrixto/MatrixToBottomSheet.kt [hunk 1]
```diff
@@ -43,21 +58,100 @@ class MatrixToBottomSheet(private val matrixItem: MatrixItem) : VectorBaseBottom
...
+        }
+
+        fun withUserId(userId: String, listener: InteractionListener?): MatrixToBottomSheet {
+            return MatrixToBottomSheet().apply {
+                arguments = Bundle().apply {
+                    putParcelable(MvRx.KEY_ARG, MatrixToBottomSheet.MatrixToArgs(
+                            matrixToLink = null,
+                            userId = userId
+                    ))
+                }
```
Comment (bmarty) [inline vector/src/main/java/im/vector/app/features/matrixto/MatrixToBottomSheet.kt:154]: Maybe we can have only one method and determine later if the String is a userId or a matrixTo link? Or keep only the withLink method, and convert the userId to a matrixTo link first, so this BottomSheet will always take a matrixTo link as parameter, which make sense regarding its name (MatrixToBottomSheet)

File: vector/src/main/java/im/vector/app/features/matrixto/MatrixToBottomSheetViewModel.kt [hunk 2]
```diff
@@ -0,0 +1,192 @@
...
+                    is PermalinkData.UserLink -> {
+                        val user = resolveUser(linkedId.userId)
+                        setState {
+                            copy(
+                                    matrixItem = Success(user.toMatrixItem()),
+                                    startChattingState = Success(Unit)
+                            )
+                        }
+                    }
+                    is PermalinkData.RoomLink -> TODO()
```
Comment (bmarty) [inline vector/src/main/java/im/vector/app/features/matrixto/MatrixToBottomSheetViewModel.kt:95]: The `TODO()` will make the app crash...

File: vector/src/main/java/im/vector/app/features/matrixto/MatrixToBottomSheetViewModel.kt [hunk 3]
```diff
@@ -0,0 +1,192 @@
...
+import org.matrix.android.sdk.api.session.profile.ProfileService
+import org.matrix.android.sdk.api.session.room.model.create.CreateRoomParams
+import org.matrix.android.sdk.api.session.user.model.User
+import org.matrix.android.sdk.api.util.JsonDict
+import org.matrix.android.sdk.api.util.toMatrixItem
+import org.matrix.android.sdk.internal.util.awaitCallback
+
+class MatrixToBottomSheetViewModel @AssistedInject constructor(
+        @Assisted initialState: MatrixToBottomSheetState,
+        @Assisted val args: MatrixToBottomSheet.MatrixToArgs,
```
Comment (bmarty) [inline vector/src/main/java/im/vector/app/features/matrixto/MatrixToBottomSheetViewModel.kt:51]: See the remark from @ganfra on the other PR.

File: vector/src/main/java/im/vector/app/features/matrixto/MatrixToBottomSheetViewModel.kt [hunk 4]
```diff
@@ -0,0 +1,192 @@
...
+        return (session.getUser(userId)
+                ?: tryOrNull {
+                    awaitCallback<JsonDict> {
+                        session.getProfile(userId, it)
+                    }
+                }?.let {
+                    User(userId, it[ProfileService.DISPLAY_NAME_KEY] as? String, it[ProfileService.AVATAR_URL_KEY] as? String)
+                }
+                // Create raw Uxid in case the user is not searchable
+                ?: User(userId, null, null))
```
Comment (bmarty) [inline vector/src/main/java/im/vector/app/features/matrixto/MatrixToBottomSheetViewModel.kt:134]: please remove the extra parenthesis

File: vector/src/main/java/im/vector/app/features/matrixto/MatrixToBottomSheetViewModel.kt [hunk 5]
```diff
@@ -0,0 +1,192 @@
...
+    }
+
+    private suspend fun resolveUser(userId: String): User {
+        return (session.getUser(userId)
+                ?: tryOrNull {
+                    awaitCallback<JsonDict> {
+                        session.getProfile(userId, it)
+                    }
+                }?.let {
+                    User(userId, it[ProfileService.DISPLAY_NAME_KEY] as? String, it[ProfileService.AVATAR_URL_KEY] as? String)
```
Comment (bmarty) [inline vector/src/main/java/im/vector/app/features/matrixto/MatrixToBottomSheetViewModel.kt:131]: this is ugly code, we could provide something better SDK side to convert a result of getProfile() to a User

File: vector/src/main/java/im/vector/app/features/matrixto/MatrixToBottomSheetViewModel.kt [hunk 6]
```diff
@@ -0,0 +1,192 @@
...
+            viewModelScope.launch(Dispatchers.IO) {
+                val adminE2EByDefault = rawService.getElementWellknown(session.myUserId)
+                        ?.isE2EByDefault()
+                        ?: true
+
+                val roomParams = CreateRoomParams()
+                        .apply {
+                            invitedUserIds.add(mxId)
+                            setDirectMessage()
+                            enableEncryptionIfInvitedUsersSupportIt = adminE2EByDefault
```
Comment (bmarty) [inline vector/src/main/java/im/vector/app/features/matrixto/MatrixToBottomSheetViewModel.kt:172]: this make me think that the method `createDirectRoom()` is not correct since it ignore the wellknown configuration.

File: vector/src/main/java/im/vector/app/features/matrixto/MatrixToBottomSheetViewModel.kt [hunk 7]
```diff
@@ -0,0 +1,192 @@
...
+                        }
+
+                val roomId =
+                        try {
+                            awaitCallback<String> { session.createRoom(roomParams, it) }.also {
```
Comment (bmarty) [inline vector/src/main/java/im/vector/app/features/matrixto/MatrixToBottomSheetViewModel.kt:177]: no need to use `also` here, if you move the setState() call after the `try/catch` block

File: vector/src/main/java/im/vector/app/features/permalink/PermalinkHandlerActivity.kt [hunk 8]
```diff
@@ -45,23 +43,28 @@ class PermalinkHandlerActivity : VectorBaseActivity() {
...
+        // We forward intent to HomeActivity (singleTask) to avoid the dueling app problem
+        // https://stackoverflow.com/questions/25884954/deep-linking-and-multiple-app-instances
+        intent.setClass(this, HomeActivity::class.java)
+        intent.flags = Intent.FLAG_ACTIVITY_CLEAR_TOP or Intent.FLAG_ACTIVITY_SINGLE_TOP
+        startActivity(intent)
+
+        finish()
+    }
+
+    override fun onNewIntent(intent: Intent?) {
```
Comment (bmarty) [inline vector/src/main/java/im/vector/app/features/permalink/PermalinkHandlerActivity.kt:65]: I do not think it is necessary to add `onNewIntent()` here.

File: vector/src/main/java/im/vector/app/features/usercode/UserCodeSharedViewModel.kt [hunk 9]
```diff
@@ -145,22 +148,36 @@ class UserCodeSharedViewModel @AssistedInject constructor(
...
+                    val user = session.getUser(linkedId.userId)
+                            ?: tryOrNull {
+                                awaitCallback<JsonDict> {
+                                    session.getProfile(linkedId.userId, it)
+                                }
+                            }?.let {
+                                User(linkedId.userId, it[ProfileService.DISPLAY_NAME_KEY] as? String, it[ProfileService.AVATAR_URL_KEY] as? String)
+                            }
+                            // Create raw Uxid in case the user is not searchable
+                            ?: User(linkedId.userId, null, null)
```
Comment (bmarty) [inline vector/src/main/java/im/vector/app/features/usercode/UserCodeSharedViewModel.kt:165]: Duplicated code :/

**Review by bmarty — CHANGES_REQUESTED** [review]
Thanks for the PR, a few remarks

File: vector/src/main/java/im/vector/app/features/matrixto/MatrixToBottomSheetViewModel.kt (hunk 2 above)
Comment (BillCarsonFr) [reply vector/src/main/java/im/vector/app/features/matrixto/MatrixToBottomSheetViewModel.kt:95]: yes but not called yet, anyhow will log silently instead

File: vector/src/main/java/im/vector/app/features/matrixto/MatrixToBottomSheet.kt (hunk 1 above)
Comment (BillCarsonFr) [reply vector/src/main/java/im/vector/app/features/matrixto/MatrixToBottomSheet.kt:154]: That's what i thought and how it was at the beginning, but side effect is that callers would have to resolve user first to get the matrix item, for that callers fragment/activity needed to have waiting view show/hide... leading to code duplication
Maskes more sense that matrix.to is self contained and do network calls

File: vector/src/main/java/im/vector/app/features/usercode/UserCodeSharedViewModel.kt (hunk 9 above)
Comment (BillCarsonFr) [reply vector/src/main/java/im/vector/app/features/usercode/UserCodeSharedViewModel.kt:165]: added resolveUser in UserService

File: vector/src/main/java/im/vector/app/features/matrixto/MatrixToBottomSheetViewModel.kt (hunk 3 above)
Comment (BillCarsonFr) [reply vector/src/main/java/im/vector/app/features/matrixto/MatrixToBottomSheetViewModel.kt]: done

Comment (BillCarsonFr) [reply vector/src/main/java/im/vector/app/features/matrixto/MatrixToBottomSheetViewModel.kt]: done

File: vector/src/main/java/im/vector/app/features/matrixto/MatrixToBottomSheetViewModel.kt (hunk 4 above)
Comment (BillCarsonFr) [reply vector/src/main/java/im/vector/app/features/matrixto/MatrixToBottomSheetViewModel.kt]: moved

**Review by bmarty — APPROVED** [review]
Thanks for the update!
