### PR TITLE
replyTo are not updated if the original message is edited

### LINKED ISSUE #5546: If you reply to a redaction, the redacted text still appears
### Steps to reproduce

- Steps to reproduce
- Send a message
- Reply to that message
- Redact the original message
- The redacted text is displayed, presumably because it's contained in the reply as fallback text

Note: 
- The behavior is correct on Element-Web
- Issue reproduced in Element-iOS (https://github.com/vector-im/element-ios/issues/5823)

### Outcome

Element-android would not display this text, even though the client has access to it.

### Your phone model

_No response_

### Operating system version

_No response_

### Application version and app store

_No response_

### Homeserver

_No response_

### Will you send logs?

No

### PR DESCRIPTION
**Pull request by Claire1817**
## Type of change

- [ ] Feature
- [X] Bugfix
- [ ] Technical
- [ ] Other :

## Content
Before printing a replied event, update it with the event from the DB.
I will do another PR for the rédaction.
Same solution implemented in iOs.

## Motivation and context
Closes #5546 

## Screenshots / GIFs

https://user-images.githubusercontent.com/15031750/176211466-1a62184e-9c13-42f2-b7e6-3930d7c38379.mp4

## Tests

Send a message, replied to the event and edit the first message.

## Tested devices

- [X] Physical
- [X] Emulator
- OS version(s):

## Checklist

- [X] Changes has been tested on an Android device or Android emulator with API 21
- [X] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#accessibility
- [X] Pull request is based on the develop branch
- [X] Pull request includes a new file under ./changelog.d. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#changelog
- [X] Pull request includes screenshots or videos if containing UI changes
- [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [X] You've made a self review of your PR
- [ ] If you have modified the screen flow, or added new screens to the application, you have updated the test [UiAllScreensSanityTest.allScreensTest()](https://github.com/vector-im/element-android/blob/main/vector/src/androidTest/java/im/vector/app/ui/UiAllScreensSanityTest.kt#L73)

### CODE REVIEW

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/LoadTimelineStrategy.kt [hunk 1]
```diff
@@ -240,10 +248,45 @@ internal class LoadTimelineStrategy constructor(
...
+            eventsUpdated
+        }
+    }
+
+    private fun updateRepliedEventIfNeeded(events: List<TimelineEvent>): List<TimelineEvent> {
+        return events.map {
+            if (it.isReply() && it.isEncrypted()) {
+                    createNewRepliedEvent(it)?.let { newEvent ->
+                        it.copy(root = newEvent)
+                    } ?: it
```
Comment (Claire1817) [inline matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/LoadTimelineStrategy.kt:264]: For not encrypted message, how can i get the eventId ?

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/timeline/TimelineEvent.kt [hunk 2]
```diff
@@ -65,7 +65,7 @@ data class TimelineEvent(
 
     init {
         if (BuildConfig.DEBUG) {
-            assert(eventId == root.eventId)
+//            assert(eventId == root.eventId)
```
[the remark this answers is not in the document]
Comment (bmarty) [reply matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/timeline/TimelineEvent.kt:68]: `this.eventId` should always have the same value than `this.root.eventId`. In which case this was not true on your side?

File: changelog.d/5546.bugfix [hunk 3]
```diff
@@ -0,0 +1 @@
+If you reply to a redaction, the redacted text still appears
```
Comment (bmarty) [inline changelog.d/5546.bugfix:1]: This does not match the content of this PR, this is about message edition. can you update please?

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/timeline/TimelineEvent.kt (hunk 2 above)
[the remark this answers is not in the document]
Comment (Claire1817) [reply matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/timeline/TimelineEvent.kt:68]: I wanted to use some code from LocalEventFactory to avoid the code duplication. In ```createEvent```, a new eventId is created for the event. 
In my case i don't know if i should use the past id even if i updated the relatedTo part ? or should i create a new id ? 🤔 
Knowing i never update the DB, i juste update the object before print it.

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/LoadTimelineStrategy.kt [hunk 4]
```diff
@@ -240,10 +249,50 @@ internal class LoadTimelineStrategy constructor(
 
     fun buildSnapshot(): List<TimelineEvent> {
         val events = buildSendingEvents() + timelineChunk?.builtItems(includesNext = true, includesPrev = true).orEmpty()
+        val eventsUpdated = updateRepliedEventIfNeeded(events)
```
Comment (ganfra) [inline matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/LoadTimelineStrategy.kt:252]: I'd avoid using map here, will slow down a lot timeline when there is a lot of events already loaded. It should be handled directly inside the buildEvents

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/timeline/TimelineEvent.kt (hunk 2 above)
[the remark this answers is not in the document]
Comment (Claire1817) [reply matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/timeline/TimelineEvent.kt:68]: @ganfra told me that i should keep the id.

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/TimelineChunk.kt [hunk 5]
```diff
@@ -413,7 +425,43 @@ internal class TimelineChunk(
             buildReadReceipts = timelineSettings.buildReadReceipts
     ).let {
         // eventually enhance with ui echo?
-        (uiEchoManager?.decorateEventWithReactionUiEcho(it) ?: it)
+        uiEchoManager?.decorateEventWithReactionUiEcho(it)
+
+        if (it.isReply()) {
```
Comment (ganfra) [inline matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/TimelineChunk.kt:430]: Can you add a name to the let scope param instead of using `it`

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/LocalEchoEventFactory.kt [hunk 6]
```diff
@@ -507,13 +507,13 @@ internal class LocalEchoEventFactory @Inject constructor(
...
     }
 
-    private fun createMessageEvent(roomId: String, content: MessageContent? = null): Event {
-        return createEvent(roomId, EventType.MESSAGE, content.toContent())
+    private fun createMessageEvent(roomId: String, content: MessageContent? = null, currentEventId: String? = null): Event {
+        return createEvent(roomId, EventType.MESSAGE, content.toContent(), currentEventId)
     }
 
-    fun createEvent(roomId: String, type: String, content: Content?): Event {
+    fun createEvent(roomId: String, type: String, content: Content?, currentEventId: String? = null): Event {
```
Comment (ganfra) [inline matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/LocalEchoEventFactory.kt:514]: It feels a bit hacky to use an eventId on the LocalEchoEventFactory, it should only gives Event with local.id.
I don't think we need a complete new Event but just a new Content. Create a method which returns the Content and uses this in both the Timeline and this Factory 
```
MessageTextContent(
                msgType = MessageType.MSGTYPE_TEXT,
                format = MessageFormat.FORMAT_MATRIX_HTML,
                body = replyFallback,
```

**Review by ganfra — CHANGES_REQUESTED** [review]

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/LocalEchoEventFactory.kt [hunk 7]
```diff
@@ -573,6 +573,51 @@ internal class LocalEchoEventFactory @Inject constructor(
         return clock.epochMillis()
     }
 
+    fun createReplyTextContent(
```
Comment (ganfra) [inline matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/LocalEchoEventFactory.kt:576]: You should use this in createReplyTextEvent

File: matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/TimelineChunk.kt [hunk 8]
```diff
@@ -451,14 +452,21 @@ internal class TimelineChunk(
...
                         timelineEventMapper.map(timelineEventEntity),
                         replyText,
                         false,
-                        showInThread = false,
-                        currentEventId = currentTimelineEvent.eventId
-
+                        showInThread = false
+                )
+                val event = currentTimelineEvent.root
+                Event(
```
Comment (ganfra) [inline matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/TimelineChunk.kt:462]: You are missing the transient fields here

**Review by ganfra — APPROVED** [review]
Thanks for the changes
