### PR TITLE
Fix notif badge for space invite

### LINKED ISSUE #4059: Space Invites are not lighting up the drawer menu
### Steps to reproduce

When there is a pending space invite, the left drawer button should display a notification

image

### Your phone model

_No response_

### Operating system version

_No response_

### Application version and app store

_No response_

### Homeserver

_No response_

### Have you submitted a rageshake?

No

### PR DESCRIPTION
**Pull request by BillCarsonFr**
Fixes #4059

image

### CODE REVIEW

File: vector/src/main/java/im/vector/app/features/home/UnreadMessagesSharedViewModel.kt [hunk 1]
```diff
@@ -161,15 +173,18 @@ class UnreadMessagesSharedViewModel @AssistedInject constructor(@Assisted initia
...
                                     otherCount = RoomAggregateNotificationCount(
                                             rootCounts.fold(0, { acc, rs ->
                                                 acc + rs.notificationCount
-                                            }) + (counts.notificationCount.takeIf { selectedSpace != null } ?: 0),
+                                            }) + (counts.notificationCount.takeIf { selectedSpace != null } ?: 0)
+                                                    + spaceInviteCount,
                                             rootCounts.fold(0, { acc, rs ->
                                                 acc + rs.highlightCount
                                             }) + (counts.highlightCount.takeIf { selectedSpace != null } ?: 0)
+                                                    + spaceInviteCount
```
Comment (bmarty) [inline vector/src/main/java/im/vector/app/features/home/UnreadMessagesSharedViewModel.kt:187]: With this formatting it is really hard to read.
change to
```kotlin
                            CountInfo(
                                    homeCount = counts,
                                    otherCount = RoomAggregateNotificationCount(
                                            notificationCount = rootCounts.fold(0, { acc, rs -> acc + rs.notificationCount })
                                                    + (counts.notificationCount.takeIf { selectedSpace != null } ?: 0)
                                                    + spaceInviteCount,
                                            highlightCount = rootCounts.fold(0, { acc, rs -> acc + rs.highlightCount })
                                                    + (counts.highlightCount.takeIf { selectedSpace != null } ?: 0)
                                                    + spaceInviteCount
                                    )
                            )
```

**Review by bmarty — COMMENTED** [review]
LGTM, one remark about formatting

**Review by bmarty — APPROVED** [review]
I have improved the formatting
