### PR TITLE
[Session manager] Sessions without encryption support should not prompt to verify (PSG-1004)

### LINKED ISSUE #7733: [Session manager] Sessions without encryption support should not prompt to verify
### Steps to reproduce

When a session did not upload its crypto keys, the UI in session manager screens is not correct. It displays a "Verify" button which is not possible for this session.
UI should be updated to inform the user the session cannot be verified.

#### What did you expect?
Not to be able to verify sessions without encryption keys. Also, the app should not alert of unverified sessions which do not support encryption.

#### What happened instead?
"Verify" action is available for sessions without encryption keys.

### Your phone model

_No response_

### Operating system version

_No response_

### Application version and app store

_No response_

### Homeserver

_No response_

### Will you send logs?

No

### Are you willing to provide a PR?

Yes

### PR DESCRIPTION
**Pull request by mnaturel**
## Type of change

- [ ] Feature
- [x] Bugfix
- [ ] Technical
- [ ] Other :

## Content

Render a specific UI in session manager screens (main screen and session overview screen) when a session does not support encryption.

## Motivation and context

Closes #7733 
See also https://github.com/vector-im/element-web/issues/23722

## Tests

For my tests, I mocked locally the data (setting the `CryptoDeviceInfo` to `null`)
- Enable new Session manager labs flag
- Go to "Settings -> Security & Privacy -> Show all sessions"
- Check the UI for the current session is correct
- Press a session entry in the other sessions list which does support encryption
- Check the UI for the session overview screen is correct
- Press "Learn more"
- Check the displayed text is correct

## Tested devices

- [ ] Physical
- [x] Emulator
- OS version(s): Android 11

## Checklist

- [ ] Changes has been tested on an Android device or Android emulator with API 21
- [x] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#accessibility
- [x] Pull request is based on the develop branch
- [x] Pull request includes a new file under ./changelog.d. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#changelog
- [x] Pull request includes screenshots or videos if containing UI changes
- [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [x] You've made a self review of your PR
- [ ] If you have modified the screen flow, or added new screens to the application, you have updated the test [UiAllScreensSanityTest.allScreensTest()](https://github.com/vector-im/element-android/blob/main/vector/src/androidTest/java/im/vector/app/ui/UiAllScreensSanityTest.kt#L73)

### CODE REVIEW

File: vector/src/main/java/im/vector/app/features/settings/devices/v2/overview/SessionOverviewFragment.kt [hunk 1]
```diff
@@ -293,21 +293,28 @@ class SessionOverviewFragment :
...
-            R.string.device_manager_verification_status_verified
-        } else {
-            R.string.device_manager_verification_status_unverified
-        }
-        val descriptionResId = if (isVerified) {
-            R.string.device_manager_learn_more_sessions_verified_description
-        } else {
-            R.string.device_manager_learn_more_sessions_unverified
+    private fun showLearnMoreInfoVerificationStatus(roomEncryptionTrustLevel: RoomEncryptionTrustLevel?) {
+        val args = when(roomEncryptionTrustLevel) {
```
Comment (ElementBot) [inline vector/src/main/java/im/vector/app/features/settings/devices/v2/overview/SessionOverviewFragment.kt:297]: - :no_entry_sign: Missing spacing after "when"

File: vector/src/main/java/im/vector/app/features/settings/devices/v2/verification/GetEncryptionTrustLevelForDeviceUseCase.kt [hunk 2]
```diff
@@ -25,11 +25,15 @@ class GetEncryptionTrustLevelForDeviceUseCase @Inject constructor(
         private val getEncryptionTrustLevelForOtherDeviceUseCase: GetEncryptionTrustLevelForOtherDeviceUseCase,
 ) {
 
-    fun execute(currentSessionCrossSigningInfo: CurrentSessionCrossSigningInfo, cryptoDeviceInfo: CryptoDeviceInfo?): RoomEncryptionTrustLevel {
+    fun execute(currentSessionCrossSigningInfo: CurrentSessionCrossSigningInfo, cryptoDeviceInfo: CryptoDeviceInfo?): RoomEncryptionTrustLevel? {
+        if(cryptoDeviceInfo == null) {
```
Comment (ElementBot) [inline vector/src/main/java/im/vector/app/features/settings/devices/v2/verification/GetEncryptionTrustLevelForDeviceUseCase.kt:29]: - :no_entry_sign: Missing spacing after "if"

**Review by fedrunov — APPROVED** [review]
LGTM
