### PR TITLE
[Timeline] Memory leak in audio message playback tracker

### LINKED ISSUE #6678: [Timeline] Memory leak in audio message playback tracker
### Steps to reproduce

When enabling LeakCanary, we see there is a missing call to clear the listeners in `AudioMessagePlaybackTracker` when the `TimelineFragment` is destroyed.

#### What did you expect?
No memory leak.

#### What happened instead?
A memory leak is caught.

### Your phone model

_No response_

### Operating system version

_No response_

### Application version and app store

_No response_

### Homeserver

_No response_

### Will you send logs?

No

### Are you willing to provide a PR?

Yes

### PR DESCRIPTION
**Pull request by mnaturel**
## Type of change

- [ ] Feature
- [ ] Bugfix
- [ ] Technical
- [x] Other : Enhancement

## Content

Clearing the listeners on `AudioMessagePlaybackTracker` when `TimelineFragment` is destroyed.

## Motivation and context

Closes #6678 

## Tests

To check, you need to enable LeakCanary. When doing tests, check there is no leaks notified and related to `AudioMessagePlaybackTracker`.

- Go to a room timeline
- Press back

## Tested devices

- [ ] Physical
- [x] Emulator
- OS version(s): Android 11

## Checklist

- [ ] Changes has been tested on an Android device or Android emulator with API 21
- [ ] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#accessibility
- [x] Pull request is based on the develop branch
- [x] Pull request includes a new file under ./changelog.d. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#changelog
- [ ] Pull request includes screenshots or videos if containing UI changes
- [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [x] You've made a self review of your PR
- [ ] If you have modified the screen flow, or added new screens to the application, you have updated the test [UiAllScreensSanityTest.allScreensTest()](https://github.com/vector-im/element-android/blob/main/vector/src/androidTest/java/im/vector/app/ui/UiAllScreensSanityTest.kt#L73)

### CODE REVIEW

**Review by bmarty — APPROVED** [review]
LGTM, thanks to investigate those issues!

File: vector/src/main/java/im/vector/app/features/home/room/detail/TimelineFragment.kt [hunk 1]
```diff
@@ -963,6 +963,7 @@ class TimelineFragment @Inject constructor(
 
     override fun onDestroyView() {
         audioMessagePlaybackTracker.makeAllPlaybacksIdle()
+        audioMessagePlaybackTracker.clear()
```
Comment (bmarty) [inline vector/src/main/java/im/vector/app/features/home/room/detail/TimelineFragment.kt:966]: Can it be handled in `MessageComposerViewModel`, since we are calling `AudioMessageHelper.clearTracker()` there?

Comment (mnaturel) [reply vector/src/main/java/im/vector/app/features/home/room/detail/TimelineFragment.kt]: Yes you are right. This is cleaner. I have used the `MessageComposerAction.EndAllVoiceActions` which in fact was not used. See [5c2e0ee](https://github.com/vector-im/element-android/pull/6679/commits/5c2e0ee7e61245fd1d627711ce05d83012f289a0).

**Review by bmarty — COMMENTED** [review]
Thanks for the update.
We will have to be careful when the handle action will be a suspend function, cause action could be cancelled if the scope is cancelled.
Else move this code to the `fun onCleared()` of the ViewModel?

**Comment by mnaturel** [comment]
> Thanks for the update. We will have to be careful when the handle action will be a suspend function, cause action could be cancelled if the scope is cancelled. Else move this code to the `fun onCleared()` of the ViewModel?

Yes I agree, I thought about that case. Now it is okay since we don't launch it inside a coroutine. For safety, I changed it to call the clear method directly. See [48b6919](https://github.com/vector-im/element-android/pull/6679/commits/48b6919dc2307d118005f349337bc89c5d67fbc0)
