### PR TITLE
Fix crashes

### LINKED ISSUE #8409: Crash when entering the "Protect access" screen.
Go to settings / security / protect access

The app crashes.

### PR DESCRIPTION
**Pull request by bmarty**
## Type of change

- [ ] Feature
- [x] Bugfix
- [ ] Technical
- [ ] Other :

## Content

`repeatOnLifecycle` was not used properly. This PR does some cleanup.

Reviewer: please ignore spaces when comparing.

## Motivation and context

Fixes #8409

## Tests

- I have manaully tested the impacted code without any issue.

## Tested devices

- [ ] Physical
- [x] Emulator
- OS version(s):

## Checklist

- [ ] Changes has been tested on an Android device or Android emulator with API 21
- [ ] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#accessibility
- [ ] Pull request is based on the develop branch
- [ ] Pull request includes a new file under ./changelog.d. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#changelog
- [ ] Pull request includes screenshots or videos if containing UI changes
- [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [ ] You've made a self review of your PR
- [ ] If you have modified the screen flow, or added new screens to the application, you have updated the test [UiAllScreensSanityTest.allScreensTest()](https://github.com/vector-im/element-android/blob/main/vector/src/androidTest/java/im/vector/app/ui/UiAllScreensSanityTest.kt#L73)

### CODE REVIEW

File: vector/src/main/java/im/vector/app/features/location/preview/LocationPreviewFragment.kt [hunk 1]
```diff
@@ -81,9 +79,7 @@ class LocationPreviewFragment :
         views.mapView.onCreate(savedInstanceState)
 
         viewLifecycleOwner.lifecycleScope.launch {
-            viewLifecycleOwner.repeatOnLifecycle(Lifecycle.State.CREATED) {
```
Comment (Florian14) [inline vector/src/main/java/im/vector/app/features/location/preview/LocationPreviewFragment.kt:84]: I don't know if this code was here for a certain reason, but I agree that it does not seem necessary since we're in the `onViewCreated` method

**Review by Florian14 — APPROVED** [review]
Changes LGTM, not tested
