### PR TITLE
Fix: Loudspeaker is always used

### LINKED ISSUE #1685: Loudspeaker is always used
Whether wired headset is connected or not, or which sound device is selected: `Phone`, `Headset` or `Speaker` the loudspeaker is always used.

### PR DESCRIPTION
**Pull request by onurays**
Fixes #1685

### CODE REVIEW

File: vector/src/main/java/im/vector/app/features/call/CallAudioManager.kt [hunk 1]
```diff
@@ -246,7 +246,7 @@ class CallAudioManager(
     }
 
     private fun isHeadsetOn(): Boolean {
-        return isWiredHeadsetOn() || isBluetoothHeadsetOn()
+        return isWiredHeadsetOn() || (audioManager?.let { isBluetoothHeadsetConnected(it) } ?: false)
```
Comment (bmarty) [inline vector/src/main/java/im/vector/app/features/call/CallAudioManager.kt:249]: `audioManager` should only be used from a single thread, according to Valere's comment.
The fix LGTM, but let discuss with Valere about it.

Comment (BillCarsonFr) [reply vector/src/main/java/im/vector/app/features/call/CallAudioManager.kt:249]: Should be ok to read state

Comment (bmarty) [reply vector/src/main/java/im/vector/app/features/call/CallAudioManager.kt:249]: Thanks
